/* Actual JSX render functions, hook/network doubles. Static layout fixture,
 * not a Next build, hydration test, live backend or scientific discovery. */
const fs=require('fs'),path=require('path'),ts=require(process.env.TYPESCRIPT_PATH||path.resolve(path.dirname(process.execPath),'../lib/node_modules/typescript/lib/typescript.js'));
const root=path.resolve(__dirname,'..'),out=process.argv[2]||path.join(root,'build/research-layout');fs.mkdirSync(out,{recursive:true});
let owner='',index=0,scenario='populated';const now='2026-09-08T12:00:00Z';
const tasks=[{id:'review',title:'Compare competing explanations',kind:'literature',question:'Which observations discriminate the proposed mechanisms?',method:'Review retrieved abstracts, then identify required full-text comparisons.',inputs:['Citable sources','Relevant measurement definitions'],depends_on:[],success_criterion:'Differences and uncertainty recorded without inventing evidence.',deliverable:'An evidence comparison and a data-acquisition plan.',next_prompt:'Prepare a source-grounded comparison.',search_query:'mechanism evidence uncertainty'},
{id:'data',title:'Inspect measurements and calibration requirements',kind:'data_analysis',question:'Do available measurements identify the parameters?',method:'Inspect aggregate missingness and variable units; define a calibration protocol.',inputs:['Measured time series','Units and data provenance'],depends_on:['review'],success_criterion:'Required measurements and unresolved confounding are explicit.',deliverable:'A documented data/validation contract.',next_prompt:'Prepare the data review.',search_query:''},
{id:'study',title:'Propose the next discriminating experiment',kind:'simulation',question:'Which permitted changes best separate the hypotheses?',method:'Bounded parameter search with whole-trajectory constraints and independent verification.',inputs:['Calibrated model','Compute approval'],depends_on:['data'],success_criterion:'Diverse candidates are compared against prespecified checks.',deliverable:'An unexecuted Discovery protocol.',next_prompt:'Design the bounded study.',search_query:''}];
const record={id:'plan',project_id:'world',created_at:now,status:'proposed_not_executed',plan:{title:'A staged investigation—not a preselected demonstration',goal:'Investigate distinct candidate behaviors and their scientific plausibility.',tractable_question:'Which measurements can rule out competing explanations?',rationale:'Start with evidence, then design informative numerical work within the available compute budget.',knowns:['The earlier run completed a finite initial-value calculation.'],unknowns:['Whether its measurements distinguish the intended phenomena.','Which model assumptions require independent data.'],source_ids:[],limitations:['This plan is not a finding, cure, or validated physical model.','External domain-engine execution and expert review remain separate.'],tasks}};
const workspace={plans:[record],tasks:[{id:'rec',plan_id:'plan',task_id:'review',status:'in_progress',notes:'Full papers not reviewed yet.',created_at:now}],searches:[{id:'query',status:'completed',query:'Synthetic fixture: mechanistic evidence',created_at:now,total_hits:1,results:[{id:'FIXTURE:1',title:'Presentation-only source fixture—not a real scientific paper',authors:'Synthetic layout data',year:'2026',doi:'',abstract_text:'No scientific evidence is asserted by this UI test.',url:'https://europepmc.org',scope:'Synthetic abstract fixture'}]},{id:'failed',status:'failed',query:'Example failed request',created_at:now,total_hits:null,error:'Service unavailable',results:[]}],data:[{id:'csv',name:'synthetic-measurements.csv',rows:20,sha256:'f'.repeat(64),provenance:'Synthetic layout fixture only.',columns:[{name:'time',finite_numeric:20,missing:0,nonfinite:0,mean:4.2},{name:'observation',finite_numeric:18,missing:2,nonfinite:0,mean:.45}],scope:'Descriptive statistics; no causal inference. Raw rows not retained.'}]};
const advice={route:'CPU/f64',reason:'Trajectory reductions are not implemented by the GPU lowerer.',admissible:true,candidate_evaluations:128,estimated_peak_bytes:150*1048576,available_memory_bytes:18*1073741824,cpu_workers:20,recommended_compute:{batch_size:20,max_wall_seconds:900},warnings:['Independent candidates parallelize; one trajectory remains sequential.'],scope:'Structural estimate only, not measured peak RSS or an ETA.'};
const React={Fragment:Symbol.for('react.fragment'),createElement:(type,props,...children)=>({type,props:{...(props||{}),children}}),useEffect:()=>{},useRef:x=>({current:x}),useMemo:fn=>fn(),useState:initial=>{const i=index++;let v=typeof initial==='function'?initial():initial;if(owner==='ResearchPlan'){if(i===0)v=scenario==='empty'?{plans:[],searches:[],tasks:[],data:[]}:workspace;if(i===6&&scenario==='error')v='Explicit query consent is required before public retrieval.';}if(owner==='ComputeAdvice'&&i===0)v=advice;return[v,()=>{}];}};
const icon=new Proxy({}, {get:(_,key)=>props=>React.createElement('span',{'aria-hidden':'true',className:'fixtureIcon'},'◇')});const cache={};
function load(file){file=path.resolve(file);if(cache[file])return cache[file].exports;const module={exports:{}};cache[file]=module;let source=fs.readFileSync(file,'utf8');const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React,target:ts.ScriptTarget.ES2022},reportDiagnostics:true});if(compiled.diagnostics?.length)throw Error(compiled.diagnostics.map(d=>ts.flattenDiagnosticMessageText(d.messageText,' ')).join('\n'));
 function req(id){if(id==='react')return React;if(id==='lucide-react')return icon;if(id==='next/link')return {__esModule:true,default:p=>React.createElement('a',{...p,href:p.href},p.children)};if(id==='@/lib/api')return{api:{}};if(id.startsWith('@/')){let p=path.join(root,'frontend/src',id.slice(2));if(!fs.existsSync(p))p+=fs.existsSync(p+'.jsx')?'.jsx':'.js';return load(p);}return require(id);}
 new Function('require','module','exports','React',compiled.outputText)(req,module,module.exports,React);return module.exports;}
const escape=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function render(node){if(node==null||typeof node==='boolean')return'';if(Array.isArray(node))return node.map(render).join('');if(typeof node!=='object')return escape(node);const {type,props}=node;if(typeof type==='function'){const before=[owner,index];owner=type.name;index=0;const child=type(props);const text=render(child);[owner,index]=before;return text;}if(type===React.Fragment)return render(props.children);if(!type)return'';
 const attrs=Object.entries(props||{}).filter(([k,v])=>!['children','key','ref','dangerouslySetInnerHTML'].includes(k)&&!k.startsWith('on')&&v!==false&&v!=null).map(([k,v])=>{if(k==='className')k='class';if(k==='htmlFor')k='for';if(k==='style')v=Object.entries(v).map(([a,b])=>a.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())+':'+(typeof b==='number'&&!['opacity','flex','flexGrow'].includes(a)?b+'px':b)).join(';');return typeof v==='boolean'?` ${k}`:` ${k}="${escape(v)}"`;}).join('');const open=`<${type}${attrs}>`;return['input','img','br','hr','meta','link'].includes(type)?open:open+render(props.children)+`</${type}>`;}
const Research=load(path.join(root,'frontend/src/components/workspace/ResearchPlan.jsx')).default,Advice=load(path.join(root,'frontend/src/components/workspace/ComputeAdvice.jsx')).default;
const css=['globals.css','workspace.css','research.css'].map(n=>fs.readFileSync(path.join(root,'frontend/styles',n),'utf8')).join('\n');
for(scenario of ['empty','populated','error'])for(const theme of ['dark','light']){
 const tree=React.createElement(Research,{project:{id:'world',question:'Investigate distinct modeled regimes'},manifest:{id:'manifest',title:'A bounded model'},busy:false,onPropose:async()=>{},refreshKey:0});
 const html=`<!doctype html><html data-theme="${theme}"><meta charset="utf-8"><style>${css}\nbody{overflow:auto;min-width:320px}.fixtureHost{max-width:var(--fixture-width,100%);margin:auto}.pfResearch{height:auto;overflow:visible}.fixtureBanner{padding:10px;color:var(--muted);font-size:11px}.fixtureIcon{display:inline-block;width:14px}</style><body><div class="fixtureHost"><div class="fixtureBanner">Actual JSX · synthetic presentation fixture · NOT a running scientific experiment</div>${render(tree)}${render(React.createElement(Advice,{manifest:{id:'manifest',trajectory:[{}],search:{enabled:true},constraints:[{}],falsification:[{}]}}))}</div></body></html>`;
 fs.writeFileSync(path.join(out,`${scenario}-${theme}.html`),html);
}console.log('Research fixture HTML:',out);
