import fs from 'node:fs';import assert from 'node:assert/strict';
const load=async name=>import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(new URL('../frontend/src/lib/'+name,import.meta.url))).toString('base64'));
const m=await load('research.js'),{api}=await load('api.js');let n=0;const check=(name,fn)=>{fn();n++;console.log('PASS',name);};
check('Distinct sphere radii',()=>{assert.equal(m.radiusFor({radius:.3},.01),.3);assert.equal(m.radiusFor({radius:.1},.01),.1);});
for(const x of [null,undefined,NaN,Infinity,-1,0,true,'0.3',{}])check('Invalid radius '+String(x),()=>assert.equal(m.radiusFor({radius:x},.02),.02));
const rows=[{plan_id:'a',task_id:'t',status:'completed',created_at:'2026-09-07T12:00:00Z'},{plan_id:'a',task_id:'t',status:'blocked',created_at:'2026-09-07T13:00:00Z'},{plan_id:'b',task_id:'t',status:'completed',created_at:'2026-09-07T14:00:00Z'}];
check('Latest assessment wins',()=>assert.equal(m.latestTask(rows,'a','t').status,'blocked'));
check('World/plan scoped progress',()=>assert.equal(m.latestTask(rows,'b','t').status,'completed'));
check('Missing task not completed',()=>assert.equal(m.latestTask(rows,'a','x'),null));
check('Single demo flagged',()=>assert(m.designGaps({}).some(x=>x.includes('One trajectory'))));
check('All design inputs not scientific proof',()=>assert.deepEqual(m.designGaps({search:{enabled:true},trajectory:[{}],constraints:[{}],falsification:[{}]}),[]));
check('Metric names include reductions once',()=>assert.equal(m.allMetrics({observables:[{name:'x'}],trajectory:[{name:'x'},{name:'peak'}]}).length,2));
check('Source URL allowlist',()=>{assert(m.sourceURL('https://europepmc.org/article/MED/1'));assert.equal(m.sourceURL('javascript:alert(1)'),null);assert.equal(m.sourceURL('https://europepmc.org.evil.example/x'),null);});
check('Task intent and no execution',()=>{const s=m.taskPrompt('goal',{title:'test',question:'q',method:'m',inputs:['real data'],success_criterion:'evidence',deliverable:'record',next_prompt:'prepare'});assert(s.includes('real data'));assert(s.includes('do not run'));});
check('Explicit intent choices include direct experimentation',()=>assert.equal(m.INTENTS.length,5));
let last;globalThis.fetch=async(url,options={})=>{last={url,options};return{ok:true,status:200,json:async()=>({})}};const signal=new AbortController().signal;
await api.researchSearch('p','query',false,signal);check('Consent never invented',()=>assert.equal(JSON.parse(last.options.body).consent,false));check('Search cancellation passed',()=>assert.equal(last.options.signal,signal));
await api.researchWorkspace('p',signal);check('Scoped research endpoint',()=>assert(last.url.endsWith('/api/projects/p/research')));
await api.researchData('p',{name:'x.csv',content:'x\n1\n',provenance:'fixture'},signal);check('CSV actual payload retained',()=>assert.equal(JSON.parse(last.options.body).content,'x\n1\n'));
await api.computeAdvice('m',signal);check('Advice is read-only',()=>{assert(last.url.endsWith('/compute-advice'));assert(!last.options.method||last.options.method==='GET');});
console.log(`Research helpers: ${n} passed; fetch doubles, no live API calls.`);
