import {useEffect,useState} from 'react';
import styles from './CameraControls.module.css';

/** The same camera vocabulary is used for numerical and editable illustration views. */
export default function CameraControls({engineRef,storageKey='scene',selection=false}){
  const [saved,setSaved]=useState([]),[coordinates,setCoordinates]=useState(null);
  useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem(`phaseforge.savedViews.${storageKey}`)||'[]'));}catch{setSaved([]);}},[storageKey]);
  const nav=value=>engineRef.current?.navigate?.(value);
  const save=()=>{const camera=engineRef.current?.cameraState?.();if(!camera)return;const next=[...saved.slice(-7),{name:`View ${saved.length+1}`,camera}];setSaved(next);try{localStorage.setItem(`phaseforge.savedViews.${storageKey}`,JSON.stringify(next));}catch{}};
  const apply=value=>{const current=engineRef.current;if(current?.setCamera)current.setCamera(value);else current?.command?.(value);};
  return <details className={styles.controls} onToggle={e=>{if(e.currentTarget.open)setCoordinates(engineRef.current?.cameraState?.()||null);}}><summary>Camera controls</summary><div className={styles.panel}><p>Drag to orbit · Shift/right drag to pan · scroll to zoom. Focus the view for arrow keys, Shift arrows and +/−.</p><div className={styles.buttons}><button type="button" aria-label="Zoom in" onClick={()=>nav({zoom:-.2})}>Zoom +</button><button type="button" aria-label="Zoom out" onClick={()=>nav({zoom:.2})}>Zoom −</button><button type="button" onClick={()=>nav({orbit:[.18,0]})}>Orbit ←</button><button type="button" onClick={()=>nav({orbit:[-.18,0]})}>Orbit →</button><button type="button" onClick={()=>nav({orbit:[0,-.15]})}>Tilt ↑</button><button type="button" onClick={()=>nav({orbit:[0,.15]})}>Tilt ↓</button><button type="button" onClick={()=>nav({pan:[-.1,0]})}>Pan ←</button><button type="button" onClick={()=>nav({pan:[.1,0]})}>Pan →</button><button type="button" onClick={()=>nav({pan:[0,.1]})}>Pan ↑</button><button type="button" onClick={()=>nav({pan:[0,-.1]})}>Pan ↓</button><button type="button" onClick={()=>nav({roll:-.15})}>Roll ↶</button><button type="button" onClick={()=>nav({roll:.15})}>Roll ↷</button><button type="button" onClick={()=>nav({home:true})}>Home / fit all</button>{selection&&<button type="button" onClick={()=>engineRef.current?.focusSelection?.()}>Fit selection</button>}</div><button type="button" onClick={save}>Save this camera</button>{saved.map((view,index)=><button type="button" className={styles.saved} key={index} onClick={()=>apply(view.camera)}>{view.name}</button>)}{coordinates&&<details className={styles.precise}><summary>Exact source coordinates</summary>{['position','target'].map(key=><label key={key}>{key}<input aria-label={`Camera ${key}`} defaultValue={coordinates[key]?.join(', ')} onBlur={e=>{const value=e.target.value.split(',').map(Number);if(value.length===3&&value.every(Number.isFinite))apply({[key]:value});}}/></label>)}<small>{coordinates.units}</small></details>}</div></details>;
}
