import {useState,useRef} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {localDraft,DEFAULT_BUILD} from '@/lib/experiment';
export default function EquationEditor({project,onImport,busy,onBack}){
 const [states,setStates]=useState([{name:'',initial:'',derivative:'',unit:''}]),[constants,setConstants]=useState([]),[title,setTitle]=useState(''),[start,setStart]=useState(0),[end,setEnd]=useState(10),[step,setStep]=useState(.01),[error,setError]=useState('');
 const update=(setter,index,key,value)=>setter(rows=>rows.map((r,i)=>i===index?{...r,[key]:value}:r));
 const submitting=useRef(false);
 const submit=async e=>{e.preventDefault();if(submitting.current||busy)return;submitting.current=true;setError('');try{const manifest=localDraft({project,title,states,constants,start,end,step,budget:DEFAULT_BUILD});await onImport({manifest,auto_run:false});onBack();}catch(e){setError(e.message);}finally{submitting.current=false;}};
 return <section className="equationEditor"><h2>Enter equations, no model required</h2><p>Define your own ordinary differential equations and starting values. The runtime validates them and saves a new setup. No paper review, AI call, or research-task completion is required.</p>{!project?<p>Create a project first.</p>:<form onSubmit={submit}><label>Experiment title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="equationTable"><table><thead><tr><th>State name</th><th>Initial value</th><th>Derivative expression</th><th>Unit</th><th/></tr></thead><tbody>{states.map((s,i)=><tr key={i}>{['name','initial','derivative','unit'].map(k=><td key={k}><input required={k!=='unit'} aria-label={`${k} for state ${i+1}`} value={s[k]} onChange={e=>update(setStates,i,k,e.target.value)}/></td>)}<td><button type="button" aria-label={`Remove state ${i+1}`} onClick={()=>setStates(r=>r.filter((_,n)=>n!==i))} disabled={states.length===1}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div><button type="button" className="button button--secondary" onClick={()=>setStates(r=>[...r,{name:'',initial:'',derivative:'',unit:''}])} disabled={states.length>=128}><Plus size={14}/>State</button><details><summary>Constants ({constants.length})</summary>{constants.map((c,i)=><div className="equationConstant" key={i}>{['name','value','unit'].map(k=><input key={k} aria-label={`${k} for constant ${i+1}`} placeholder={k} value={c[k]} onChange={e=>update(setConstants,i,k,e.target.value)}/>)}<button type="button" onClick={()=>setConstants(r=>r.filter((_,n)=>n!==i))}>Remove</button></div>)}<button type="button" className="button button--secondary" onClick={()=>setConstants(r=>[...r,{name:'',value:'',unit:''}])}>Add constant</button></details><div className="equationTimes">{[[start,setStart,'Start time'],[end,setEnd,'End time'],[step,setStep,'Step size']].map(([v,set,label])=><label key={label}>{label}<input type="number" step="any" required value={v} onChange={e=>set(Number(e.target.value))}/></label>)}</div><p>Expressions use state names, constants, t, + − * / ^ and functions such as sin, cos, sqrt, exp, abs, min and max. This editor uses RK4 / CPU and records each state. Add acceptance tests later in a revised setup; this initial run is not a validated claim.</p>{error&&<p className="expError" role="alert">{error}</p>}<div className="expActions"><button className="button button--primary" disabled={busy}>Save executable setup</button><button className="button button--secondary" type="button" onClick={onBack}>Back to experiment</button></div></form>}</section>;
}
