import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,FlaskConical,Play,Square,SlidersHorizontal,RefreshCw,Code2,ChevronDown} from 'lucide-react';
import GenericViewport from './GenericViewport';
import ModelPicker from './ModelPicker';
import {DEFAULT_BUILD,RUNNING,validateBudget} from '@/lib/experiment';
export default function ExperimentWorkspace({project,manifest,run,busy,providerReady,providers=[],build,onRun,onNext,onStop,onSetup,onEquations,onNew,onResults,onSession,onInspect,onCameraChange}){
  const [instruction,setInstruction]=useState(''),[options,setOptions]=useState({...DEFAULT_BUILD}),[error,setError]=useState(''),[expanded,setExpanded]=useState(true);
  const locked=useRef(false),owner=useRef(project?.id);owner.current=project?.id;
  useEffect(()=>{setInstruction('');setError('');setExpanded(!manifest);},[project?.id,!!manifest]);
  const executing=RUNNING.has(run?.status);
  async function act(action){if(locked.current||busy)return;locked.current=true;const id=project?.id;setError('');try{await action();}catch(e){if(owner.current===id)setError(e.message);}finally{locked.current=false;}}
  const submit=async go=>{validateBudget(options);const id=project?.id;const response=await build(instruction,options,go);if(owner.current===id&&response?.manifest)setExpanded(false);};
  if(!project)return <section className="experimentWorkspace"><div className="expEmpty"><FlaskConical size={35}/><span className="eyebrow">ONE WORKBENCH. EVERY SCALE.</span><h2>Follow your question further.</h2><p>Build worlds from equations. Explore molecules, motion, and the cosmos with an AI research team and your local compute.</p><button className="button button--primary" onClick={onNew}>Start researching <ArrowRight size={16}/></button></div><div className="expCanvas"><GenericViewport/></div></section>;
  return <section className="experimentWorkspace">
    <div className={`expCommand ${manifest&&!expanded?'expCommand--collapsed':''}`}><header><div><span className="eyebrow">{manifest?`EXPERIMENT · REVISION ${manifest.revision}`:'START EXPERIMENTING'}</span><h2>{manifest?.title||'Turn the question into a runnable experiment'}</h2></div><button className="button button--secondary" onClick={()=>setExpanded(v=>!v)} aria-expanded={expanded}>{expanded?'Hide request':'Change experiment'}<ChevronDown size={14}/></button></header>
      {expanded&&<form onSubmit={e=>{e.preventDefault();act(()=>submit(false));}}><label className="expPrompt">{manifest?'What should change or be tested next?':'What should this experiment test?'}<textarea value={instruction} maxLength={12000} onChange={e=>setInstruction(e.target.value)} placeholder={manifest?'Describe a change, parameter comparison, or behavior to investigate…':project.question} rows={3}/></label><label className="expAssumptions"><input type="checkbox" checked={options.assumptions_allowed} onChange={e=>setOptions(v=>({...v,assumptions_allowed:e.target.checked}))}/>Allow clearly declared exploratory assumptions when measured inputs are missing. Results remain uncalibrated.</label>
      <details className="expBudget"><summary>Run limits · {options.max_wall_seconds}s · {options.max_memory_mb} MiB · up to {options.max_candidates} candidates</summary><div>{[['max_wall_seconds','Wall-time limit (seconds)',1,86400],['max_memory_mb','Memory limit (MiB)',128,262144],['max_candidates','Total candidate evaluations',1,131072]].map(([key,label,min,max])=><label key={key}>{label}<input type="number" min={min} max={max} value={options[key]} onChange={e=>setOptions(v=>({...v,[key]:Number(e.target.value)}))}/></label>)}</div><small>One generated experiment, including its screening budget. Existing paid-model limits still apply. No automatic follow-on runs.</small></details>
      <div className="expActions"><ModelPicker providers={providers} disabled={busy}/><button className="button button--secondary" disabled={busy||!providerReady} type="submit">{manifest?'Build revised setup':'Build experiment'}</button><button className="button button--primary" type="button" disabled={busy||!providerReady} onClick={()=>act(()=>submit(true))}><Play size={14}/>{manifest?'Build & run revision':'Build & run'}</button><button className="expTextButton" type="button" onClick={onEquations} disabled={busy}><Code2 size={14}/>Enter equations</button></div><small>Build saves a setup. Build & run also starts one local experiment.</small>{!providerReady&&<p className="expNotice">Configure a provider to use AI, or enter equations to run locally. <Link href="/settings/">Open Settings</Link></p>}</form>}
      {error&&<p className="expError" role="alert">{error}</p>}
      <div className="expRunControls">{manifest&&<><button type="button" className="button button--primary" disabled={busy||executing} onClick={()=>act(onRun)}><Play size={15}/>Run saved setup</button><span className="expCaps">This setup: ≤{manifest.compute.max_wall_seconds}s · {manifest.compute.max_memory_mb} MiB</span><button className="button button--secondary" onClick={onSetup}><SlidersHorizontal size={14}/>Setup</button></>}{(busy||executing)&&<button type="button" className="button button--danger" onClick={onStop}><Square size={14}/>Stop</button>}{run?.status==='completed'&&<button className="button button--secondary" onClick={onResults}>View results <ArrowRight size={14}/></button>}</div>
      {run&&['completed','failed','cancelled'].includes(run.status)&&<details className="expNext"><summary>Run another pass without a model call</summary><p>Starts again from the source experiment's initial conditions and seed. Keeps its existing compute caps; does not continue from the last frame or prove a result independently.</p><div className="expActions"><button className="button button--secondary" disabled={busy} onClick={()=>act(()=>onNext('replay'))}><RefreshCw size={14}/>Replay</button><button className="button button--secondary" disabled={busy} onClick={()=>act(()=>onNext('finer_steps'))}>Half-size steps & run</button><button className="button button--secondary" disabled={busy} onClick={()=>act(()=>onNext('longer_horizon'))}>Double horizon & run</button></div></details>}
    </div>
    {run&&manifest&&run.manifest_id!==manifest.id&&<div className="expVersionNote">The display below belongs to {run.name}. Revision {manifest.revision} above is a different setup; its Run button will not relabel this result.</div>}
    <div className="expCanvas"><GenericViewport run={run} manifest={manifest} onInspect={onInspect} onCameraChange={onCameraChange}/></div>
    <div className="experimentSessionInvite"><span>Take this question further with a timed research team.</span><button type="button" onClick={onSession}>Research session <ArrowRight size={13}/></button></div>
  </section>;
}
