import {Box,Camera,ChevronDown,Download,Eye,Focus,Layers3,Maximize,MousePointer2,Pause,Play,RotateCcw,Settings2,SkipBack,SkipForward,X} from 'lucide-react';
import {useEffect,useMemo,useRef,useState} from 'react';
import {exportJson,normalizedFrames,sampleFrames,number} from '@/lib/lab';
import {exampleScene,normalizeScene,sceneSourceFromEvidence,SCENE_PRESETS,PALETTE} from '@/lib/scene.mjs';
import styles from './ScientificScene.module.css';

const EMPTY=[];
const VIEW_LABELS={perspective:'Perspective',xy:'Front · XY',xz:'Top · XZ',yz:'Side · YZ'};

/** Human/agent scene interface. Callbacks contain serializable world coordinates. */
export default function GenericViewport({run,manifest,scene:providedScene,onInspect,onCameraChange,cameraCommand,compact=false}) {
  const hostRef=useRef(null),panelRef=useRef(null),engineRef=useRef(null),options=useRef({});
  const [example,setExample]=useState(null),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[speed,setSpeed]=useState(1);
  const [selected,setSelected]=useState(''),[picked,setPicked]=useState(null),[view,setView]=useState('perspective'),[showTree,setShowTree]=useState(false),[showOptions,setShowOptions]=useState(false);
  const [trails,setTrails]=useState(true),[vectors,setVectors]=useState(false),[interpolate,setInterpolate]=useState(true),[grid,setGrid]=useState(false),[cut,setCut]=useState(1);
  const [quality,setQuality]=useState('balanced'),[stats,setStats]=useState(null),[error,setError]=useState(''),[resetKey,setResetKey]=useState(0);
  const frames=useMemo(()=>normalizedFrames(run?.result?.visualization?.frames||EMPTY),[run?.result?.visualization?.frames]);
  // Parent camera/inspection state can recreate a lightweight manifest wrapper.
  // Depend on its actual immutable scene payload, or reporting a mount camera
  // would repeatedly rebuild the renderer and report another mount camera.
  const sceneSource=providedScene||sceneSourceFromEvidence(run,manifest);
  const evidenceScene=useMemo(()=>normalizeScene(sceneSource),[sceneSource]);
  const sceneSpec=useMemo(()=>evidenceScene||(example&&!frames.length?exampleScene(example):null),[evidenceScene,example,frames.length]);
  const meta=useMemo(()=>{const ids=new Set();for(const frame of frames)for(const entity of frame.entities)ids.add(entity.id);return {ids:[...ids],start:frames[0]?.time||0,end:frames.at(-1)?.time||0};},[frames]);
  const hasEvidence=frames.length>0,ready=!!(sceneSpec?.nodes.length||meta.ids.length),nodes=sceneSpec?.nodes||EMPTY;
  const listed=useMemo(()=>nodes.length?nodes.map(n=>({id:n.id,label:n.label,color:n.color,type:n.type,entity_id:n.entity_id})):meta.ids.slice(0,128).map((id,i)=>({id,label:id,color:PALETTE[i%PALETTE.length],type:'trajectory',entity_id:id})),[nodes,meta.ids]);
  const current=useMemo(()=>sampleFrames(frames,time),[frames,time]);
  const selectedNode=nodes.find(n=>n.id===selected),selectedEntity=current.left?.entities.find(e=>e.id===(selectedNode?.entity_id||selected));
  options.current={playing,speed,trails,vectors,interpolate,grid,selected,cut,onInspect,onCameraChange};
  useEffect(()=>{setPlaying(false);setTime(meta.start);setSelected('');setPicked(null);setError('');},[run?.id,sceneSpec,meta.start]);
  useEffect(()=>{if(cameraCommand){engineRef.current?.command(cameraCommand);if(cameraCommand.view)setView(cameraCommand.view);}},[cameraCommand]);
  useEffect(()=>{
    let cancelled=false,engine=null;
    async function mount(){
      if(!hostRef.current||!ready)return;
      try{
        const {createSceneViewer}=await import('@/lib/scene-viewer.mjs');if(cancelled)return;
        engine=await createSceneViewer(hostRef.current,{sceneSpec,frames,meta,quality,sampleFrames,view,cameraCommand,pointSize:run?.result?.visualization?.point_size,runId:run?.id,options:()=>options.current,onTime:setTime,onStop:()=>setPlaying(false),onStats:setStats,onSelect:(id,detail)=>{setSelected(id);setPicked(detail||null);},onError:setError,isCancelled:()=>cancelled});
        if(cancelled)engine?.dispose();else engineRef.current=engine;
      }catch(e){if(!cancelled)setError(e.message||'The scientific scene could not initialize.');}
    }
    mount();return()=>{cancelled=true;engine?.dispose();if(engineRef.current===engine)engineRef.current=null;};
    // Playback and camera state live outside the geometry lifecycle.
  },[ready,frames,meta,sceneSpec,quality,resetKey,run?.id]);
  useEffect(()=>{
    const node=selectedNode?{id:selectedNode.id,type:selectedNode.type,label:selectedNode.label,description:selectedNode.description,entity_id:selectedNode.entity_id,position:selectedNode.position,scale:selectedNode.scale,atom_count:selectedNode.parameters.atoms?.length||0,vertex_count:selectedNode.parameters.vertices?.length||0}:null;
    options.current.onInspect?.(selected?{node,entity:selectedEntity||null,picked,time:current.left?.time??null,camera:engineRef.current?.cameraState(),provenance:sceneSpec?.provenance||{kind:'computed',description:'Recorded numerical state; display glyph geometry.'}}:null);
  },[selected,picked,current.left,sceneSpec]);
  const seek=t=>{setPlaying(false);setTime(t);engineRef.current?.seek(t);};
  const changeView=value=>{setView(value);engineRef.current?.view(value);};
  const exportScene=()=>exportJson(`phaseforge-${run?.id||'scene'}.json`,{scene:sceneSpec,camera:engineRef.current?.cameraState(),run_id:run?.id||null,manifest_id:run?.manifest_id||manifest?.id||null,retained_frame:current.left,display:{interpolated:interpolate,time,quality}});
  if(!ready)return <section className={styles.empty}><div className={styles.emptySymbol}><Layers3 size={30}/></div><span className={styles.eyebrow}>SCIENTIFIC SCENE STUDIO</span><h3>{['running','queued'].includes(run?.status)?'Your experiment is taking shape':'Build a world around your question'}</h3><p>{run?.phase||'Agents can compose structures, surfaces, fields and trajectories. Explore a scene study, or build an experiment above.'}</p><div className={styles.examples}>{SCENE_PRESETS.map(p=><button type="button" key={p.id} onClick={()=>setExample(p.id)}><Box size={18}/><strong>{p.name}</strong><span>{p.detail}</span></button>)}</div><small>Scene studies are illustrative geometry. Simulation evidence appears when a run retains numerical frames.</small></section>;
  return <section ref={panelRef} className={`${styles.viewport} ${compact?styles.compact:''}`} aria-label="Interactive scientific scene">
    <div ref={hostRef} className={styles.canvas}/>
    <header className={styles.header}><div><span className={styles.eyebrow}>{hasEvidence?'EXPERIMENT REPLAY':'SCENE STUDY'}</span><strong>{sceneSpec?.title||manifest?.title||run?.name||'Measured trajectories'}</strong></div><div className={styles.headerActions}><span className={styles.gpuDot}/><span>{stats?(stats.idle?'GPU ready':`${stats.fps} fps`):'GPU viewport'}</span><button type="button" onClick={()=>setShowTree(v=>!v)} title="Toggle scene objects" aria-label="Toggle scene objects"><Layers3 size={17}/></button><button type="button" onClick={()=>setShowOptions(v=>!v)} title="Display settings" aria-label="Display settings"><Settings2 size={17}/></button><button type="button" onClick={()=>document.fullscreenElement?document.exitFullscreen?.():panelRef.current?.requestFullscreen?.()} title="Fullscreen" aria-label="Fullscreen"><Maximize size={17}/></button></div></header>
    <div className={styles.provenance}><span className={hasEvidence?styles.evidenceDot:styles.conceptDot}/>{hasEvidence?`${frames.length.toLocaleString()} recorded frames`:'Conceptual preview'}{sceneSpec&&<span> · {sceneSpec.provenance.kind} geometry</span>}</div>
    {showTree&&<aside className={styles.tree}><div className={styles.treeTitle}>SCENE OBJECTS <span>{listed.length}</span></div>{listed.slice(0,32).map(node=><button type="button" key={node.id} onClick={()=>{setSelected(selected===node.id?'':node.id);setPicked(null);}} className={selected===node.id?styles.selected:''}><i style={{background:node.color}}/><span><strong>{node.label}</strong><small>{node.type.replaceAll('_',' ')}{node.entity_id?' · state linked':''}</small></span><Eye size={12}/></button>)}{listed.length>32&&<small className={styles.treeExtra}>Showing 32 of {listed.length} objects. Pick others directly in the scene.</small>}{example&&!evidenceScene&&<button type="button" className={styles.backExamples} onClick={()=>setExample(null)}>Back to scene studies</button>}</aside>}
    <div className={styles.tools}><select aria-label="Camera view" value={view} onChange={e=>changeView(e.target.value)}>{Object.entries(VIEW_LABELS).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select><button type="button" onClick={()=>engineRef.current?.view(view)} title="Fit entire scene" aria-label="Fit entire scene"><Focus size={17}/></button><button type="button" onClick={()=>engineRef.current?.capture()} title="Save image" aria-label="Save viewport image"><Camera size={17}/></button><button type="button" onClick={exportScene} title="Export scene and camera" aria-label="Export scene and camera"><Download size={17}/></button></div>
    {showOptions&&<div className={styles.settings}><strong>Display settings</strong><label>Geometry detail<select value={quality} onChange={e=>setQuality(e.target.value)}><option value="low">Economy</option><option value="balanced">Balanced</option><option value="high">High detail</option></select></label><label><span>Reference grid</span><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/></label>{hasEvidence&&<><label><span>Trajectory trails</span><input type="checkbox" checked={trails} onChange={e=>setTrails(e.target.checked)}/></label><label><span>Velocity vectors</span><input type="checkbox" checked={vectors} onChange={e=>setVectors(e.target.checked)}/></label><label><span>Interpolate positions</span><input type="checkbox" checked={interpolate} onChange={e=>setInterpolate(e.target.checked)}/></label></>}<label>Section cut<input aria-label="Section cut" type="range" min="0" max="1" step=".01" value={cut} onChange={e=>setCut(Number(e.target.value))}/></label><small>{stats?`${stats.triangles.toLocaleString()} triangles · ${stats.drawCalls} draw calls`:'Preparing scene'}<br/>Display detail adapts pixel resolution under load.</small></div>}
    {selected&&<aside className={styles.inspector}><div><span className={styles.eyebrow}>INSPECT OBJECT</span><button type="button" onClick={()=>setSelected('')} aria-label="Close object inspector"><X size={14}/></button></div><strong>{selectedNode?.label||selected}</strong><span className={styles.objectType}>{selectedNode?.type.replaceAll('_',' ')||'numerical entity'} · {sceneSpec?.units||'model units'}</span>{selectedNode?.description&&<p>{selectedNode.description}</p>}{picked?.atom&&<label>Picked atom · {picked.atom.element} {picked.atom.id}<code>{picked.atom.position.map(number).join(' · ')}</code></label>}{selectedEntity?<><label>Recorded position<code>{selectedEntity.position.map(number).join(' · ')}</code></label>{selectedEntity.velocity&&<label>Recorded velocity<code>{selectedEntity.velocity.map(number).join(' · ')}</code></label>}{Number.isFinite(selectedEntity.scalar)&&<label>Recorded scalar<code>{number(selectedEntity.scalar)}</code></label>}<small>Frame t = {number(current.left?.time)}. Playback interpolation affects the display only.</small></>:<small>{selectedNode?.entity_id?'No retained state for this object at the current time.':'Authored geometry; no numerical state binding.'}</small>}<button type="button" className={styles.focusButton} onClick={()=>engineRef.current?.view(view,selected)}><Focus size={14}/>Focus object</button></aside>}
    <footer className={styles.footer}>{hasEvidence&&<div className={styles.playback}><button type="button" aria-label="Restart playback" onClick={()=>seek(meta.start)}><RotateCcw size={15}/></button><button type="button" aria-label="Previous recorded frame" onClick={()=>seek(frames[Math.max(0,current.index-1)].time)}><SkipBack size={15}/></button><button type="button" className={styles.play} aria-label={playing?'Pause playback':'Play simulation'} disabled={meta.end<=meta.start} onClick={()=>{if(time>=meta.end)engineRef.current?.seek(meta.start);setPlaying(v=>!v);}}>{playing?<Pause size={16}/>:<Play size={16}/>}</button><button type="button" aria-label="Next recorded frame" onClick={()=>seek(frames[Math.min(frames.length-1,current.index+1)].time)}><SkipForward size={15}/></button><input type="range" aria-label="Simulation time" min={meta.start} max={meta.end||1} step={(meta.end-meta.start)/3000||.001} value={time} onChange={e=>seek(Number(e.target.value))}/><code>{number(time)} <span>/ {number(meta.end)}</span></code><select aria-label="Playback speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[.25,.5,1,2,4].map(v=><option value={v} key={v}>{v}×</option>)}</select></div>}<div className={styles.bottomLine}><span><MousePointer2 size={12}/> Drag orbit · right-drag pan · scroll zoom · click inspect</span><details><summary>Scene provenance <ChevronDown size={12}/></summary><div>{sceneSpec?.provenance.description||run?.result?.numerical?.visual_entity_mapping||'Recorded numerical coordinates. Sphere size is a display representation, not contact or material physics.'}{hasEvidence&&<p>{meta.ids.length} retained entities. Numerical data are unchanged by camera, geometry detail or smooth playback. Velocity arrows use a display scale.</p>}{sceneSpec?.warnings.map(w=><p key={w}>{w}</p>)}{(run?.result?.visualization?.frames?.length||0)>frames.length&&<p>Display sampled to {frames.length} frames to bound memory; the saved run keeps all evidence.</p>}</div></details></div></footer>
    {error&&<div role="alert" className={styles.error}><strong>{error}</strong><button type="button" onClick={()=>{setQuality('low');setError('');setResetKey(v=>v+1);}}>Recover with lower detail</button></div>}
  </section>;
}

export function ScenePreview({preset='molecular',className='',onInspect,onCameraChange}) {
  const scene=useMemo(()=>exampleScene(preset),[preset]);
  return <div className={className}><GenericViewport scene={scene} compact onInspect={onInspect} onCameraChange={onCameraChange}/></div>;
}
