'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Download,Focus,Minus,Plus} from 'lucide-react';
import {api} from '@/lib/api';
import {laboratoryUrl} from '@/lib/laboratory-http.mjs';
import {artifactPath,fitPlot,zoomPlot} from '@/lib/laboratory-plot.mjs';
import {outputArtifacts,previewableArtifact,registeredArtifacts,verifyArtifactImage} from '@/lib/laboratory-artifacts.mjs';
import styles from './LaboratoryPlotViewer.module.css';

export default function LaboratoryArtifactViewer({job}){
  const viewport=useRef(null),drag=useRef(null),size=useRef({width:1,height:1}),imageSize=useRef({width:1,height:1});
  const [full,setFull]=useState(job),[selected,setSelected]=useState(''),[image,setImage]=useState(null),[imageDimensions,setImageDimensions]=useState({width:1,height:1}),[error,setError]=useState(''),[view,setView]=useState({scale:1,x:0,y:0}),[retry,setRetry]=useState(0);
  const outputs=outputArtifacts(full),all=registeredArtifacts(full),images=outputs.filter(previewableArtifact),artifact=images.find(item=>item.path===selected)||images[0];
  const description=typeof full.result?.reported_result?.summary==='string'?full.result.reported_result.summary:'Files retained by the completed local job.',scope=typeof full.result?.reported_result?.scope==='string'?full.result.reported_result.scope:'These are recorded job outputs. Successful execution alone does not establish scientific validity.';
  const reset=useCallback(()=>setView(fitPlot(size.current.width,size.current.height,imageSize.current.width,imageSize.current.height)),[]);
  const zoom=factor=>setView(value=>zoomPlot(value,factor,{x:size.current.width/2,y:size.current.height/2}));
  useEffect(()=>{const controller=new AbortController();api.labJob(job.id,controller.signal).then(value=>{if(!controller.signal.aborted){setFull(value);setError('');}}).catch(error=>{if(error.name!=='AbortError')setError(error.message);});return()=>controller.abort();},[job.id,job.updated_at,retry]);
  useEffect(()=>{
    setImage(null);if(!artifact)return;const controller=new AbortController();let objectUrl;
    async function load(){try{if(artifact.bytes>32*1024*1024)throw Error('This image exceeds the 32 MiB preview limit. Download the original file below.');const response=await fetch(laboratoryUrl(artifactPath(job.id,artifact.path)),{signal:controller.signal});if(!response.ok)throw Error(`Saved image unavailable (${response.status}).`);const bytes=await response.arrayBuffer(),mime=await verifyArtifactImage(bytes,artifact);if(controller.signal.aborted)return;objectUrl=URL.createObjectURL(new Blob([bytes],{type:mime}));setImage(objectUrl);setError('');}catch(error){if(error.name!=='AbortError')setError(error.message);}}
    load();return()=>{controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};
  },[job.id,artifact?.path,artifact?.sha256,retry]);
  useEffect(()=>{const host=viewport.current,resize=new ResizeObserver(()=>{size.current={width:host.clientWidth,height:host.clientHeight};reset();});resize.observe(host);const wheel=event=>{event.preventDefault();const bounds=host.getBoundingClientRect();setView(value=>zoomPlot(value,Math.exp(-Math.max(-100,Math.min(100,event.deltaY))*.004),{x:event.clientX-bounds.left,y:event.clientY-bounds.top}));};host.addEventListener('wheel',wheel,{passive:false});return()=>{resize.disconnect();host.removeEventListener('wheel',wheel);};},[reset]);
  const link=item=><a key={item.path} href={laboratoryUrl(artifactPath(job.id,item.path))} download={`phaseforge-${job.id}-${item.path.split('/').at(-1)}`}><Download size={14}/>{item.path.split('/').at(-1)}</a>;
  return <section className={styles.viewer} aria-label="Saved output files" style={{gridTemplateRows:images.length>1?'auto auto minmax(320px,1fr) auto':undefined,'--image-width':`${imageDimensions.width}px`,'--image-height':`${imageDimensions.height}px`}}>
    <header className={styles.header}><div><span>SAVED OUTPUT</span><h3>{job.title||'Generated files'}</h3><p>{description}</p></div><div className={styles.tools}><button type="button" aria-label="Zoom output image out" disabled={!image} onClick={()=>zoom(.8)}><Minus size={16}/></button><output aria-label="Output magnification">{Math.round(view.scale*100)}%</output><button type="button" aria-label="Zoom output image in" disabled={!image} onClick={()=>zoom(1.25)}><Plus size={16}/></button><button type="button" disabled={!image} onClick={reset}><Focus size={15}/>Fit / reset</button></div></header>
    {images.length>1&&<label>Preview image <select aria-label="Preview saved output image" value={artifact?.path||''} onChange={event=>setSelected(event.target.value)}>{images.map(item=><option key={item.path} value={item.path}>{item.path.split('/').at(-1)}</option>)}</select></label>}
    <div ref={viewport} className={styles.viewport} tabIndex={0} aria-label="Saved image. Drag to pan, scroll to zoom, Home to fit." onDoubleClick={reset} onPointerDown={event=>{if(event.button!==0)return;event.currentTarget.focus();event.currentTarget.setPointerCapture(event.pointerId);drag.current={id:event.pointerId,x:event.clientX,y:event.clientY};}} onPointerMove={event=>{if(drag.current?.id!==event.pointerId)return;const {x,y}=drag.current;drag.current={id:event.pointerId,x:event.clientX,y:event.clientY};setView(value=>({...value,x:value.x+event.clientX-x,y:value.y+event.clientY-y}));}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onKeyDown={event=>{if(event.key==='Home'){event.preventDefault();reset();}else if(['+','=','-'].includes(event.key)){event.preventDefault();zoom(event.key==='-'?.8:1.25);}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();setView(value=>({...value,x:value.x+(event.key==='ArrowLeft'?40:event.key==='ArrowRight'?-40:0),y:value.y+(event.key==='ArrowUp'?40:event.key==='ArrowDown'?-40:0)}));}}}>
      {image?<img draggable={false} src={image} alt={artifact.path.split('/').at(-1)} onLoad={event=>{imageSize.current={width:event.currentTarget.naturalWidth,height:event.currentTarget.naturalHeight};setImageDimensions(imageSize.current);reset();}} style={{transform:`translate(${view.x}px,${view.y}px) scale(${view.scale})`}}/>:<div className={styles.pending} role="status">{artifact?'Loading and verifying the saved image…':full.state==='completed'?'This output contains downloadable files.':'Saved files appear when the job completes.'}</div>}
    </div>
    <footer className={styles.footer}><p>{scope}</p><div className={styles.downloads}>{outputs.map(link)}</div><details><summary>All retained files & provenance</summary><div className={styles.downloads}>{all.map(link)}</div>{artifact&&<p>Displayed image SHA-256 <code>{artifact.sha256}</code></p>}</details>{error&&<p className={styles.error} role="status">{error} <button type="button" onClick={()=>setRetry(value=>value+1)}>Retry</button></p>}</footer>
  </section>;
}
