'use client';
import {useEffect,useRef,useState} from 'react';
import {Box,Download,Image,Redo2,Undo2} from 'lucide-react';
import {api} from '@/lib/api';
import {laboratoryUrl} from '@/lib/laboratory-http.mjs';
import ScientificModelViewer from './ScientificModelViewer';
import useLaboratoryPresentation from './useLaboratoryPresentation';
import styles from './LaboratoryIllustrationViewer.module.css';

const DEFAULTS={color:null,background:'#111d2e',contrast:1,exposure:1.03,selectedIds:[],hiddenIds:[]};
export default function LaboratoryIllustrationViewer({job}){
  const [full,setFull]=useState(job),[mode,setMode]=useState('still'),[error,setError]=useState(''),engine=useRef(null);
  const presentation=useLaboratoryPresentation(job.id,DEFAULTS),settings=presentation.settings;
  useEffect(()=>{const controller=new AbortController();api.labJob(job.id,controller.signal).then(value=>{if(!controller.signal.aborted){setFull(value);setError('');}}).catch(error=>{if(error.name!=='AbortError')setError(error.message);});return()=>controller.abort();},[job.id,job.updated_at,job.state]);
  const request=full.input?.resolved?.request||{},renderer=full.result?.renderer||{},scene=request.scene||{},nodes=scene.nodes||[],state=job.state||full.state;
  const artifacts=full.result?.artifacts||[],has=path=>state==='completed'&&artifacts.some(item=>item.path===path),url=path=>laboratoryUrl(`/api/laboratory/jobs/${job.id}/artifacts/${path}`);
  const initialCamera=request.camera||scene.camera,display={...settings,camera:settings.camera||initialCamera};
  const selected=settings.selectedIds?.[0]||'';
  return <section className={styles.viewer} aria-label="Scientific illustration workspace">
    <header className={styles.header}><div><span>SCIENTIFIC ILLUSTRATION</span><h3>{job.title||'Blender illustration'}</h3><p>Authored geometry · {renderer.width||request.width||'—'} × {renderer.height||request.height||'—'} · {renderer.engine||'Blender Cycles'}</p></div><div className={styles.tabs}><button type="button" aria-pressed={mode==='still'} onClick={()=>setMode('still')}><Image size={15}/>Rendered still</button><button type="button" aria-pressed={mode==='model'} disabled={!has('scene.glb')} onClick={()=>setMode('model')}><Box size={15}/>Explore 3D</button></div></header>
    {mode==='still'?<div className={styles.still}>{has('render.png')?<img src={url('render.png')} alt={scene.title||job.title||'Scientific illustration rendered from the saved authored Blender scene'}/>:<div role="status"><strong>Illustration · {state}</strong><p>{job.progress?.message||full.progress?.message||'The saved render will appear when Blender finishes.'}</p></div>}</div>:<ScientificModelViewer url={url('scene.glb')} title={scene.title||job.title} style={request.style||'studio'} coordinateMapping={renderer.coordinate_mapping} sourceUnits={scene.units||'authored scene units'} displayPresentation={display} onCameraChange={camera=>presentation.update({camera})} onInspect={selection=>{if(selection.entity_id)presentation.update({selectedIds:[selection.entity_id]});}} onEngineReady={value=>{engine.current=value;}} provenance={{description:renderer.export_note||'Saved illustration geometry. This scene is an illustration, not measured experimental evidence.'}}/>}
    {mode==='model'&&<div className={styles.presentation}><label>Geometry color<input type="color" aria-label="Illustration geometry color" disabled={!presentation.ready} value={settings.color||'#ffffff'} onChange={e=>presentation.update({color:e.target.value})}/></label><button type="button" disabled={!presentation.ready||!settings.color} onClick={()=>presentation.update({color:null})}>Original colors</button><label>Background<input type="color" disabled={!presentation.ready} value={settings.background} onChange={e=>presentation.update({background:e.target.value})}/></label><label>Contrast<input type="range" aria-label="Illustration contrast" min=".5" max="2" step=".05" disabled={!presentation.ready} value={settings.contrast} onChange={e=>presentation.update({contrast:Number(e.target.value)})}/></label><label>Exposure<input type="range" aria-label="Illustration exposure" min=".15" max="3" step=".05" disabled={!presentation.ready} value={settings.exposure} onChange={e=>presentation.update({exposure:Number(e.target.value)})}/></label>{nodes.length>0&&<label>Highlight<select aria-label="Highlight illustration component" disabled={!presentation.ready} value={selected} onChange={e=>presentation.update({selectedIds:e.target.value?[e.target.value]:[]})}><option value="">None</option>{nodes.map(node=><option key={node.id} value={node.id}>{node.name||node.label||node.id}</option>)}</select></label>}<button type="button" disabled={!selected} onClick={()=>engine.current?.focusSelection?.()}>Fit highlighted</button><button type="button" aria-label="Undo illustration presentation" disabled={!presentation.canUndo} onClick={presentation.undo}><Undo2 size={15}/></button><button type="button" aria-label="Redo illustration presentation" disabled={!presentation.canRedo} onClick={presentation.redo}><Redo2 size={15}/></button><p>These edits reuse saved geometry. Ask chat to render this illustration with your changes to create a new Blender still.</p></div>}
    <footer className={styles.footer}><p>Scientific illustration is a separate output. It does not establish simulated motion, binding, efficacy, or experimental results.</p><div>{[['render.png','Save PNG'],['scene.glb','Save 3D model'],['scene.blend','Save editable Blender scene']].filter(([path])=>has(path)).map(([path,label])=><a key={path} href={url(path)} download={`phaseforge-${job.id}-${path}`}><Download size={14}/>{label}</a>)}</div>{presentation.warning&&<small role="status">{presentation.warning}</small>}{error&&<small role="alert">{error}</small>}</footer>
  </section>;
}
