'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera,Eye,Focus,Maximize,Pause,Play,Redo2,RotateCcw,Settings2,Undo2,X} from 'lucide-react';
import {laboratoryJson,laboratoryUrl} from '@/lib/laboratory-http.mjs';
import {FieldStore,normalizeFieldIndex,recordedFieldNumber,fieldColor} from '@/lib/laboratory-field.mjs';
import {TIMELINE_SLIDER_MAX,timelineSliderTime,timelineSliderValue} from '@/lib/timeline-slider.mjs';
import CameraControls from './CameraControls';
import LaboratoryVideoExport from './LaboratoryVideoExport';
import useLaboratoryPresentation from './useLaboratoryPresentation';
import styles from './LaboratoryViewer.module.css';

const DEFAULTS={colorLow:'#142650',colorHigh:'#ffbe3c',background:'#080f20',contrast:1,selectedCell:null,playbackDurationSeconds:30,speed:1};
const number=value=>Number(value).toLocaleString(undefined,{maximumSignificantDigits:6});
export default function LaboratoryFieldViewer({job,onCapture}){
  const host=useRef(null),panel=useRef(null),engine=useRef(null),store=useRef(null),options=useRef(DEFAULTS),loadVersion=useRef(0),onSelectRef=useRef(null),mounted=useRef(false),activeRef=useRef(false);
  const [index,setIndex]=useState(null),[frame,setFrame]=useState(null),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[error,setError]=useState(''),[reconnecting,setReconnecting]=useState(false),[buffering,setBuffering]=useState(false),[capturing,setCapturing]=useState(false);
  const presentation=useLaboratoryPresentation(job.id,DEFAULTS),settings=presentation.settings;options.current=settings;onSelectRef.current=cell=>presentation.update({selectedCell:{x:cell.x,y:cell.y}});
  const active=['queued','preparing','provisioning','waiting','running','validating'].includes(job.state),path=`/api/laboratory/jobs/${job.id}/artifacts`;activeRef.current=active;
  useEffect(()=>{mounted.current=true;const controller=new AbortController();let busy=false,current=null,source=null,terminalRefreshed=false;
    setIndex(null);setFrame(null);setError('');setPlaying(false);
    async function refresh(){if(busy||controller.signal.aborted||(terminalRefreshed&&!activeRef.current))return;busy=true;try{const raw=await laboratoryJson(`${path}/fields/index.json`,{signal:controller.signal}),next=normalizeFieldIndex(raw);if(controller.signal.aborted)return;
      if(!source){source=new FieldStore({index:raw,loadBytes:async relative=>{const response=await fetch(laboratoryUrl(`${path}/${relative}`),{signal:controller.signal});if(!response.ok)throw Error(`Recorded field unavailable (${response.status})`);return response.arrayBuffer();}});store.current=source;}
      if(!current){
        const {createFieldViewer}=await import('@/lib/field-viewer.mjs');if(controller.signal.aborted)return;current=await createFieldViewer(host.current,{index:next,options:()=>options.current,signal:controller.signal,onCameraChange:camera=>presentation.update({camera}),onSelect:cell=>onSelectRef.current?.(cell)});if(controller.signal.aborted){current?.dispose();return;}engine.current=current;setTime(next.start);
      }source.updateIndex(raw);setIndex(next);setReconnecting(false);setError('');terminalRefreshed=!activeRef.current;
    }catch(error){if(error.name==='AbortError')return;if(error.status===404&&activeRef.current)return;if(source)setReconnecting(true);else setError(error.message);}finally{busy=false;}}
    refresh();const interval=setInterval(refresh,2000);return()=>{mounted.current=false;clearInterval(interval);controller.abort();current?.dispose();source?.close();if(engine.current===current)engine.current=null;if(store.current===source)store.current=null;};
  },[job.id,path]);
  useEffect(()=>{if(!index||!store.current)return;const version=++loadVersion.current;setBuffering(true);store.current.frame(recordedFieldNumber(index,time),{latestOnly:true}).then(value=>{if(mounted.current&&version===loadVersion.current){engine.current?.setFrame(value);setFrame(value);setBuffering(false);setError('');}}).catch(error=>{if(mounted.current&&version===loadVersion.current&&error.name!=='AbortError'){setError(error.message);setBuffering(false);}});},[index,time]);
  useEffect(()=>{if(settings.camera)engine.current?.setCamera(settings.camera,{silent:true});},[settings.camera]);
  useEffect(()=>{if(!playing||!index)return;let raf=0,last=null;const tick=now=>{if(last===null)last=now;if(now-last>32){const elapsed=Math.min(.25,(now-last)/1000);last=now;setTime(previous=>{const next=Math.min(index.end,previous+elapsed*(index.end-index.start)/settings.playbackDurationSeconds*settings.speed);if(next>=index.end)setPlaying(false);return next;});}raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[playing,index?.start,index?.end,settings.playbackDurationSeconds,settings.speed]);
  const seek=value=>{setPlaying(false);setTime(value);},capture=()=>{const value=engine.current?.capture();return value?{...value,sourceJobId:job.id}:null;};
  const save=()=>{const value=capture();if(value){const link=document.createElement('a');link.download=`phaseforge-field-${job.id}-t${value.time}.png`;link.href=value.dataUrl;link.click();}};
  const observe=async()=>{setCapturing(true);try{const value=capture();if(value)await onCapture?.(value);}catch(error){setError(error.message);}finally{setCapturing(false);}};
  const selected=settings.selectedCell,cell=selected&&index&&selected.x>=0&&selected.x<index.nx&&selected.y>=0&&selected.y<index.ny?{...selected,xValue:index.x_um[selected.x],yValue:index.y_um[selected.y],value:frame?.values[selected.y]?.[selected.x]}:null;
  const gradient=index?`linear-gradient(to right,${Array.from({length:9},(_,i)=>`rgb(${fieldColor(index.color_scale.min+(index.color_scale.max-index.color_scale.min)*i/8,index.color_scale,settings).join(',')})`).join(',')})`:'';
  return <section ref={panel} className={`${styles.viewer} ${styles.fieldViewer}`} aria-label="Recorded scalar field laboratory viewer"><div ref={host} className={styles.canvas}/><header className={styles.header}><div><span className={styles.eyebrow}>COMPUTED SCALAR FIELD</span><strong>{job.title||'Diffusion laboratory'}</strong><small>{index?`${index.nx} × ${index.ny} cells · ${index.frame_count} recorded states · ${index.boundary} boundaries`:'Waiting for committed numerical fields'}</small></div><div className={styles.actions}><button type="button" aria-label="Field presentation settings" onClick={()=>setSettingsOpen(v=>!v)}><Settings2 size={17}/></button><button type="button" aria-label="Undo field presentation" disabled={!presentation.canUndo} onClick={presentation.undo}><Undo2 size={17}/></button><button type="button" aria-label="Redo field presentation" disabled={!presentation.canRedo} onClick={presentation.redo}><Redo2 size={17}/></button><button type="button" aria-label="Save field image" disabled={!frame} onClick={save}><Camera size={17}/></button><button type="button" aria-label="Fullscreen field" onClick={()=>document.fullscreenElement?document.exitFullscreen?.():panel.current?.requestFullscreen?.()}><Maximize size={17}/></button></div></header>
    <div className={styles.provenance}><i/>Exact recorded cell values · fixed numerical color scale{buffering?' · loading state':''}</div>{index&&<div className={styles.cameraTools}><button type="button" onClick={()=>engine.current?.fit('front')}><Focus size={14}/>Fit field</button><button type="button" onClick={()=>engine.current?.fit('perspective')}>Tilted view</button><CameraControls engineRef={engine} storageKey={`field-${job.id}`} selection={!!cell}/></div>}
    {settingsOpen&&<aside className={styles.settings}><div className={styles.panelHeading}><strong>Field presentation</strong><button type="button" aria-label="Close field settings" onClick={()=>setSettingsOpen(false)}><X size={14}/></button></div><p>Colors change the display and its legend. Numerical values and the fixed range stay unchanged.</p>{[['colorLow','Low value'],['colorHigh','High value'],['background','Background']].map(([key,label])=><label key={key}>{label}<input type="color" disabled={!presentation.ready} value={settings[key]} onChange={e=>presentation.update({[key]:e.target.value})}/></label>)}<label>Contrast<input type="range" aria-label="Field contrast" disabled={!presentation.ready} min=".5" max="2" step=".05" value={settings.contrast} onChange={e=>presentation.update({contrast:Number(e.target.value)})}/></label><button type="button" onClick={()=>presentation.update({colorLow:DEFAULTS.colorLow,colorHigh:DEFAULTS.colorHigh,contrast:1})}>Default quantitative palette</button><small>Each visible cell corresponds to one saved finite-difference value. No smoothing or generated intermediate fields are applied.</small></aside>}
    {cell&&<aside className={styles.inspector}><div className={styles.panelHeading}><span className={styles.eyebrow}>SELECTED CELL</span><button type="button" aria-label="Clear field cell selection" onClick={()=>presentation.update({selectedCell:null})}><X size={14}/></button></div><strong>{number(cell.value)} {index.field_unit}</strong><code>x = {number(cell.xValue)}, y = {number(cell.yValue)} {index.length_unit}</code><small>Cell ({cell.x}, {cell.y}) · t = {number(frame?.time)} {index.time_unit}</small><button type="button" onClick={()=>engine.current?.focusSelection()}>Fit cell</button></aside>}
    {index&&<div className={styles.fieldLegend} aria-label="Fixed field color legend"><div className={styles.legendScale}><strong>{index.field_name.replaceAll('_',' ')} [{index.field_unit}]</strong><div className={styles.legendBar} style={{background:gradient}}/><div className={styles.legendEndpoints}><span>{number(index.color_scale.min)}</span><span>{number(index.color_scale.max)}</span></div></div><div className={styles.legendDetails}><strong>Fixed range across time</strong><span>{number(index.lx)} × {number(index.ly)} {index.length_unit}</span><span>x right · y up in front view</span></div></div>}
    {!frame&&!error&&<div className={styles.loading} role="status"><i/><strong>{active?'Waiting for the first computed field':'Loading saved field values'}</strong><p>The viewer reads committed solver artifacts.</p></div>}
    {index&&frame&&<footer className={styles.footer}><div className={styles.timeline}><button type="button" aria-label="Restart field playback" onClick={()=>seek(index.start)}><RotateCcw size={15}/></button><button type="button" className={styles.play} aria-label={playing?'Pause field':'Play field'} disabled={index.end<=index.start} onClick={()=>{if(time>=index.end)setTime(index.start);setPlaying(v=>!v);}}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><input aria-label="Recorded field time" type="range" min="0" max={TIMELINE_SLIDER_MAX} step="1" value={timelineSliderValue(time,index.start,index.end)} aria-valuetext={`${number(frame.time)} ${index.time_unit}`} onChange={e=>seek(timelineSliderTime(e.target.value,index.start,index.end))}/><code>{number(frame.time)} / {number(index.end)} {index.time_unit}</code></div><div className={styles.playbackOptions}><label>Playback duration<input aria-label="Field playback duration in seconds" type="number" min=".1" max="86400" value={settings.playbackDurationSeconds} onChange={e=>{const value=Number(e.target.value);if(value>=.1&&value<=86400)presentation.update({playbackDurationSeconds:value});}}/>s at 1×</label><select aria-label="Field playback speed" value={settings.speed} onChange={e=>presentation.update({speed:Number(e.target.value)})}>{[.1,.25,.5,1,2,4,8,16,32].map(value=><option key={value} value={value}>{value}×</option>)}</select><div className={styles.exportActions}>{onCapture&&<button type="button" disabled={capturing||buffering} onClick={observe}><Eye size={14}/>{capturing?'Observing…':'Ask AI to inspect'}</button>}<LaboratoryVideoExport job={job} index={index} presentation={settings} camera={()=>engine.current?.cameraState()} duration={settings.playbackDurationSeconds/settings.speed}/></div></div><div className={styles.bottomLine}><span>Drag orbit · right drag pan · scroll zoom. Click a cell to read its value.</span><span>{store.current?.cache.size||0} cached fields</span></div>{(reconnecting||presentation.warning)&&<p role="status" className={styles.syncNotice}>{presentation.warning||'Reconnecting to newly recorded fields. Saved data remains available.'}</p>}</footer>}
    {error&&<div className={styles.error} role="alert"><strong>{error}</strong><button type="button" onClick={()=>setError('')}>Dismiss</button></div>}
  </section>;
}
