'use client';
import {useEffect,useRef,useState} from 'react';
import {Download,X} from 'lucide-react';
import {api} from '@/lib/api';
import {laboratoryJson,laboratoryUrl} from '@/lib/laboratory-http.mjs';
import {createExportRefresh,exportsForSource,exportDownloadName} from '@/lib/laboratory-exports.mjs';
import styles from './LaboratoryViewer.module.css';

export default function LaboratoryVideoExport({job,index,presentation,camera,duration=30}){
  const [open,setOpen]=useState(false),[settings,setSettings]=useState({width:1920,height:1080,fps:30,playback_duration_seconds:duration,labels:true}),[estimate,setEstimate]=useState(null),[exportJob,setExportJob]=useState(null),[error,setError]=useState(''),[reconnecting,setReconnecting]=useState(false),[busy,setBusy]=useState(false),dismissed=useRef(new Set());
  const path=`/api/laboratory/jobs/${job.id}`,state=exportJob?.state;
  const body=()=>({...settings,start_time:settings.start_time??index.start,end_time:settings.end_time??index.end,presentation:{...presentation,camera:camera()}});
  useEffect(()=>{const controller=new AbortController();const refresh=createExportRefresh({signal:controller.signal,load:()=>api.labJobs(job.project_id,controller.signal),onValue:value=>{const latest=exportsForSource(value.jobs||value,job.id).find(j=>!dismissed.current.has(j.id));if(latest)setExportJob(previous=>!previous||previous.id===latest.id||Date.parse(latest.created_at)>Date.parse(previous.created_at||0)?latest:previous);},onUnavailable:setReconnecting});refresh();const timer=setInterval(refresh,5000);return()=>{clearInterval(timer);controller.abort();};},[job.id,job.project_id]);
  useEffect(()=>{if(!exportJob||['completed','failed','cancelled','paused','timed_out'].includes(state))return;const controller=new AbortController(),refresh=createExportRefresh({signal:controller.signal,load:()=>laboratoryJson(`/api/laboratory/exports/${exportJob.id}`,{signal:controller.signal}),onValue:setExportJob,onUnavailable:setReconnecting});refresh();const timer=setInterval(refresh,1500);return()=>{clearInterval(timer);controller.abort();};},[exportJob?.id,state]);
  useEffect(()=>{if(!open)return;const controller=new AbortController();setEstimate(null);const timer=setTimeout(()=>laboratoryJson(`${path}/exports/estimate`,{method:'POST',body:body(),signal:controller.signal}).then(setEstimate).catch(error=>{if(error.name!=='AbortError')setEstimate({supported:false,reason:error.message});}),350);return()=>{clearTimeout(timer);controller.abort();};},[open,settings,presentation,path,index.start,index.end]);
  async function start(){setBusy(true);setError('');try{setExportJob(await laboratoryJson(`${path}/exports`,{method:'POST',body:body()}));setOpen(false);}catch(error){setError(error.message);}finally{setBusy(false);}}
  return <><button type="button" disabled={index.end<=index.start} onClick={()=>{setSettings(s=>({...s,playback_duration_seconds:duration}));setOpen(true);}}><Download size={14}/>Export video</button>
    {open&&<div className={styles.modal}><div><div className={styles.panelHeading}><strong>Export saved numerical field</strong><button type="button" aria-label="Close field export" onClick={()=>setOpen(false)}><X size={16}/></button></div><label>Resolution<select value={settings.height} onChange={e=>{const height=Number(e.target.value);setSettings(s=>({...s,height,width:height===2160?3840:height===1080?1920:1280}));}}><option value="720">1280 × 720 · HD</option><option value="1080">1920 × 1080 · Full HD</option><option value="2160">3840 × 2160 · 4K</option></select></label><label>Frames per second<select value={settings.fps} onChange={e=>setSettings(s=>({...s,fps:Number(e.target.value)}))}>{[24,30,60].map(fps=><option key={fps}>{fps}</option>)}</select></label><label>Video duration (seconds)<input type="number" min=".1" max="86400" step="any" value={settings.playback_duration_seconds} onChange={e=>setSettings(s=>({...s,playback_duration_seconds:Number(e.target.value)}))}/></label>{['start','end'].map(key=><label key={key}>{key} time ({index.time_unit})<input type="number" min={index.start} max={index.end} step="any" value={settings[`${key}_time`]??index[key]} onChange={e=>setSettings(s=>({...s,[`${key}_time`]:Number(e.target.value)}))}/></label>)}<p>The video reads exact saved fields with a fixed quantitative color scale. Playback duration changes viewing speed; it does not add scientific time or run the solver again.</p><small>{estimate?estimate.supported?`Approximately ${Math.ceil(estimate.estimated_seconds)} seconds to render, including cold startup. ${estimate.frame_count} frames; ${estimate.movie_duration_seconds.toPrecision(4)} encoded seconds. ${estimate.estimate_basis}`:estimate.reason:'Checking export resources…'}</small>{error&&<p role="alert">{error}</p>}<button type="button" disabled={busy||!estimate?.supported} onClick={start}>{busy?'Submitting…':'Render in background'}</button></div></div>}
    {exportJob&&<div className={styles.exportStatus} role="status"><strong>Video · {state}</strong><span>{Math.round((exportJob.progress?.fraction||0)*100)}%</span>{state==='completed'&&exportJob.download_url?<a href={laboratoryUrl(exportJob.download_url)} download={exportDownloadName(exportJob)}>Save MP4</a>:!['failed','cancelled','paused','timed_out'].includes(state)&&<button type="button" onClick={async()=>{try{setExportJob(await laboratoryJson(`/api/laboratory/exports/${exportJob.id}/cancel`,{method:'POST',body:{}}));}catch(error){setError(error.message);}}}>Cancel</button>}<button type="button" aria-label="Dismiss field export status" onClick={()=>{dismissed.current.add(exportJob.id);setExportJob(null);}}><X size={14}/></button>{reconnecting&&<small>Reconnecting to export status…</small>}{exportJob.error&&<small>{exportJob.error}</small>}</div>}
  </>;
}
