'use client';

import {TIMELINE_SLIDER_MAX,timelineSliderTime,timelineSliderValue} from '@/lib/timeline-slider.mjs';

import {forwardRef,useCallback,useEffect,useImperativeHandle,useRef,useState} from 'react';
import {Camera,Download,Eye,Focus,Maximize,Pause,Play,Redo2,RotateCcw,Settings2,Undo2,X} from 'lucide-react';
import {api} from '@/lib/api';
import {PresentationWriter,presentationPatch} from '@/lib/presentation-writer.mjs';
import {exportsForSource,exportDownloadName,createExportRefresh,savedRenderingReady} from '@/lib/laboratory-exports.mjs';
import {TrajectoryStore,normalizeTrajectoryIndex} from '@/lib/laboratory-trajectory.mjs';
import {particleUnits} from '@/lib/particle-presentation.mjs';
import styles from './LaboratoryViewer.module.css';
import CameraControls from './CameraControls';
import LaboratoryFieldViewer from './LaboratoryFieldViewer';
import LaboratoryIllustrationViewer from './LaboratoryIllustrationViewer';
import LaboratoryPlotViewer from './LaboratoryPlotViewer';
import LaboratoryArtifactViewer from './LaboratoryArtifactViewer';

const DEFAULTS={color:'#9f8ded',background:'#080f20',exposure:1.1,contrast:1,opacity:1,selectedIds:[],hiddenIds:[],dimOthers:false,showBox:true,showGrid:true,showLabels:true,interpolate:false,playbackDurationSeconds:30,speed:1,savedViews:[]};
const number=value=>Number.isFinite(Number(value))?Number(value).toLocaleString(undefined,{maximumSignificantDigits:6}):'—';
const absolute=path=>/^https?:\/\//.test(path)?path:`${api.baseUrl}${path}`;
async function json(path,{signal,method='GET',body,keepalive=false}={}){const response=await fetch(absolute(path),{signal,method,keepalive,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const value=await response.json().catch(()=>null);if(!response.ok){const error=new Error(value?.error?.message||value?.message||`Request failed (${response.status})`);error.status=response.status;error.body=value;throw error;}return value;}

/** Saved numerical state, presentation revisions, and captured observations have separate identities. */
const ParticleLaboratoryViewer=forwardRef(function ParticleLaboratoryViewer({job,onCapture,onPresentationChange,presentation:externalPresentation},ref){
  const published=job.kind==='published_simulation',renderingReady=savedRenderingReady(job),isolated=job.input?.engine==='newtonian_nbody',defaults=(isolated||published)?{...DEFAULTS,color:null,showBox:false}:DEFAULTS;
  const host=useRef(null),panel=useRef(null),engine=useRef(null),store=useRef(null),options=useRef(defaults),saveTimer=useRef(null),revision=useRef(0),writer=useRef(null),presentationValue=useRef(defaults),applyingRemote=useRef(false),dismissedExports=useRef(new Set()),mounted=useRef(false),onPresentationRef=useRef(onPresentationChange);
  const [presentation,setPresentation]=useState(defaults),[undo,setUndo]=useState([]),[redo,setRedo]=useState([]),[index,setIndex]=useState(null),[topology,setTopology]=useState(null),[timeline,setTimeline]=useState(null),[playing,setPlaying]=useState(false),[loading,setLoading]=useState(true),[buffering,setBuffering]=useState(false),[stats,setStats]=useState(null),[cache,setCache]=useState(null),[error,setError]=useState(''),[saveError,setSaveError]=useState(''),[settings,setSettings]=useState(false),[exporting,setExporting]=useState(false),[estimate,setEstimate]=useState(null),[estimateLoading,setEstimateLoading]=useState(false),[exportJob,setExportJob]=useState(null),[exportSync,setExportSync]=useState({list:false,status:false}),[exportSettings,setExportSettings]=useState({width:1920,height:1080,fps:30,playback_duration_seconds:30,labels:true}),[view,setView]=useState('perspective'),[retry,setRetry]=useState(0),[capturing,setCapturing]=useState(false);
  const path=`/api/laboratory/jobs/${encodeURIComponent(job.id)}`,state=job.state||job.status,active=['queued','preparing','provisioning','waiting','running','validating','rendering'].includes(state);
  options.current={...presentation,playing};onPresentationRef.current=onPresentationChange;
  const cachePresentation=useCallback(next=>{try{localStorage.setItem(`phaseforge.lab.presentation.${job.id}`,JSON.stringify(next));}catch{}onPresentationRef.current?.(next);},[job.id]);
  const persist=useCallback((next,patch)=>{cachePresentation(next);writer.current?.queue(patch);clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>writer.current?.flush(),350);},[cachePresentation]);
  const update=useCallback((patch,{history=true}={})=>{
    if(applyingRemote.current)return;
    const previous=presentationValue.current,next={...previous,...patch},changed=presentationPatch(previous,next);
    if(!Object.keys(changed).length)return;
    presentationValue.current=next;options.current={...options.current,...next};setPresentation(next);
    if(history){setUndo(items=>[...items.slice(-39),Object.fromEntries(Object.keys(changed).map(key=>[key,previous[key]]))]);setRedo([]);}
    persist(next,changed);
  },[persist]);
  useEffect(()=>{if(externalPresentation){const next={...presentationValue.current,...externalPresentation};presentationValue.current=next;options.current={...options.current,...next};setPresentation(next);applyingRemote.current=true;try{if(externalPresentation.camera)engine.current?.setCamera(externalPresentation.camera);}finally{applyingRemote.current=false;}}},[externalPresentation]);
  useEffect(()=>{
    mounted.current=true;const controller=new AbortController();let current=null,source=null,presentationWriter=null,timer=null,busy=false,cancelled=false;
    setLoading(true);setPlaying(false);setError('');setIndex(null);setTopology(null);setTimeline(null);setUndo([]);setRedo([]);setExportJob(null);setExportSync({list:false,status:false});dismissedExports.current.clear();
    let local={};try{local=JSON.parse(localStorage.getItem(`phaseforge.lab.presentation.${job.id}`)||'{}');}catch{}
    presentationValue.current={...defaults,...local};options.current={...presentationValue.current,playing:false};setPresentation(presentationValue.current);
    async function prepare(){if(busy||cancelled)return;busy=true;try{
      const [shape,rawIndex,persisted]=await Promise.all([json(`${path}/artifacts/topology.json`,{signal:controller.signal}),json(`${path}/artifacts/trajectory/index.json`,{signal:controller.signal}),json(`${path}/presentation`,{signal:controller.signal}).catch(()=>null)]);
      const normalized=normalizeTrajectoryIndex(rawIndex);if(!normalized.chunks.length){busy=false;timer=setTimeout(prepare,2000);return;}
      if(cancelled)return;revision.current=persisted?.revision||0;const settings={...defaults,...local,...persisted?.settings};presentationValue.current=settings;options.current={...settings,playing:false};setPresentation(settings);setTopology(shape);setIndex(normalized);
      presentationWriter=new PresentationWriter({revision:revision.current,settings:persisted?.settings||settings,
        send:body=>json(`${path}/presentation`,{method:'PUT',body,keepalive:true}),
        onState:(saved,nextRevision,details)=>{if(cancelled)return;revision.current=nextRevision;const next={...defaults,...saved};const previous=presentationValue.current;const remoteKeys=(details?.remoteKeys||[]).filter(key=>JSON.stringify(previous[key])!==JSON.stringify(next[key]));if(remoteKeys.length){setUndo(items=>[...items.slice(-39),Object.fromEntries(remoteKeys.map(key=>[key,previous[key]]))]);setRedo([]);}presentationValue.current=next;options.current={...options.current,...next};setPresentation(next);cachePresentation(next);setSaveError('');applyingRemote.current=true;try{if(next.camera&&JSON.stringify(engine.current?.cameraState())!==JSON.stringify(next.camera))engine.current?.setCamera(next.camera);}finally{applyingRemote.current=false;}},
        onError:error=>{if(!cancelled)setSaveError(`Presentation kept locally; server save failed: ${error.message}`);}});
      writer.current=presentationWriter;
      source=new TrajectoryStore({index:rawIndex,loadBytes:async relative=>{const response=await fetch(absolute(`${path}/artifacts/${relative.split('/').map(encodeURIComponent).join('/')}`),{signal:controller.signal});if(!response.ok)throw Error(`Recorded trajectory unavailable (${response.status})`);return response.arrayBuffer();},onCache:setCache});store.current=source;
      const {createLaboratoryViewer}=await import('@/lib/laboratory-viewer.mjs');if(cancelled)return;
      current=await createLaboratoryViewer(host.current,{topology:shape,source,signal:controller.signal,options:()=>options.current,onTime:setTimeline,onStats:setStats,onSelect:id=>update({selectedIds:id?[id]:[]}),onCamera:camera=>update({camera},{history:false}),onLoading:setBuffering,onError:setError,onStop:()=>setPlaying(false)});
      if(cancelled){current?.dispose();return;}engine.current=current;setLoading(false);if(Number.isFinite(settings.displayTime))current?.seek(settings.displayTime);
    }catch(e){if(cancelled||e.name==='AbortError')return;if(e.status===404&&['queued','preparing','provisioning','waiting','running','validating'].includes(job.state||job.status)){timer=setTimeout(prepare,2000);}else{setError(e.message);setLoading(false);}}finally{busy=false;}}
    prepare();return()=>{cancelled=true;mounted.current=false;controller.abort();clearTimeout(timer);clearTimeout(saveTimer.current);presentationWriter?.detach();if(writer.current===presentationWriter)writer.current=null;current?.dispose();source?.dispose();if(engine.current===current)engine.current=null;if(store.current===source)store.current=null;};
  },[job.id,retry]);
  useEffect(()=>{if(!store.current)return;const controller=new AbortController();let busy=false;const refresh=async()=>{if(busy)return;busy=true;try{const next=await json(`${path}/artifacts/trajectory/index.json`,{signal:controller.signal});if(!controller.signal.aborted){store.current?.updateIndex(next);setIndex(normalizeTrajectoryIndex(next));}}catch(e){if(e.name!=='AbortError'&&e.status!==404)setError(e.message);}finally{busy=false;}};refresh();const interval=active?setInterval(refresh,2500):null;return()=>{clearInterval(interval);controller.abort();};},[active,path,loading]);
  useEffect(()=>{if(loading)return;const controller=new AbortController();const timer=setInterval(async()=>{try{await writer.current?.retry();const saved=await json(`${path}/presentation`,{signal:controller.signal});if(!controller.signal.aborted)writer.current?.acceptRemote(saved);}catch{}},5000);return()=>{clearInterval(timer);controller.abort();};},[path,loading]);
  useEffect(()=>{if(!exportJob||['completed','failed','cancelled'].includes(exportJob.state||exportJob.status)){setExportSync(previous=>previous.status?{...previous,status:false}:previous);return;}const controller=new AbortController();const refresh=createExportRefresh({signal:controller.signal,load:()=>json(exportJob.status_url||`/api/laboratory/exports/${exportJob.id}`,{signal:controller.signal}),onValue:setExportJob,onUnavailable:status=>setExportSync(previous=>previous.status===status?previous:{...previous,status})});const interval=setInterval(refresh,1500);return()=>{clearInterval(interval);controller.abort();};},[exportJob?.id,exportJob?.state,exportJob?.status]);
  useEffect(()=>{if(!exporting||!index)return;const controller=new AbortController();setEstimate(null);setEstimateLoading(true);const timer=setTimeout(async()=>{try{const result=await json(`${path}/exports/estimate`,{method:'POST',signal:controller.signal,body:{...exportSettings,start_time:Number(exportSettings.start_time??index.start),end_time:Number(exportSettings.end_time??index.end),presentation:{...presentation,camera:engine.current?.cameraState()}}});if(!controller.signal.aborted)setEstimate(result);}catch(e){if(e.name!=='AbortError')setEstimate({supported:null,reason:`Estimate unavailable: ${e.message}`});}finally{if(!controller.signal.aborted)setEstimateLoading(false);}},350);return()=>{clearTimeout(timer);controller.abort();};},[exporting,exportSettings,presentation,index?.start,index?.end,path]);
  useEffect(()=>{const controller=new AbortController();const refresh=createExportRefresh({signal:controller.signal,load:()=>api.labJobs(job.project_id,controller.signal),onValue:response=>{const latest=exportsForSource(response.jobs||response,job.id).find(item=>!dismissedExports.current.has(item.id));if(latest)setExportJob(previous=>!previous||previous.id===latest.id||Date.parse(latest.created_at)>Date.parse(previous.created_at||0)?latest:previous);},onUnavailable:list=>setExportSync(previous=>previous.list===list?previous:{...previous,list})});refresh();const timer=setInterval(refresh,5000);return()=>{clearInterval(timer);controller.abort();};},[job.id,job.project_id]);
  const capture=useCallback(()=>{const value=engine.current?.capture();return value?{...value,sourceJobId:job.id}:null;},[job.id]);
  useImperativeHandle(ref,()=>({captureFrame:capture,seek:time=>engine.current?.seek(time),setPresentation:patch=>update(patch),cameraCommand:command=>{if(command.view)engine.current?.fit(command.view,command.entity_id);if(command.position||command.target)engine.current?.setCamera(command);else engine.current?.navigate(command);}}),[capture,update]);
  const seek=time=>{setPlaying(false);engine.current?.seek(time);update({displayTime:time},{history:false});};
  const changeView=value=>{setView(value);engine.current?.fit(value);};
  const restore=(items,setItems,setOther)=>{if(!items.length)return;const patch=items.at(-1),previous=presentationValue.current;setOther(other=>[...other,Object.fromEntries(Object.keys(patch).map(key=>[key,previous[key]]))]);setItems(items.slice(0,-1));update(patch,{history:false});if(patch.camera){applyingRemote.current=true;try{engine.current?.setCamera(patch.camera);}finally{applyingRemote.current=false;}}};
  async function observe(){setCapturing(true);try{const captured=capture();if(captured)await onCapture?.(captured);}catch(e){setError(e.message);}finally{setCapturing(false);}}
  const saveImage=()=>{const captured=capture();if(!captured)return;const anchor=document.createElement('a');anchor.href=captured.dataUrl;anchor.download=`phaseforge-${job.id}-t${captured.time}.png`;anchor.click();};
  const startExport=async()=>{try{const value=await json(`${path}/exports`,{method:'POST',body:{...exportSettings,start_time:Number(exportSettings.start_time??index.start),end_time:Number(exportSettings.end_time??index.end),presentation:{...presentation,camera:engine.current?.cameraState()}}});setExportJob(value);setExporting(false);setError('');}catch(e){setError(e.message);}};
  const selected=presentation.selectedIds?.[0],selectedEntity=engine.current?.sample().left.entities.find(e=>String(e.id)===selected),selectionSpec=topology?.entities.find(e=>String(e.id)===selected),currentTime=timeline?.time??index?.start??0,units=particleUnits(topology||{},index||{}),unit=units.time,duration=presentation.playbackDurationSeconds/presentation.speed,exportState=exportJob?.state||exportJob?.status;
  return <section ref={panel} className={`${styles.viewer} ${styles.particleViewer}`} aria-label="Numerical laboratory trajectory viewer">
    <div ref={host} className={styles.canvas}/>
    <header className={styles.header}><div><span className={styles.eyebrow}>RETAINED SIMULATION</span><strong>{job.title||job.input?.title||'Recorded particle laboratory'}</strong><small>{topology?`${topology.entities.length.toLocaleString()} particles · ${index?.frame_count.toLocaleString()} recorded states · ${units.position}`:'Preparing saved numerical states'}</small></div><div className={styles.actions}>
      <button type="button" aria-label="Presentation settings" title="Color, lighting and display" onClick={()=>setSettings(value=>!value)}><Settings2 size={17}/></button><button type="button" aria-label="Undo presentation edit" disabled={!undo.length} onClick={()=>restore(undo,setUndo,setRedo)}><Undo2 size={17}/></button><button type="button" aria-label="Redo presentation edit" disabled={!redo.length} onClick={()=>restore(redo,setRedo,setUndo)}><Redo2 size={17}/></button><button type="button" title="Save current frame" aria-label="Save current frame" disabled={loading} onClick={saveImage}><Camera size={17}/></button><button type="button" aria-label="Fullscreen simulation" onClick={()=>document.fullscreenElement?document.exitFullscreen?.():panel.current?.requestFullscreen?.()}><Maximize size={17}/></button>
    </div></header>
    <div className={styles.provenance}><i/>{presentation.interpolate?'Display interpolation between recorded states':'Exact recorded particle positions'}{buffering&&<span> · loading chunk</span>}</div>
    {!loading&&<div className={styles.cameraTools}><select aria-label="Standard camera view" value={view} onChange={e=>changeView(e.target.value)}><option value="perspective">Perspective</option><option value="front">Front · XY</option><option value="top">Top · XZ</option><option value="side">Side · YZ</option></select><CameraControls engineRef={engine} storageKey={`trajectory-${job.id}`}/></div>}
    {!loading&&!isolated&&<div className={styles.orientation} aria-label="Orientation axes"><button type="button" onClick={()=>changeView('side')} style={{color:'#ffa69e'}}>X</button><button type="button" onClick={()=>changeView('top')} style={{color:'#a3e5b5'}}>Y</button><button type="button" onClick={()=>changeView('front')} style={{color:'#8dcaff'}}>Z</button><small>Standard views</small></div>}
    {settings&&<aside className={styles.settings}><div className={styles.panelHeading}><strong>Presentation</strong><button type="button" aria-label="Close presentation settings" onClick={()=>setSettings(false)}><X size={14}/></button></div><p>These edits reuse the saved simulation.</p><label>Particle color<input type="color" value={presentation.color||'#9f8ded'} onChange={e=>update({color:e.target.value})}/></label>{(isolated||published)&&<button type="button" onClick={()=>update({color:null})}>Restore body ID colors</button>}<label>Background<input type="color" value={presentation.background} onChange={e=>update({background:e.target.value})}/></label><label>Exposure<input aria-label="Exposure" type="range" min=".15" max="3" step=".05" value={presentation.exposure} onChange={e=>update({exposure:Number(e.target.value)})}/></label><label>Contrast<input aria-label="Particle contrast" type="range" min=".5" max="2" step=".05" value={presentation.contrast} onChange={e=>update({contrast:Number(e.target.value)})}/></label><label>Opacity<input aria-label="Particle opacity" type="range" min=".05" max="1" step=".05" value={presentation.opacity} onChange={e=>update({opacity:Number(e.target.value)})}/></label>{[['showBox','Periodic cell outline'],['showGrid','Scale reference grid'],['showLabels','Scientific labels'],['interpolate','Interpolate display'],['dimOthers','Dim unselected particles']].filter(([key])=>!isolated||key!=='showBox').map(([key,label])=><label key={key}>{label}<input type="checkbox" checked={presentation[key]} onChange={e=>update({[key]:e.target.checked})}/></label>)}<small>{topology?.radius_semantics||'Particle radii are a display representation.'}</small><button type="button" onClick={()=>update({savedViews:[...(presentation.savedViews||[]).slice(-7),{name:`View ${(presentation.savedViews?.length||0)+1}`,camera:engine.current?.cameraState()}]})}>Save camera view</button>{(presentation.savedViews||[]).map((saved,i)=><button type="button" key={i} onClick={()=>{engine.current?.setCamera(saved.camera);update({camera:saved.camera});}}>{saved.name}</button>)}<details><summary>Precise camera coordinates</summary>{['position','target'].map(key=><label className={styles.coordinates} key={key}>{key}<input aria-label={`Camera ${key}`} key={JSON.stringify(presentation.camera?.[key])} defaultValue={presentation.camera?.[key]?.join(', ')||''} onBlur={e=>{const values=e.target.value.split(',').map(Number);if(values.length===3&&values.every(Number.isFinite))engine.current?.setCamera({[key]:values});}}/></label>)}</details></aside>}
    {selected&&<aside className={styles.inspector}><div className={styles.panelHeading}><span className={styles.eyebrow}>SELECTED PARTICLE</span><button type="button" aria-label="Clear particle selection" onClick={()=>update({selectedIds:[]})}><X size={14}/></button></div><strong>{selectionSpec?.element||'Entity'} · {selected}</strong><code>{selectedEntity?.position.map(number).join(' · ')} {units.position}</code><small>Recorded {isolated?'t/T0':'t'} = {number(timeline?.recordedTime)} {!isolated&&unit}{isolated&&<> · mass {number(selectionSpec?.mass)} {units.mass}</>}</small><button type="button" onClick={()=>engine.current?.fit(view,selected)}><Focus size={14}/>Focus selection</button><button type="button" onClick={()=>update({dimOthers:!presentation.dimOthers})}>Highlight selection</button><button type="button" onClick={()=>update({hiddenIds:[...(presentation.hiddenIds||[]),selected],selectedIds:[]})}>Hide particle</button></aside>}
    {!!presentation.hiddenIds?.length&&<button type="button" className={styles.restoreHidden} onClick={()=>update({hiddenIds:[]})}>Restore {presentation.hiddenIds.length} hidden particles</button>}
    {presentation.showLabels&&index&&<div className={styles.particleLegend}><div><strong>{isolated?'Isolated Newtonian bodies':published?'Retained particle coordinates':'Periodic particles'} · {units.position}</strong><div className={styles.bodyColors}>{topology?.entities.slice(0,8).map(entity=><span key={entity.id}><i style={{background:presentation.color||entity.color||'#9f8ded'}}/>{entity.id}</span>)}</div></div><div className={styles.legendDetails}>{topology?.box_nm||topology?.box?`Cell ${(topology.box_nm||topology.box).map(number).join(' × ')} ${units.position}`:'Marker radii are display sizes.'}<br/>{published?'Published numerical states. Assess model validation from the source evidence.':isolated?'Coordinates and masses use scaled units.':'Coordinates are retained from the numerical solver.'}</div></div>}
    {loading&&<div className={styles.loading} role="status"><i/><strong>{active?'Waiting for the first measured frames':'Loading the saved trajectory'}</strong><p>The viewer reads recorded solver positions as they become available.</p></div>}
    {index&&!loading&&<footer className={styles.footer}><div className={styles.timeline}><button type="button" aria-label="Restart trajectory" onClick={()=>seek(index.start)}><RotateCcw size={15}/></button><button type="button" className={styles.play} disabled={index.end<=index.start} aria-label={playing?'Pause trajectory':'Play trajectory'} onClick={()=>{if(currentTime>=index.end)engine.current?.seek(index.start);setPlaying(value=>!value);}}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><input aria-label="Recorded simulation time" type="range" min="0" max={TIMELINE_SLIDER_MAX} step="1" value={timelineSliderValue(currentTime,index.start,index.end)} aria-valuetext={`${number(currentTime)} ${unit}`} onChange={e=>seek(timelineSliderTime(e.target.value,index.start,index.end))}/><code>{isolated&&'t/T0 = '}{number(presentation.interpolate?currentTime:timeline?.recordedTime)} / {number(index.end)} {!isolated&&unit}</code></div><div className={styles.playbackOptions}><label>Playback duration<input aria-label="Playback duration in seconds" type="number" min=".1" max="86400" step="1" value={presentation.playbackDurationSeconds} onChange={e=>{const value=Number(e.target.value);if(value>0)update({playbackDurationSeconds:value});}}/>s at 1×</label><select aria-label="Playback speed" value={presentation.speed} onChange={e=>update({speed:Number(e.target.value)})}>{[.05,.1,.25,.5,1,2,4,8,16,32].map(value=><option key={value} value={value}>{value}×</option>)}</select><span>1 playback s = {number((index.end-index.start)/duration)} {unit}</span><div className={styles.exportActions}>{onCapture&&renderingReady&&<button type="button" disabled={capturing} onClick={observe}><Eye size={14}/>{capturing?'Observing…':'Ask AI to inspect'}</button>}{renderingReady&&<button type="button" disabled={index.end<=index.start} onClick={()=>{setExportSettings(previous=>({...previous,playback_duration_seconds:duration}));setExporting(true);}}><Download size={14}/>Export video</button>}</div></div><div className={styles.bottomLine}><span>Drag orbit · Shift/right drag pan · scroll zoom · arrows tilt · +/− zoom</span><details><summary>{stats?`${stats.active?`${stats.fps} fps`:'Preview idle'} · ${stats.width} × ${stats.height}`:'Graphics metrics'}</summary><p>{stats&&<>CPU render submission mean {number(stats.meanFrameMs)} ms, p95 {number(stats.p95FrameMs)} ms; {stats.triangles.toLocaleString()} triangles, {stats.drawCalls} draw calls.<br/></>}{cache&&<>Display cache: {cache.chunks}/{cache.totalChunks} chunks, approximately {number(cache.bytes/1048576)} MiB.<br/></>}Preview pixel resolution adapts under load. Saved scientific coordinates and requested export resolution are unchanged.</p></details></div>{(exportSync.list||exportSync.status)&&<p className={styles.syncNotice} role="status">Reconnecting to export updates. Simulation controls remain available.</p>}</footer>}
    {exporting&&<div className={styles.modal}><div><div className={styles.panelHeading}><strong>Export saved simulation</strong><button type="button" aria-label="Close video export" onClick={()=>setExporting(false)}><X size={16}/></button></div><label>Resolution<select value={exportSettings.height} onChange={e=>{const height=Number(e.target.value);setExportSettings(previous=>({...previous,height,width:height===2160?3840:height===1080?1920:1280}));}}><option value="720">1280 × 720 · HD</option><option value="1080">1920 × 1080 · Full HD</option><option value="2160">3840 × 2160 · 4K</option></select></label><label>Frame rate<select value={exportSettings.fps} onChange={e=>setExportSettings(previous=>({...previous,fps:Number(e.target.value)}))}>{[24,30,60].map(fps=><option key={fps}>{fps}</option>)}</select></label><label>Video duration (seconds)<input type="number" min=".1" max="86400" step="any" value={exportSettings.playback_duration_seconds} onChange={e=>setExportSettings(previous=>({...previous,playback_duration_seconds:Number(e.target.value)}))}/></label><label>Start time ({unit})<input type="number" min={index?.start} max={index?.end} step="any" value={exportSettings.start_time??index?.start??0} onChange={e=>setExportSettings(previous=>({...previous,start_time:Number(e.target.value)}))}/></label><label>End time ({unit})<input type="number" min={index?.start} max={index?.end} step="any" value={exportSettings.end_time??index?.end??0} onChange={e=>setExportSettings(previous=>({...previous,end_time:Number(e.target.value)}))}/></label><label>Scientific labels<input type="checkbox" checked={exportSettings.labels} onChange={e=>setExportSettings(previous=>({...previous,labels:e.target.checked}))}/></label><p>{number(estimate?.movie_duration_seconds??Math.round(exportSettings.playback_duration_seconds*exportSettings.fps)/exportSettings.fps)} encoded seconds · {number(estimate?.frame_count??Math.round(exportSettings.playback_duration_seconds*exportSettings.fps))} video frames · MP4. Uses this camera and saved numerical trajectory. Interpolated display frames add no new computed science.</p><small>{estimateLoading?"Estimating render time…":Number.isFinite(estimate?.estimated_seconds)?`Estimated render time: ${number(estimate.estimated_seconds)} seconds. ${estimate.estimate_basis||"Estimate based on prior renderer throughput; actual time can vary."}`:estimate?.reason||"Waiting for export feasibility check."}</small>{estimate?.supported===false&&<p role="alert">{estimate.reason||"This export exceeds available resources."}</p>}<button type="button" disabled={estimateLoading||estimate?.supported===false} onClick={startExport}><Download size={15}/>Render in background</button></div></div>}
    {exportJob&&<div className={styles.exportStatus} role="status"><strong>Video export · {exportState}</strong><span>{exportJob.message||`${number((exportJob.progress?.fraction??exportJob.progress??0)*100)}%`}</span>{exportState==='completed'&&exportJob.download_url?<a download={exportDownloadName(exportJob)} href={absolute(exportJob.download_url)}>Save MP4</a>:!['completed','failed','cancelled'].includes(exportState)&&<button type="button" onClick={async()=>{try{setExportJob(await json(exportJob.cancel_url||`/api/laboratory/exports/${exportJob.id}/cancel`,{method:'POST',body:{}}));}catch(e){setError(e.message);}}}>Cancel export</button>}<button type="button" aria-label="Dismiss export status" onClick={()=>{dismissedExports.current.add(exportJob.id);setExportJob(null);}}><X size={14}/></button></div>}
    {saveError&&<div className={styles.saveError} role="status">{saveError}</div>}{error&&<div className={styles.error} role="alert"><strong>{error}</strong><button type="button" onClick={()=>{setError('');setRetry(value=>value+1);}}>Reload viewer</button><button type="button" aria-label="Dismiss viewer error" onClick={()=>setError('')}><X size={14}/></button></div>}
  </section>;
});
const LaboratoryViewer=forwardRef(function LaboratoryViewer(props,ref){
  if(props.job.kind==='generated')return <LaboratoryArtifactViewer job={props.job}/>;
  if(['study_plot','ml_study'].includes(props.job.kind))return <LaboratoryPlotViewer job={props.job}/>;
  if(props.job.kind==='illustration')return <LaboratoryIllustrationViewer {...props}/>;
  if((['diffusion_2d','heat_conduction_2d','navier_stokes_2d'].includes(props.job.input?.engine)||props.job.result?.representation==='scalar_field'))return <LaboratoryFieldViewer {...props}/>;
  if((['openmm_argon','newtonian_nbody'].includes(props.job.input?.engine)||props.job.result?.representation==='particle_trajectory'))return <ParticleLaboratoryViewer ref={ref} {...props}/>;
  return <div role="status">This saved laboratory result has no supported numerical viewer.</div>;
});
export default LaboratoryViewer;
