import {useEffect,useRef,useState} from 'react';
import {Bot,Clock3,Play,Pause,Square,RotateCcw,Network,ArrowRight} from 'lucide-react';
import {api} from '@/lib/api';
import {useModelSelection} from '@/lib/modelSelection';
import ModelPicker from './ModelPicker';
import {DEFAULT_BUILD} from '@/lib/experiment';

const ACTIVE=new Set(['queued','running','planning','building','reviewing','waiting']);
function remaining(task,now){if(task.state!=='running')return task.remaining_seconds||0;return task.deadline_at?Math.max(0,(Date.parse(task.deadline_at)-now)/1000):task.remaining_seconds||0;}
function time(s){const n=Math.max(0,Math.floor(s));return `${String(Math.floor(n/3600)).padStart(2,'0')}:${String(Math.floor(n/60)%60).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
export default function ResearchSessions({project,providers=[],onRefresh,onInspectRun}) {
  const {selection}=useModelSelection();
  const [tasks,setTasks]=useState([]),[objective,setObjective]=useState(''),[minutes,setMinutes]=useState(30),[specialists,setSpecialists]=useState(2),[cycles,setCycles]=useState(3),[busy,setBusy]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(Date.now());
  const [assumptions,setAssumptions]=useState(true);
  const [composerOpen,setComposerOpen]=useState(true);
  const locked=useRef(false),owner=useRef(project?.id),seen=useRef(new Map());owner.current=project?.id;
  useEffect(()=>{setObjective('');setTasks([]);setComposerOpen(true);setError('');seen.current.clear();if(!project?.id)return;let alive=true,timer;const load=async()=>{try{const r=await api.tasks(project.id);if(alive){const rows=Array.isArray(r)?r:r.tasks||[];if(!seen.current.size&&rows.length)setComposerOpen(false);setTasks(rows);for(const t of rows){const signature=`${t.state}:${(t.run_ids||[]).length}:${t.artifacts?.length||0}`;if(seen.current.has(t.id)&&seen.current.get(t.id)!==signature)onRefresh?.();seen.current.set(t.id,signature);}}}catch(e){if(alive)setError(e.message);}finally{if(alive)timer=setTimeout(load,3000);}};load();return()=>{alive=false;clearTimeout(timer);};},[project?.id,onRefresh]);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
  async function start(e){e.preventDefault();if(locked.current||!project)return;locked.current=true;setBusy(true);setError('');const id=project.id;try{const payload={objective:objective.trim()||project.question,duration_minutes:Number(minutes),specialist_count:Number(specialists),max_cycles:Number(cycles),auto_run:true,experiment_options:{...DEFAULT_BUILD,assumptions_allowed:assumptions},...selection,model:selection.model||null};const r=await api.createTask(id,payload);if(owner.current===id){setTasks(v=>[r.task||r,...v]);setComposerOpen(false);setObjective('');}}catch(e){if(owner.current===id)setError(e.message);}finally{locked.current=false;setBusy(false);}}
  async function control(task,action){if(locked.current)return;locked.current=true;setBusy(true);setError('');const id=project?.id;try{const r=await api.controlTask(task.id,{action,...(action==='resume'?{...selection,model:selection.model||null,...(['time_limit','failed'].includes(task.state)&&task.remaining_seconds===0?{duration_minutes:Number(minutes)}:{})}:{})});if(owner.current===id)setTasks(v=>v.map(t=>t.id===task.id?(r.task||r):t));}catch(e){if(owner.current===id)setError(e.message);}finally{locked.current=false;setBusy(false);}}
  const ready=providers.some(p=>p.configured);
  return <section className="sessionsPanel">
    <div className="sessionsHeading"><Network size={27}/><div><h2>A research team, on your clock.</h2><p>Let specialists build, challenge, simulate, and review together.</p></div>{tasks.length>0&&<button className="button button--secondary" onClick={()=>setComposerOpen(v=>!v)}>{composerOpen?'View progress':'New session'}</button>}</div>
    {(composerOpen||!tasks.length)&&<form className="sessionComposer" onSubmit={start}>
      <label>Research objective<textarea aria-label="Session research objective" value={objective} onChange={e=>setObjective(e.target.value)} placeholder={project?.question||'Create a project to start a research session.'} disabled={!project||busy} maxLength={12000}/></label>
      <div className="sessionOptions"><label>Time budget (minutes)<input aria-label="Session duration in minutes" type="number" min="1" max="10080" value={minutes} onChange={e=>setMinutes(e.target.value)} required/></label><label>Collaborating specialists<select value={specialists} onChange={e=>setSpecialists(e.target.value)} aria-label="Number of specialists"><option value="1">1 specialist</option><option value="2">2 specialists</option><option value="3">3 specialists</option></select></label><label>Experiment cycles<select value={cycles} onChange={e=>setCycles(e.target.value)} aria-label="Maximum experiment cycles">{[1,2,3,4,6,8,12].map(n=><option key={n} value={n}>{n} {n===1?'cycle':'cycles'}</option>)}</select></label></div>
      <label className="sessionAssumptions"><input type="checkbox" checked={assumptions} onChange={e=>setAssumptions(e.target.checked)}/>Allow declared exploratory assumptions where measurements are missing.</label>
      <footer><ModelPicker providers={providers} disabled={busy}/><button className="button button--primary" type="submit" disabled={!project||!ready||busy}><Play size={14}/>{busy?'Starting…':'Start research session'}</button></footer>
      <p>Authorizes model calls and local experiments for this session, bounded by time, cycles, and your usage limits. Pause preserves progress. Resume uses the model selected above. A session can finish before its time budget.</p>
    </form>}
    {error&&<p className="expError" role="alert">{error}</p>}
    <div className="sessionList">{tasks.map(t=>{const state=t.state||t.status;const active=ACTIVE.has(state);const left=remaining(t,now);const fraction=Math.min(100,Math.max(0,100-left/(t.duration_minutes*60||1)*100));return <article className="sessionCard" key={t.id}>
      <header><span className="sessionState"><span className="connectionPill__dot"/>{state?.replaceAll('_',' ')}</span><span className="sessionTimer" title="Time remaining"><Clock3 size={13}/> {time(left)}</span></header>
      <h3 className="sessionObjective">{t.objective}</h3>{t.objective.length>220&&<details><summary>Full objective</summary><p>{t.objective}</p></details>}<div className="sessionMeta"><span>{t.stage||'Preparing'}</span><span>Cycle {t.cycle||0} / {t.max_cycles||cycles}</span><span>{t.model||'Provider default'}</span><span>{t.run_ids?.length||0} runs</span></div>
      <div className="sessionProgress"><i style={{width:`${fraction}%`}}/></div>
      {t.notice&&<p className="sessionNotice">{t.notice}</p>}{t.next_step&&<p className="sessionNotice"><strong>Next step: </strong>{t.next_step}</p>}{t.failure&&<p className="expError">{t.failure}</p>}
      {!!t.children?.length&&<div className="sessionChildren">{t.children.map((child,i)=><div className="sessionChild" key={child.id||i}><Bot size={16}/><div><strong>{child.role||child.name||'Specialist'}</strong><span>{child.state||child.status}</span>{child.error&&<p className="expError">{child.error}</p>}{(child.summary||child.output||child.message)&&<p>{typeof(child.summary||child.output||child.message)==='string'?child.summary||child.output||child.message:JSON.stringify(child.summary||child.output||child.message)}</p>}</div></div>)}</div>}
      {!!t.artifacts?.length&&<details><summary>{t.artifacts.length} saved research artifacts</summary>{t.artifacts.map((a,i)=><div key={a.id||i}><strong>{a.title||a.kind||a.role||'Artifact'}</strong><pre>{a.content||a.summary||JSON.stringify(a,null,2)}</pre></div>)}</details>}
      <footer>{active&&<><button className="button button--secondary" onClick={()=>control(t,'pause')} disabled={busy}><Pause size={13}/>Pause</button><button className="button button--danger" onClick={()=>control(t,'cancel')} disabled={busy}><Square size={13}/>Stop</button></>}{['paused','interrupted','failed','time_limit','needs_input'].includes(state)&&<button className="button button--secondary" onClick={()=>control(t,'resume')} disabled={busy}><RotateCcw size={13}/>Resume</button>}{t.run_ids?.length>0&&<button className="button button--secondary" onClick={()=>onInspectRun?.(t.run_ids.at(-1))}>Inspect latest run<ArrowRight size={13}/></button>}</footer>
    </article>;})}{!tasks.length&&<p className="sessionEmpty">Your sessions, collaborators, and saved progress will appear here.</p>}</div>
  </section>;
}
