import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {BookOpen,Search,ArrowRight,RefreshCw,CheckCircle2,FileText,Upload,Compass} from 'lucide-react';
import {api} from '@/lib/api';
import {latestTask,taskPrompt,sourceURL} from '@/lib/research';
export default function ResearchPlan({project,manifest,refreshKey,busy,onPropose,onExperiment,onAdvanced}){
  const [workspace,setWorkspace]=useState({plans:[],searches:[],tasks:[],data:[]}),[selected,setSelected]=useState('');
  const [query,setQuery]=useState(''),[consent,setConsent]=useState(false),[provenance,setProvenance]=useState('');
  const [working,setWorking]=useState(''),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
  const owner=useRef(project?.id),controller=useRef(null),file=useRef(null);owner.current=project?.id;
  useEffect(()=>{controller.current?.abort();controller.current=new AbortController();setWorkspace({plans:[],searches:[],tasks:[],data:[]});setSelected('');setQuery('');setConsent(false);setWorking('');setError('');setProvenance('');return()=>controller.current?.abort();},[project?.id]);
  useEffect(()=>{if(!project?.id)return;const c=new AbortController();api.researchWorkspace(project.id,c.signal).then(v=>{if(!c.signal.aborted){setWorkspace(v);setSelected(old=>v.plans.some(p=>p.id===old)?old:v.plans[0]?.id||'');}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[project?.id,refreshKey,refresh]);
  const record=workspace.plans.find(p=>p.id===selected)||workspace.plans[0],plan=record?.plan,locked=busy||!!working;
  async function action(name,fn){const id=project?.id;setWorking(name);setError('');try{await fn();}catch(e){if(owner.current===id&&e.name!=='AbortError')setError(e.message);}finally{if(owner.current===id)setWorking('');}}
  const design=()=>action('Designing programme',()=>onPropose(`Create a structured research_plan for this world's full goal: ${project.question}. Identify a tractable question, competing hypotheses, relevant sources/data, measurable acceptance criteria, ordered tasks and the next useful experiment. Missing domain engines should block only the relevant tasks, not all research. Avoid an unrelated toy demonstration or unsupported clinical/scientific claim. Propose only, do not execute.`, 'plan'));
  const prepare=t=>action('Preparing task',()=>onPropose(taskPrompt(plan.goal,t),t.kind==='simulation'?'experiment':'review'));
  const search=e=>{e.preventDefault();if(!project||!consent)return;action('Retrieving abstracts',async()=>{const id=project.id,signal=controller.current.signal;const packet=await api.researchSearch(id,query,consent,signal);if(signal.aborted||owner.current!==id)return;setWorkspace(w=>({...w,searches:[packet.search,...w.searches]}));});};
  const profile=files=>{const f=files?.[0];if(!f||!project)return;action('Profiling CSV',async()=>{if(f.size>1024*1024)throw new Error('Use a scoped deidentified CSV of at most 1 MiB.');const id=project.id,signal=controller.current.signal,content=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await f.arrayBuffer());if(signal.aborted||owner.current!==id)return;const p=await api.researchData(id,{name:f.name,content,provenance},signal);if(signal.aborted||owner.current!==id)return;setWorkspace(w=>({...w,data:[p,...w.data]}));});};
  const saveTask=(t,status,notes)=>action('Saving human assessment',async()=>{const id=project.id,signal=controller.current.signal;const r=await api.researchTask(id,{plan_id:record.id,task_id:t.id,status,notes,evidence_run_ids:[]},signal);if(signal.aborted||owner.current!==id)return;setWorkspace(w=>({...w,tasks:[r.task,...w.tasks]}));});
  if(!project)return <section className="pfResearch"><div className="pfResearchCard"><Compass size={30}/><h2>Start with your research question</h2><p>Create a research world, configure a model key, and turn the goal into an evidence-backed programme.</p></div></section>;
  return <section className="pfResearch"><header className="pfResearchHero"><div><span className="eyebrow">OPTIONAL PROJECT NOTES</span><h2>Notes, sources & research history</h2><p>These notes do not lock your experiment. Build an exploratory model now and return to sources and validation when they are useful.</p></div><BookOpen size={32}/></header><div className="pfResearchActions"><button className="button button--primary" disabled={locked} onClick={()=>action("Building experiment",()=>onExperiment?.(`Investigate ${plan?.tractable_question||project.question}. Build a meaningful supported computational model with explicitly declared assumptions; do not wait for the earlier plan tasks or return another plan.`))}>Build an experiment now</button><button className="button button--secondary" disabled={locked} onClick={design}>{plan?'Replan with current evidence':'Design research programme'}<ArrowRight size={14}/></button><button className="button button--secondary" disabled={locked} onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={14}/>Refresh</button><button type="button" className="button button--secondary" onClick={onAdvanced}>Optional batch / verification tools</button></div>{error&&<p className="pfResearchError" role="alert">{error}</p>}{working&&<p className="pfResearchWorking" role="status">{working}… {['Designing programme','Preparing task','Reviewing evidence'].includes(working)&&'Metered model request; Stop is available in chat and Usage controls.'}</p>}
    <div className="pfResearchGrid"><main>{workspace.plans.length>1&&<label className="pfPlanSelector">Saved immutable plans<select value={record.id} onChange={e=>setSelected(e.target.value)}>{workspace.plans.map(p=><option key={p.id} value={p.id}>{p.plan.title} · {new Date(p.created_at).toLocaleString()}</option>)}</select></label>}
      {!plan?<div className="pfResearchCard"><h3>A missing solver need not end the investigation</h3><p>Design a programme to identify useful evidence, data requirements, model assumptions and executable subquestions. External engines and expert work remain explicit dependencies.</p><small>Designing a programme uses your configured model and existing usage limits. It does not start simulations.</small></div>:<><div className="pfResearchCard"><span className="pfResearchTag">PROPOSED · NOT EXECUTED</span><h3>{plan.title}</h3><p><strong>Ultimate goal:</strong> {plan.goal}</p><h4>What we can investigate next</h4><p>{plan.tractable_question}</p><p>{plan.rationale}</p><div className="pfResearchColumns"><div><h4>Starting knowledge</h4>{plan.knowns.map((s,i)=><p key={i}>{s}</p>)}{!plan.source_ids.length&&<small>No retrieved sources cited. Treat these as provisional assumptions/model knowledge, not a literature review.</small>}</div><div><h4>Open questions</h4>{plan.unknowns.map((s,i)=><p key={i}>{s}</p>)}</div></div>{plan.source_ids.length>0&&<p className="pfSourceIds">Cited retrieved records: {plan.source_ids.join(', ')}</p>}</div><h3 className="pfResearchSectionTitle">Optional research tasks</h3>{plan.tasks.map((t,i)=><TaskCard key={`${record.id}:${t.id}`} task={t} index={i} status={latestTask(workspace.tasks,record.id,t.id)} blocked={t.depends_on.filter(id=>latestTask(workspace.tasks,record.id,id)?.status!=='completed')} disabled={locked} onPrepare={()=>prepare(t)} onQuery={()=>{setQuery(t.search_query);setConsent(false);document.getElementById('pf-public-search')?.scrollIntoView({behavior:'smooth',block:'start'});}} onSave={(status,notes)=>saveTask(t,status,notes)}/>)}<div className="pfResearchCard"><h4>Limits and required validation</h4>{plan.limitations.map((s,i)=><p key={i}>{s}</p>)}<small>Task completion is a human progress record, not certification of novelty, biological activity, clinical efficacy or scientific truth.</small></div></>}
      {manifest&&<div className="pfResearchCard"><h3>Retain a portfolio—not just one winner</h3><p>Source: <strong>{manifest.title}</strong>. Discovery keeps separate attempts, descriptor ranges, trade-offs and multiple finalists. This is optional; a single experiment does not require a batch study.</p><Link className="button button--secondary" href={`/?panel=advanced&project=${project.id}&manifest=${manifest.id}`}>Open optional batch tools <ArrowRight size={14}/></Link></div>}
    </main><aside><form className="pfResearchCard" onSubmit={search} id="pf-public-search"><h3><Search size={17}/>Source evidence</h3><p>Europe PMC metadata and available abstracts. A relevance-ranked search is not an exhaustive review; abstracts are not full papers.</p><label>Focused public query<textarea rows={3} value={query} maxLength={1000} onChange={e=>setQuery(e.target.value)}/></label><label className="pfResearchConsent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Send this query to Europe PMC. Exclude patient information and confidential research.</label><button className="button button--secondary" disabled={locked||!consent||query.trim().length<3}>Retrieve abstracts & metadata</button><small>No model tokens for retrieval. Results and failed queries are retained in this world.</small></form>
      {workspace.searches.some(s=>s.status==='completed'&&s.results.length>0)&&<button className="button button--primary pfSourceReview" disabled={locked} onClick={()=>action('Reviewing evidence',()=>onPropose('Analyze the retrieved abstracts and dataset profiles now. Give findings, disagreements and limitations in assistant_message with action=explain. Use exact retrieved source IDs; do not claim full papers were read or produce another plan.','review'))}>Summarize retrieved evidence</button>}
      {workspace.searches.slice(0,8).map(s=><div className="pfResearchCard pfResearchSources" key={s.id}><h4>{s.query}</h4><small>Europe PMC · {new Date(s.created_at).toLocaleString()} · {s.total_hits??'Unknown'} reported hits</small>{s.status!=='completed'?<p>Retrieval {s.status}: {s.error||'No completed results yet'}. No absence conclusion can be drawn.</p>:!s.results.length?<p>No results for this query. This does not establish novelty or absence of relevant work.</p>:s.results.map(r=><details key={r.id}><summary>{r.title}</summary><p>{r.authors} · {r.year}</p><small>{r.id} · {r.scope}</small><p>{r.abstract_text||'No abstract supplied'}</p>{sourceURL(r.url)&&<a href={sourceURL(r.url)} target="_blank" rel="noreferrer">Open source record</a>}{r.doi&&<p>DOI: {r.doi}</p>}</details>)}</div>)}
      <div className="pfResearchCard"><h3><FileText size={17}/>Inspect local data</h3><p>CSV missingness and numeric summaries—not causal or clinical inference. Raw rows are not retained or sent to the model. Column names and aggregate profiles enter later research context; use deidentified data.</p><label>Provenance, units and permitted use<textarea rows={2} value={provenance} maxLength={2000} onChange={e=>setProvenance(e.target.value)}/></label><input ref={file} type="file" hidden accept=".csv,text/csv" onChange={e=>{profile(e.target.files);e.target.value='';}}/><button className="button button--secondary" disabled={locked} onClick={()=>file.current?.click()}><Upload size={14}/>Profile local CSV</button>{workspace.data.map(d=><details key={d.id}><summary>{d.name} · {d.rows.toLocaleString()} rows</summary><p>{d.provenance}</p><code className="pfHash">SHA-256 {d.sha256}</code><div className="pfProfileTable"><table><thead><tr><th>Column</th><th>Finite</th><th>Missing</th><th>Nonfinite</th><th>Mean</th></tr></thead><tbody>{d.columns.map(c=><tr key={c.name}><td>{c.name}</td><td>{c.finite_numeric}</td><td>{c.missing}</td><td>{c.nonfinite}</td><td>{typeof c.mean==='number'?Number(c.mean.toPrecision(5)):'—'}</td></tr>)}</tbody></table></div><small>{d.scope}</small></details>)}</div>
    </aside></div></section>;
}
function TaskCard({task,index,status,blocked,disabled,onPrepare,onQuery,onSave}){
 const [notes,setNotes]=useState(status?.notes||''),[choice,setChoice]=useState(status?.status||'planned');
 useEffect(()=>{setNotes(status?.notes||'');setChoice(status?.status||'planned');},[status?.id]);
 return <article className="pfResearchCard pfResearchTask"><header><span className="pfResearchStep">{index+1}</span><div><small>{task.kind.replaceAll('_',' ')}</small><h3>{task.title}</h3></div><span className="pfResearchTag">{status?.status||'planned'}</span></header><p>{task.question}</p><p><strong>Method:</strong> {task.method}</p><p><strong>Required inputs:</strong> {task.inputs.join('; ')||'Not specified'}</p><div className="pfTaskCriteria"><strong>Success criterion</strong><p>{task.success_criterion}</p><strong>Expected deliverable</strong><p>{task.deliverable}</p></div>{blocked.length>0&&<p className="pfWarning">Unreviewed inputs: {blocked.join(', ')}. These affect the strength of claims; they do not block an explicitly hypothetical simulation.</p>}<div className="pfResearchActions"><button className="button button--secondary" disabled={disabled} onClick={onPrepare}>{task.kind==='simulation'?'Build this simulation':'Analyze this task'} <ArrowRight size={14}/></button>{task.search_query&&<button className="button button--secondary" disabled={disabled} onClick={onQuery}>Use proposed source query</button>}</div><details><summary>Record progress and evidence notes</summary><label>Status<select value={choice} onChange={e=>setChoice(e.target.value)}>{['planned','in_progress','blocked','completed'].map(s=><option value={s} key={s}>{s.replaceAll('_',' ')}</option>)}</select></label><textarea rows={3} value={notes} maxLength={20000} onChange={e=>setNotes(e.target.value)} placeholder="What was actually done? Which evidence and limitations were reviewed?"/><button className="button button--secondary" disabled={disabled} onClick={()=>onSave(choice,notes)}><CheckCircle2 size={14}/>Save human assessment</button><small>Append-only notes, not an execution gate or a scientific verdict.</small></details></article>;
}
