import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {Box,Search,Download,Play,Square,FileBox,Atom,Image as ImageIcon,Layers,Globe2} from 'lucide-react';
import {api} from '@/lib/api';
import {useModelSelection} from '@/lib/modelSelection';
import {selectStudioRenderInput,loadSavedRenderRequest} from '@/lib/studio-render-input.mjs';
import GenericViewport from './GenericViewport';
import styles from './StudioWorkbench.module.css';
const ScientificModelViewer=dynamic(()=>import('./ScientificModelViewer'),{ssr:false});
const pending=j=>['queued','rendering','running','cancelling'].includes(j?.state||j?.status);
const stateOf=j=>j?.state||j?.status;
const fileUrl=(job,name,type='renders')=>`${api.baseUrl}/api/studio/${type}/${job.id}/artifacts/${encodeURIComponent(name)}`;
function files(job,type){if(type==='renders')return (job.artifacts||[]).map(f=>({name:f.name,url:api.baseUrl+f.url}));return (job.result?.files||[]).map(name=>({name,url:fileUrl(job,name,type)}));}

export default function StudioWorkbench({project,manifest,providers=[],onInspect,onCameraChange}) {
  const {selection,selectionValid,selectionError,selectionProjectId}=useModelSelection();
  const [editorOpen,setEditorOpen]=useState(true);
  const [kind,setKind]=useState('scene'),[prompt,setPrompt]=useState(''),[designs,setDesigns]=useState([]),[design,setDesign]=useState(null);
  const [assets,setAssets]=useState([]),[search,setSearch]=useState(''),[catalog,setCatalog]=useState('rcsb'),[results,setResults]=useState([]),[searchNote,setSearchNote]=useState('');
  const [selectedAssets,setSelectedAssets]=useState([]),[structure,setStructure]=useState(null),[localFile,setLocalFile]=useState(null),[jobs,setJobs]=useState([]),[job,setJob]=useState(null),[jobType,setJobType]=useState('renders');
  const [capabilities,setCapabilities]=useState({}),[cadCapabilities,setCadCapabilities]=useState({}),[style,setStyle]=useState('microscopy'),[resolution,setResolution]=useState(1024),[samples,setSamples]=useState(64),[minutes,setMinutes]=useState(5),[renderView,setRenderView]=useState('model');
  const [busy,setBusy]=useState(''),[error,setError]=useState(''),[note,setNote]=useState('');
  const [assetURL,setAssetURL]=useState(''),[assetModel,setAssetModel]=useState(null),[assetImage,setAssetImage]=useState(null);
  const [visibleAsset,setVisibleAsset]=useState(null),[jobSource,setJobSource]=useState(null);
  const restoreJob=useRef(true);
  const contentEpoch=useRef(0);
  const owner=useRef(project?.id),locked=useRef(false),activeRequest=useRef(null),camera=useRef(null);owner.current=project?.id;
  const id=project?.id;
  const renderSelection=selectStudioRenderInput({projectId:id,job,jobType,jobSource,structure,design,assets,manifest,localFile,assetModel,assetImage,visibleAsset});
  const canFabricate=!!design?.design?.fabrication&&design.project_id===id&&!job&&!visibleAsset&&!structure&&!assetModel&&!assetImage&&!localFile;
  useEffect(()=>{let alive=true;api.studio('studio/capabilities').then(r=>alive&&setCapabilities(r)).catch(()=>{});api.studio('studio/fabrication-engines').then(r=>alive&&setCadCapabilities(r)).catch(()=>{});return()=>{alive=false;};},[]);
  useEffect(()=>{restoreJob.current=true;const epoch=++contentEpoch.current;setVisibleAsset(null);setJobSource(null);setEditorOpen(true);setAssetModel(null);setAssetImage(null);setPrompt('');setAssets([]);setSelectedAssets([]);setStructure(null);setResults([]);setDesign(null);setDesigns([]);setJob(null);setJobs([]);setLocalFile(null);setError('');setNote('');camera.current=null;if(!id)return;let alive=true;
    Promise.allSettled([api.studio(`projects/${id}/assets`),api.studio(`projects/${id}/studio/designs`)]).then(([a,d])=>{if(!alive)return;if(a.status==='fulfilled')setAssets(a.value.assets||[]);if(d.status==='fulfilled'){const rows=Array.isArray(d.value)?d.value:d.value.designs||[];setDesigns(rows);if(rows.length&&contentEpoch.current===epoch){setDesign(rows[0]);setEditorOpen(false);}}});
    return()=>{alive=false;};},[id]);
  useEffect(()=>{if(!id)return;let alive=true,timer;const load=async()=>{try{const [renders,fabs]=await Promise.all([api.studio(`studio/renders?project_id=${id}`),api.studio(`studio/fabrications?project_id=${id}`)]);if(alive){const rows=[...(Array.isArray(renders)?renders:renders.jobs||[]).map(j=>({...j,type:'renders'})),...(Array.isArray(fabs)?fabs:fabs.jobs||[]).map(j=>({...j,type:'fabrications'}))].sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at));setJobs(rows);const restore=restoreJob.current;restoreJob.current=false;if(restore&&rows.length)setEditorOpen(false);setJob(old=>old?rows.find(j=>j.id===old.id)||old:restore?rows[0]||null:null);}}catch(e){if(alive)setError(e.message);}finally{if(alive)timer=setTimeout(load,2500);}};load();return()=>{alive=false;clearTimeout(timer);};},[id]);
  useEffect(()=>{if(job?.type)setJobType(job.type);},[job?.id,job?.type]);
  useEffect(()=>{
    if(!job||job.project_id!==id||(job.type||jobType)!=='renders'||job.settings?.scene||job.settings?.structure_id)return;
    if(jobSource?.jobId===job.id&&jobSource.request)return;
    if(pending(job)){setJobSource({jobId:job.id});return;}
    const controller=new AbortController();let alive=true;const jobId=job.id;
    setJobSource({jobId});
    loadSavedRenderRequest(fileUrl(job,'input.json'),{signal:controller.signal}).then(request=>{if(alive)setJobSource({jobId,request});}).catch(error=>{if(alive)setJobSource({jobId,error:error.message});});
    return()=>{alive=false;controller.abort();};
  },[id,job?.id,job?.type,job?.state,job?.status]);
  function selectContent(){restoreJob.current=false;return ++contentEpoch.current;}
  async function act(label,work){if(locked.current||!id)return;locked.current=true;setBusy(label);setError('');const mine=id;try{await work(mine);}catch(e){if(owner.current===mine)setError(e.message);}finally{locked.current=false;if(owner.current===mine)setBusy('');}}
  async function openAsset(a,mine){const epoch=selectContent();setVisibleAsset(a);setJob(null);setLocalFile(null);setAssetModel(null);setAssetImage(null);setStructure(null);setRenderView('model');
    if(a.molecule_id){const value=await api.molecule(a.molecule_id);if(owner.current===mine&&contentEpoch.current===epoch)setStructure(value.structure||value);}
    else if(['model/gltf-binary','model/stl'].includes(a.mime_type))setAssetModel({name:a.title,url:`${api.baseUrl}/api/assets/${a.id}/content`});
    else if(a.mime_type.startsWith('image/')){setAssetImage({name:a.title,url:`${api.baseUrl}/api/assets/${a.id}/content`});setRenderView('image');}
    else setNote(a.source_description||'Source data imported and available to your research model.');
  }
  async function importAsset(candidate){await act('Importing source',async mine=>{const a=await api.studio(`projects/${mine}/assets/import`,{catalog:candidate.catalog,accession:candidate.accession});if(owner.current!==mine)return;setAssets(v=>[a,...v.filter(x=>x.id!==a.id)]);setSelectedAssets([a.id]);setNote(`Imported ${a.title}. Source and checksum saved.`);await openAsset(a,mine);});}
  async function selectAsset(a){setSelectedAssets(v=>v.includes(a.id)?v.filter(x=>x!==a.id):[...v,a.id].slice(-8));await act('Opening asset',mine=>openAsset(a,mine));}
  async function build(e){e.preventDefault();if(!selectionValid||selectionProjectId!==project?.id){setError(selectionError||'Choose this conversation’s model before building.');return;}await act('Designing with your model',async mine=>{const request_id=crypto.randomUUID();activeRequest.current=request_id;try{const r=await api.studio(`projects/${mine}/studio/design`,{prompt:prompt.trim()||project.question,kind,request_id,...selection,model:selection.model||null,asset_ids:selectedAssets,parent_design_id:design?.design?.kind===kind?design.id:null,failure_report:job?.error||null});if(owner.current!==mine)return;const epoch=selectContent();setVisibleAsset(null);setStructure(null);setAssetModel(null);setAssetImage(null);setDesign(r);setDesigns(v=>[r,...v]);setAssets(v=>[...(r.assets||[]),...v.filter(a=>!(r.assets||[]).some(n=>n.id===a.id))]);setEditorOpen(false);setJob(null);setLocalFile(null);setNote(r.message||'Design saved. Inspect it, then render or fabricate.');const binding=r.design?.asset_bindings?.[0];const bound=r.assets?.find(a=>a.id===binding?.asset_id);if(r.design?.kind==='scene'&&r.design.asset_bindings?.length===1&&bound?.molecule_id&&!binding.node_id){const s=await api.molecule(bound.molecule_id);if(owner.current===mine&&contentEpoch.current===epoch)setStructure(s.structure||s);}else setStructure(null);}finally{activeRequest.current=null;}});}
  async function render(){await act('Submitting render',async mine=>{if(!renderSelection.input)throw Error(renderSelection.error);const body={project_id:mine,style,width:Number(resolution),height:Number(resolution),samples:Number(samples),max_seconds:Number(minutes)*60,max_memory_mb:4096,...renderSelection.input};const r=await api.studio('studio/renders',body);if(owner.current===mine){selectContent();setJobSource({jobId:r.id,request:body});setJob({...r,type:'renders'});setJobType('renders');setRenderView('image');setNote('Rendering locally in Blender. You can keep working while it runs.');}});}
  async function fabricate(){await act('Submitting fabrication',async mine=>{if(!canFabricate)throw Error('Open the original CAD or PCB design from saved history before building engineering files.');const r=await api.studio('studio/fabrications',{project_id:mine,design:design.design.fabrication,max_seconds:Number(minutes)*60});if(owner.current===mine){selectContent();setJob({...r,type:'fabrications'});setJobType('fabrications');setRenderView('model');setNote('Building native engineering files. The saved report will include geometry or board checks.');}});}
  async function stop(){if(activeRequest.current)await api.cancelChatRequest(activeRequest.current);if(job&&pending(job))await api.studio(`studio/${jobType}/${job.id}/cancel`,{});}
  async function openDesign(d){const epoch=selectContent();setVisibleAsset(null);setAssetModel(null);setAssetImage(null);setDesign(d);setKind(d.design.kind);setJob(null);setStructure(null);setLocalFile(null);setRenderView('model');const binding=d.design.asset_bindings?.[0];const asset=assets.find(a=>a.id===binding?.asset_id);if(d.design.kind==='scene'&&d.design.asset_bindings?.length===1&&asset?.molecule_id&&!binding.node_id)await act('Opening design',async mine=>{const value=await api.molecule(asset.molecule_id);if(owner.current===mine&&contentEpoch.current===epoch)setStructure(value.structure||value);});}
  const artifacts=job?files(job,jobType):[],model=artifacts.find(f=>/\.(glb|stl)$/.test(f.name))||assetModel,rendered=artifacts.find(f=>f.name==='render.png')||assetImage;
  const shownScene=renderSelection.scene?{visualization:{scene:renderSelection.scene}}:null;
  if(!project)return <div className={styles.empty}><Box size={36}/><h2>Research, render, build.</h2><p>Create a project to design detailed scientific scenes, CAD solids, or circuit boards.</p></div>;
  return <section className={styles.studio}>
    <header className={styles.heading}><div><span className="eyebrow">SCIENTIFIC STUDIO</span><h2>From research to something real.</h2><p>Detailed structures, rendered scenes and engineering files, in one workspace.</p></div><div className={styles.engines}><span className={capabilities.available?styles.ready:''}>Blender {capabilities.available?'ready':'not installed'}</span><span className={cadCapabilities.cadquery_available?styles.ready:''}>CAD {cadCapabilities.cadquery_available?'ready':'not installed'}</span><span className={cadCapabilities.kicad_available?styles.ready:''}>KiCad {cadCapabilities.kicad_available?'ready':'not installed'}</span></div></header>
    <details className={styles.editor} open={editorOpen} onToggle={e=>setEditorOpen(e.currentTarget.open)}><summary><Box size={15}/>Describe or revise a design<span>{design?.design?.title||'Scenes · CAD · circuit boards'}</span></summary><form className={styles.composer} onSubmit={build}><div className={styles.kind}>{[['scene','3D scene',Box],['cad','CAD / fabrication',FileBox],['pcb','Circuit board',Layers]].map(([value,label,Icon])=><button type="button" key={value} className={kind===value?styles.selected:''} onClick={()=>setKind(value)} disabled={!!busy}><Icon size={15}/>{label}</button>)}</div><textarea aria-label="Studio design request" value={prompt} onChange={e=>setPrompt(e.target.value)} rows={3} maxLength={20000} placeholder={project.question}/><div className={styles.actions}><span title="Model for future work">{selectionProjectId===project?.id?selection.model||'Choose a conversation model':'Loading conversation model…'}{selection.model&&selectionProjectId===project?.id?` · ${selection.reasoning_effort||'Provider default'}`:''}</span><button type="button" className="button button--secondary" onClick={()=>window.dispatchEvent(new Event('phaseforge:focus-chat'))}>Choose in chat</button><button className="button button--primary" disabled={!!busy||!selectionValid||selectionProjectId!==project?.id||!providers.some(p=>p.key_configured||p.configured)} type="submit"><Box size={15}/>{busy||'Build design'}</button>{busy&&<button type="button" className="button button--danger" onClick={()=>stop().catch(e=>setError(e.message))}><Square size={14}/>Stop</button>}</div><small>Research mode retrieves public sources and structures. Building a design saves it for inspection; rendering and fabrication run locally.</small></form></details>
    {error&&<div className={styles.error} role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}{note&&<p className={styles.note} role="status">{note}</p>}
    <details className={styles.sources}><summary><Globe2 size={15}/>Public research & assets <span>{assets.length} saved</span></summary><div className={styles.search}><input aria-label="Public data or CAD URL" type="url" value={assetURL} onChange={e=>setAssetURL(e.target.value)} placeholder="Direct HTTPS data / GLB / STL URL from a supported scientific archive"/><button type="button" className="button button--secondary" disabled={!!busy||!assetURL.trim()} onClick={()=>importAsset({catalog:'public_file',accession:assetURL.trim()})}>Import URL</button></div><small>Supported archives: RCSB, EMBL-EBI, ESO, Zenodo and raw GitHub files. Imported content remains data.</small><div className={styles.search}><select aria-label="Public asset catalog" value={catalog} onChange={e=>setCatalog(e.target.value)}><option value="rcsb">Molecular structures · RCSB</option><option value="nasa">Space imagery · NASA</option><option value="literature">Scientific literature</option></select><input aria-label="Search public research" value={search} onChange={e=>setSearch(e.target.value)} placeholder="HIV envelope, Sagittarius A*, microscopy…"/><button type="button" className="button button--secondary" disabled={!!busy||!search.trim()} onClick={()=>act('Searching public research',async mine=>{const r=await api.studio(`projects/${mine}/assets/search`,{catalog,query:search,limit:5});if(owner.current===mine){setResults(r.results||[]);setSearchNote(r.error||`${r.results?.length||0} results from ${catalog.toUpperCase()}`);}})}><Search size={14}/>Search</button></div>{searchNote&&<p>{searchNote}</p>}<div className={styles.assetGrid}>{results.map(a=><article key={`${a.catalog}:${a.accession}`}><strong>{a.title}</strong><p>{a.description}</p><a href={a.source_url} target="_blank" rel="noreferrer">Open source</a>{a.catalog!=='literature'&&<button className="button button--secondary" disabled={!!busy} onClick={()=>importAsset(a)}>Import {a.accession}</button>}</article>)}</div>{assets.length>0&&<><h3>Saved sources</h3><div className={styles.assetGrid}>{assets.map(a=><article key={a.id} className={selectedAssets.includes(a.id)?styles.assetSelected:''}><button type="button" className={styles.assetPick} onClick={()=>selectAsset(a)} disabled={!!busy}>{a.molecule_id?<Atom size={18}/>:<ImageIcon size={18}/>}<strong>{a.title}</strong><span>{selectedAssets.includes(a.id)?'Selected':'Select'}</span></button><small>{a.provenance}</small><a href={`${api.baseUrl}/api/assets/${a.id}/content`} download>Download source file</a><a href={a.source_url} target="_blank" rel="noreferrer">{a.catalog.toUpperCase()} · {a.accession}</a></article>)}</div></>}</details>
    <div className={styles.renderTools}><label>Lighting<select value={style} onChange={e=>setStyle(e.target.value)}><option value="microscopy">Microscopy surface</option><option value="studio">Scientific studio</option></select></label><label>Resolution<select value={resolution} onChange={e=>setResolution(Number(e.target.value))}><option value={512}>512 px</option><option value={1024}>1024 px</option><option value={2048}>2048 px</option></select></label><label>Samples<select value={samples} onChange={e=>setSamples(Number(e.target.value))}><option value={32}>32 · preview</option><option value={64}>64 · detailed</option><option value={128}>128 · refined</option><option value={256}>256 · final</option></select></label><label>Time limit (min)<input type="number" min={1} max={30} value={minutes} onChange={e=>setMinutes(Math.max(1,Math.min(30,Number(e.target.value))))}/></label><div className={styles.actions}><button className="button button--primary" disabled={!!busy||!capabilities.available||!renderSelection.input} title={renderSelection.error||'Render the selected source'} onClick={render}><Play size={14}/>Render in Blender</button>{canFabricate&&<button className="button button--primary" disabled={!!busy} onClick={fabricate}><FileBox size={14}/>Build engineering files</button>}{pending(job)&&<button className="button button--danger" onClick={()=>stop().catch(e=>setError(e.message))}>Cancel job</button>}</div></div>
    {!renderSelection.input&&<p className={styles.note} role="status">{renderSelection.error}</p>}
    {job&&<div className={styles.jobStatus}><strong>{jobType==='renders'?'Blender render':'Fabrication'} · {stateOf(job)}</strong><span>{job.error||job.message||job.result?.notice||'Saved job'}</span>{job.result?.volume_mm3!=null&&<span>{job.result.solid_count} solid(s) · {job.result.volume_mm3.toFixed(2)} mm³</span>}{job.result?.drc_status&&<span>DRC: {job.result.drc_status} · {job.result.drc_issue_count??'—'} issues</span>}</div>}
    <div className={styles.viewTabs}><button type="button" className={renderView==='model'?styles.selected:''} onClick={()=>setRenderView('model')}>Interactive model</button><button type="button" className={renderView==='image'?styles.selected:''} disabled={!rendered} onClick={()=>setRenderView('image')}>Cycles render</button><label className={styles.import}>Open GLB / STL<input type="file" accept=".glb,.stl" onChange={e=>{if(e.target.files?.[0]){selectContent();setVisibleAsset(null);setLocalFile(e.target.files[0]);setAssetModel(null);setAssetImage(null);setJob(null);setStructure(null);setRenderView('model');}}}/></label></div>
    <div className={styles.viewport}>{renderView==='image'&&rendered?<img src={rendered.url} alt={assetImage?.name||'Blender Cycles render of the selected scientific model'}/>:model||structure||localFile?<ScientificModelViewer title={job?(renderSelection.scene?.title||job.renderer?.source?.name||'Saved render'):(structure?.name||assetModel?.name||design?.design?.title)} url={localFile?undefined:model?.url} file={localFile} structure={localFile||model?undefined:structure} style={style} onInspect={onInspect} onCameraChange={c=>{camera.current=c;onCameraChange?.(c);}} provenance={structure?{kind:'measured_coordinates',description:'Surface reconstructed from imported atomic coordinates. This is not an electron microscope measurement.'}:undefined}/>:shownScene?<GenericViewport manifest={shownScene} onInspect={onInspect} onCameraChange={onCameraChange}/>:<div className={styles.empty}><Box size={35}/><h3>Build a scene or import measured structure.</h3><p>Use public research to find molecular coordinates, or describe a custom scene, part, or circuit board above.</p></div>}</div>
    {!!artifacts.length&&<div className={styles.downloads}>{artifacts.map(f=><a key={f.name} href={f.url} download={f.name}><Download size={14}/>{f.name}</a>)}</div>}
    {(designs.length>0||jobs.length>0)&&<details className={styles.history}><summary>Saved designs & jobs</summary>{designs.map(d=><button type="button" key={d.id} onClick={()=>openDesign(d).catch(e=>setError(e.message))}><Box size={14}/>{d.design.title}</button>)}{jobs.map(j=><button key={j.id} type="button" onClick={()=>{selectContent();setVisibleAsset(null);setAssetModel(null);setAssetImage(null);setStructure(null);setJob(j);setJobType(j.type);setLocalFile(null);setRenderView('model');}}>{j.type==='renders'?'Render':'Fabrication'} · {stateOf(j)} · {new Date(j.created_at).toLocaleString()}</button>)}</details>}
  </section>;
}
