//! Native regression tests. These execute in cargo test / CI, not in a source-text audit.
use super::{comparison as cmp,service::*,types::*};
use crate::{discovery::{types::*,math},domain::*,persistence::Database};
use chrono::Utc;
use serde_json::json;
use std::collections::BTreeMap;
use uuid::Uuid;

fn fixture()->(Database,Study,RunRecord){
    let db=Database::open(std::path::Path::new(":memory:")).unwrap();
    let project=ResearchProject::new(CreateProjectRequest{name:Some("Verification contract".into()),question:"Test a bounded independent verification contract".into()});db.put_project(&project).unwrap();
    let draft:ExperimentManifestDraft=serde_json::from_str(include_str!("../../tests/fixtures/discovery-control.json")).unwrap();
    let manifest=ExperimentManifest::from_draft(project.id,None,1,draft,"test only");db.put_manifest(&manifest).unwrap();
    let mut run=RunRecord::queued(RunRequest{manifest_id:manifest.id,name:None,priority:RunPriority::Interactive,compute:None},&manifest);
    run.status=RunStatus::Completed;run.result=Some(json!({"metrics":{"state":0.3678794412},"constraint_results":[],"numerical":{"reached_end_time":true}}));db.put_run(&run).unwrap();
    let now=Utc::now();let mut study=Study{id:Uuid::new_v4(),project_id:project.id,recipe:StudyRecipe{title:"Verification test".into(),hypothesis:"No claim about nature".into(),base_manifest_id:manifest.id,strategy:Strategy::NoveltySearch,
        parameters:vec![SearchVariableSpec{name:"x0".into(),target:"initial:x".into(),minimum:0.,maximum:2.}],objectives:vec![MetricGoal{metric:"state".into(),goal:ObjectiveGoal::Minimize}],
        descriptors:vec![Descriptor{metric:"state".into(),minimum:0.,maximum:1.,bins:8}],exploration_trials:4,validation_finalists:1,wall_seconds:60,per_trial_seconds:10,seed:13,absolute_tolerance:1e-6,relative_tolerance:1e-4,auto_review:false},
        recipe_hash:"test-recipe-digest".into(),base_manifest:manifest,state:"completed".into(),stage:"done".into(),trials:vec![],finalist_ids:vec![],finalists_frozen:true,elapsed_seconds:1.,review_count:0,events:vec![],created_at:now,updated_at:now};
    let t=Trial{id:Uuid::new_v4(),index:1,phase:"explore".into(),parent_trial_id:None,manifest_id:Some(run.manifest_id),run_id:Some(run.id),values:vec![1.],state:"completed".into(),metrics:BTreeMap::from([("state".into(),0.3678794412)]),eligible:true,reasons:vec![],cell:Some("2".into()),created_at:now};
    study.finalist_ids.push(t.id);study.trials.push(t);db.put_study(&study).unwrap();(db,study,run)
}
fn rule()->MetricRule{MetricRule{metric:"state".into(),scale:1.,absolute_tolerance:1e-6,relative_tolerance:1e-4,robustness_absolute:0.1}}
fn protocol(s:&Study)->VerificationRequest{VerificationRequest{study_id:s.id,trial_id:s.trials[0].id,question:"Does this selected candidate reproduce under independent integration?".into(),metrics:vec![rule()],holdout_replicates:4,perturb_fraction:0.01,holdout_seed:104742,wall_seconds:30,max_rhs_evaluations:100000,solver_absolute_tolerance:1e-10,solver_relative_tolerance:1e-8,duplicate_distance:0.01,controls:vec![],reference_ids:vec![]}}
fn reference(s:&Study)->CatalogImport{CatalogImport{study_id:s.id,metric_rules:vec![rule()],title:"Documented reference fixture".into(),source:"A test-only explicit numerical reference".into(),license:"Test data permission".into(),run_id:None,measurements:BTreeMap::from([("state".into(),0.1)])}}
fn review()->ReviewRequest{ReviewRequest{reviewer:"Named test reviewer".into(),disposition:"potentially_distinct".into(),comparison_notes:"Compared the complete test-only source, numerical protocol and reported observable.".into(),limitations:"A test is not evidence of scientific novelty.".into(),examined_sources:vec!["Test-only source identifier".into()],full_text_reviewed:true}}

#[test]fn frozen_dossier_never_auto_executes(){let(db,s,_)=fixture();let svc=AssuranceService::new(db).unwrap();let d=svc.create(protocol(&s)).unwrap();assert_eq!(d.state,"draft");assert_eq!(d.completed_tasks,0);assert!(d.result.is_none());}
#[test]fn input_run_snapshots_are_exact(){let(db,s,run)=fixture();let svc=AssuranceService::new(db).unwrap();let d=svc.create(protocol(&s)).unwrap();assert_eq!(d.source_run_hash,cmp::hash(&run).unwrap());assert_eq!(d.worker_source_hash,cmp::text_hash(WORKER));assert_eq!(d.source_run.id,run.id);}
#[test]fn stale_or_unmeasured_candidate_rejected(){let(db,mut s,_)=fixture();s.trials[0].eligible=false;db.put_study(&s).unwrap();assert!(AssuranceService::new(db).unwrap().create(protocol(&s)).is_err());}
#[test]fn new_seed_required(){let(db,s,_)=fixture();let mut p=protocol(&s);p.holdout_seed=s.recipe.seed;assert!(AssuranceService::new(db).unwrap().create(p).is_err());}
#[test]fn same_model_parameter_is_masked_but_equations_are_not(){let(_,s,_)=fixture();let original=cmp::space(&s,&[rule()]).unwrap();let mut changed=s.clone();math::set_parameter(&mut changed.base_manifest,"initial:x",0.5).unwrap();assert_eq!(original,cmp::space(&changed,&[rule()]).unwrap());if let ModelSpec::StateVectorOde{derivatives,..}=&mut changed.base_manifest.model{derivatives[0].expression="x".into();}assert_ne!(original,cmp::space(&changed,&[rule()]).unwrap());}
#[test]fn feature_scales_define_comparison_namespace(){let(_,s,_)=fixture();let a=cmp::space(&s,&[rule()]).unwrap();let mut r=rule();r.scale=2.;assert_ne!(a,cmp::space(&s,&[r]).unwrap());}
#[test]fn missing_features_have_no_distance(){let a=BTreeMap::from([("state".into(),1.)]);assert!(cmp::distance(&a,&BTreeMap::new(),&[rule()]).is_none());}
#[test]fn near_zero_distance_uses_explicit_scale(){let a=BTreeMap::from([("state".into(),0.)]);let b=BTreeMap::from([("state".into(),1e-8)]);assert_eq!(cmp::distance(&a,&b,&[rule()]),Some(1e-8));}
#[test]fn invalid_metric_rules_rejected(){for scale in [0.,-1.,f64::INFINITY]{let mut r=rule();r.scale=scale;assert!(cmp::validate_rules(&[r]).is_err());}assert!(cmp::validate_rules(&[rule(),rule()]).is_err());}
#[test]fn absent_reference_corpus_not_novel(){let(db,s,_)=fixture();let svc=AssuranceService::new(db).unwrap();let d=svc.create(protocol(&s)).unwrap();let a=svc.assessment(&d).unwrap();assert_eq!(a["catalog"]["status"],"no_comparable_reference");assert_eq!(a["novelty"],"not_certified");}
#[test]fn near_match_is_retained(){let(db,s,run)=fixture();let svc=AssuranceService::new(db).unwrap();let mut input=reference(&s);input.measurements.insert("state".into(),0.3678794412);let entry=svc.import_reference(input).unwrap();let mut p=protocol(&s);p.reference_ids.push(entry.id);let d=svc.create(p).unwrap();assert_eq!(cmp::catalog_report(&d)["status"],"near_match");assert_eq!(d.source_run.id,run.id);}
#[test]fn own_candidate_does_not_count_as_known_reference(){let(db,s,run)=fixture();let svc=AssuranceService::new(db).unwrap();let mut input=reference(&s);input.run_id=Some(run.id);let entry=svc.import_reference(input).unwrap();let mut p=protocol(&s);p.reference_ids.push(entry.id);let d=svc.create(p).unwrap();assert_eq!(cmp::catalog_report(&d)["compared"],0);}
#[test]fn imported_features_require_all_selected_measurements(){let(db,s,_)=fixture();let svc=AssuranceService::new(db).unwrap();let mut input=reference(&s);input.measurements.clear();assert!(svc.import_reference(input).is_err());}
#[test]fn freezing_source_metadata_changes_protocol_hash(){let(db,s,_)=fixture();let svc=AssuranceService::new(db).unwrap();let a=svc.create(protocol(&s)).unwrap();let reference=svc.import_reference(reference(&s)).unwrap();let mut p=protocol(&s);p.reference_ids.push(reference.id);let b=svc.create(p).unwrap();assert_ne!(a.protocol_hash,b.protocol_hash);}
#[test]fn wrong_project_reference_rejected(){let(db,s,_)=fixture();let svc=AssuranceService::new(db.clone()).unwrap();let mut entry=svc.import_reference(reference(&s)).unwrap();entry.project_id=Uuid::new_v4();db.put_catalog_entry(&entry).unwrap();let mut p=protocol(&s);p.reference_ids.push(entry.id);assert!(svc.create(p).is_err());}
#[test]fn current_review_stales_after_new_search_record(){let(db,s,_)=fixture();let svc=AssuranceService::new(db.clone()).unwrap();let d=svc.create(protocol(&s)).unwrap();let r=svc.save_review(d.id,review()).unwrap();assert_eq!(svc.assessment(&d).unwrap()["evidence_hash"],r.evidence_hash);db.put_literature_search(&SearchRecord{id:Uuid::new_v4(),dossier_id:d.id,query:"fixture query".into(),provider:"Crossref".into(),status:"failed".into(),error:Some("offline test".into()),references:vec![],retrieved_at:Utc::now(),scope:"metadata only".into()}).unwrap();assert_ne!(svc.assessment(&d).unwrap()["evidence_hash"],r.evidence_hash);}
#[test]fn human_inconclusive_disposition_is_not_promotion(){let(db,s,_)=fixture();let svc=AssuranceService::new(db).unwrap();let d=svc.create(protocol(&s)).unwrap();let mut r=review();r.disposition="inconclusive".into();svc.save_review(d.id,r).unwrap();let a=svc.assessment(&d).unwrap();assert!(a["gaps"].as_array().unwrap().iter().any(|v|v.as_str().unwrap().contains("current human review")));}
#[test]fn restart_marks_interrupted_never_resumes(){let(db,s,_)=fixture();let svc=AssuranceService::new(db.clone()).unwrap();let mut d=svc.create(protocol(&s)).unwrap();d.state="running".into();db.put_dossier(&d).unwrap();let next=AssuranceService::new(db).unwrap();assert_eq!(next.get(d.id).unwrap().state,"interrupted");}
#[test]fn cascade_deletes_owned_new_records(){let(db,s,_)=fixture();let svc=AssuranceService::new(db.clone()).unwrap();let d=svc.create(protocol(&s)).unwrap();let r=svc.import_reference(reference(&s)).unwrap();svc.save_review(d.id,review()).unwrap();db.delete_project(s.project_id).unwrap();assert!(db.get_dossier(d.id).unwrap().is_none());assert!(db.get_catalog_entry(r.id).unwrap().is_none());assert!(db.list_verification_reviews(d.id).unwrap().is_empty());}
#[test]fn no_controls_does_not_get_a_green_control_flag(){let(db,s,_)=fixture();let svc=AssuranceService::new(db).unwrap();let d=svc.create(protocol(&s)).unwrap();assert!(svc.assessment(&d).unwrap()["gaps"].as_array().unwrap().iter().any(|v|v.as_str().unwrap().contains("No known calibration")));}
