import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {api} from "@/lib/api";
import {fmt,eligiblePoints} from "@/lib/discovery";
import {useLiveRuntime} from "@/lib/liveRuntime";

export default function StudyResults({detail,onRecord}){
  const {study:s,summary}=detail;const [selected,setSelected]=useState(null),[page,setPage]=useState(0),[signals,setSignals]=useState(null),[signalError,setSignalError]=useState("");
  const {workflow}=useLiveRuntime();const live=s.trials.find(t=>["queued","running"].includes(t.state));
  const active=workflow?.runs?.find(r=>r.id===live?.run_id);
  useEffect(()=>{setSelected(null);setPage(0);setSignals(null);},[s.id]);
  const trial=s.trials.find(t=>t.id===selected)||null;
  useEffect(()=>{setSignals(null);setSignalError("");if(!trial?.run_id||trial.state!=="completed")return;const c=new AbortController();api.signals(trial.run_id,c.signal).then(setSignals).catch(e=>{if(e.name!=="AbortError")setSignalError(e.message);});return()=>c.abort();},[trial?.run_id,trial?.state]);
  const progress=summary.planned?Math.min(100,100*summary.completed/summary.planned):0;
  const pages=Math.max(1,Math.ceil(s.trials.length/20));const visible=s.trials.slice(page*20,(page+1)*20);
  return <>
    <div className="discProgress" aria-label="Campaign progress"><div><strong>{s.stage}</strong><span>{summary.completed} / {summary.planned} planned trials · {Math.round(s.elapsed_seconds)} / {s.recipe.wall_seconds} s consumed</span></div><progress value={progress} max={100}/>{live&&<small>Trial {live.index} · {active?.phase||live.state} {active?.progress!=null?`${Math.round(active.progress*100)}%`:""}. Numerical progress is measured; remote model completion time is not predicted.</small>}</div>
    <div className="discStats"><Stat name="Feasible observations" value={summary.eligible}/><Stat name="Rejected / failed" value={summary.rejected}/><Stat name="Archive cells filled" value={summary.archive.length}/><Stat name="Descriptor-space coverage" value={summary.coverage==null?"Not configured":`${(100*summary.coverage).toFixed(1)}%`}/><Stat name="Non-dominated candidates" value={summary.pareto_trial_ids.length}/></div>
    <div className="discNotice">These are numerical candidates within one authored model. Coverage is occupancy of your chosen bins, not a percentage of possible science explored. Feasibility is not validation. Neither “completed” nor “Pareto” means a new scientific discovery.</div>
    <div className="discPlots"><BehaviorMap study={s} summary={summary} selected={selected} onSelect={setSelected}/><QualityPlot study={s} summary={summary} selected={selected} onSelect={setSelected}/></div>
    {!!summary.validation.length&&<section className="discoveryCard"><h3>Finalist resolution challenges</h3><p className="discCaption">Each finalist uses identical parameters and seed at h, h/2 and h/4. This tests numerical agreement, not statistical replication or physical stability.</p>{summary.validation.map(v=><div className="discValidation" key={v.trial_id}><header><strong>Finalist {s.trials.find(t=>t.id===v.trial_id)?.index}</strong><span className={`discBadge discBadge--${v.status}`}>{v.status}</span></header><div className="discTableScroll"><table><thead><tr><th>Metric</th><th>h</th><th>h/2</th><th>h/4</th><th>h/2 ↔ h/4</th><th>Threshold</th></tr></thead><tbody>{v.checks.map(c=><tr key={c.metric}><td>{c.metric}</td><td>{fmt(c.baseline)}</td><td>{fmt(c.half_step)}</td><td>{fmt(c.quarter_step)}</td><td>{fmt(c.half_quarter_difference)}</td><td>{fmt(c.threshold)}</td></tr>)}</tbody></table></div></div>)}</section>}
    <section className="discoveryCard"><header><div><h3>Every attempted trial</h3><p>Failures stay visible. Select a row to inspect evidence and signal diagnostics.</p></div><div className="discActions"><button className="button button--secondary" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><small>{page+1} / {pages}</small><button className="button button--secondary" disabled={page+1>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></header>
    <div className="discTableScroll"><table><thead><tr><th>Trial</th><th>Stage</th><th>State</th><th>Feasible</th>{s.recipe.objectives.map(g=><th key={g.metric}>{g.metric}</th>)}<th>Archive cell</th></tr></thead><tbody>{visible.map(t=><tr key={t.id} className={selected===t.id?"selected":""}><td><button className="discTextButton" onClick={()=>setSelected(t.id)}>#{t.index}</button></td><td>{t.phase.replaceAll("_"," ")}</td><td>{t.state}</td><td>{t.eligible?"Yes":"Not established"}</td>{s.recipe.objectives.map(g=><td key={g.metric}>{fmt(t.metrics[g.metric])}</td>)}<td>{t.cell||"Outside bins / none"}</td></tr>)}</tbody></table>{!s.trials.length&&<p className="discEmpty">Approve and start this frozen protocol to collect real observations.</p>}</div></section>
    {trial&&<section className="discoveryCard discInspector"><header><div><span className="eyebrow">TRIAL {trial.index} · {trial.id}</span><h3>What this candidate actually contains</h3></div><div className="discActions">{trial.run_id&&<Link className="button button--secondary" href={`/?run=${trial.run_id}`}>Open in Findings</Link>}<button className="button button--secondary" onClick={onRecord}>Record a claim</button></div></header><div className="discFields"><div><h4>Parameters</h4>{s.recipe.parameters.map((p,i)=><p className="discKeyValue" key={p.target}><code>{p.target}</code><strong>{fmt(trial.values[i])}</strong></p>)}</div><div><h4>Eligibility / rejection record</h4>{trial.reasons.length?trial.reasons.map((r,i)=><p className="discWarning" key={i}>{r}</p>):<p>Finite target metrics, completed interval, and reported baseline constraints. Broader validity is still unresolved.</p>}<small>Run: {trial.run_id||"No run submitted"}</small></div></div>
      <h4>Signal diagnostics from recorded samples</h4><p className="discCaption">Calculated from retained samples; no vision model or extra paid call.</p>{signalError&&<p className="discError">{signalError}</p>}{signals&&<><p className="discNotice">{signals.boundary}</p><div className="discTableScroll"><table><thead><tr><th>Series</th><th>Samples</th><th>Mean</th><th>Standard deviation</th><th>Turning points</th><th>Frequency hint</th></tr></thead><tbody>{signals.series.map(row=><tr key={row.name}><td>{row.name}</td><td>{row.samples||"—"}</td><td>{fmt(row.mean)}</td><td>{fmt(row.standard_deviation)}</td><td>{row.turning_points??"—"}</td><td>{fmt(row.dominant_frequency_hint?.frequency)}</td></tr>)}</tbody></table></div></>}
    </section>}
    <details className="discoveryCard discTimeline"><summary>Protocol and decision history · {s.events.length} events</summary><p className="discCaption">Recipe hash {s.recipe_hash}. The original protocol is retained; a new research direction requires a new study.</p>{s.events.slice().reverse().map((e,i)=><div key={i}><time>{new Date(e.at).toLocaleString()}</time><strong>{e.kind}</strong><p>{e.message}</p></div>)}</details>
  </>;
}
function Stat({name,value}){return <article><span>{name}</span><strong>{value}</strong></article>;}
function BehaviorMap({study:s,summary,selected,onSelect}){
  const axes=s.recipe.descriptors;if(!axes.length)return <section className="discoveryCard discPlot"><h3>Behavioral diversity map</h3><p>No descriptor axes were declared. Create a MAP-Elites study with measured behavioral metrics to illuminate distinct regions rather than only rank scores.</p></section>;
  const nx=axes[0].bins,ny=axes[1]?.bins||1,bycell=new Map(summary.archive.map(a=>[a.cell,a.trial_id]));
  return <section className="discoveryCard discPlot"><h3>Behavioral diversity map</h3><p>{axes.map(a=>`${a.metric} [${fmt(a.minimum)}, ${fmt(a.maximum)}]`).join(" × ")}</p><svg role="img" aria-label="Behavioral archive occupancy" viewBox="0 0 600 290"><text x="55" y="275">{axes[0].metric} →</text>{Array.from({length:nx*ny},(_,i)=>{const x=i%nx,y=Math.floor(i/nx),key=axes.length>1?`${x}:${y}`:`${x}`,id=bycell.get(key);return <rect key={key} x={50+x*530/nx} y={15+(ny-y-1)*220/ny} width={530/nx-1} height={220/ny-1} className={id?`occupied ${id===selected?"selected":""}`:"empty"} tabIndex={id?0:-1} role={id?"button":undefined} aria-label={id?`Inspect occupied cell ${key}`:undefined} onClick={()=>id&&onSelect(id)} onKeyDown={e=>{if(id&&(e.key==="Enter"||e.key===" ")){e.preventDefault();onSelect(id);}}}><title>{key}: {id?"one elite retained":"unoccupied"}</title></rect>;})}</svg><small>Click an occupied cell to inspect its elite. Out-of-range observations remain in the table, not silently clamped into edge bins.</small></section>;
}
function QualityPlot({study:s,summary,selected,onSelect}){
  const points=eligiblePoints(s),g=s.recipe.objectives[0],h=s.recipe.objectives[1];
  const data=points.map(t=>({t,x:h?t.metrics[g.metric]:t.index,y:h?t.metrics[h.metric]:t.metrics[g.metric]})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));
  const xmin=Math.min(...data.map(p=>p.x)),xmax=Math.max(...data.map(p=>p.x)),ymin=Math.min(...data.map(p=>p.y)),ymax=Math.max(...data.map(p=>p.y));const front=new Set(summary.pareto_trial_ids);
  return <section className="discoveryCard discPlot"><h3>{h?"Measured Pareto trade-offs":"Exploration quality"}</h3><p>{h?`${g.metric} (${g.goal}) × ${h.metric} (${h.goal})`:`${g.metric} (${g.goal}) by trial index`}</p>{!data.length?<p className="discEmpty">No feasible measured candidates yet.</p>:<svg role="img" aria-label="Measured candidate scores" viewBox="0 0 600 290"><path d="M65 20V235H580" className="axes"/><text x="65" y="263">{fmt(xmin)}</text><text x="500" y="263">{fmt(xmax)}</text><text x="2" y="32">{fmt(ymax)}</text><text x="2" y="235">{fmt(ymin)}</text>{data.map(p=><circle key={p.t.id} cx={65+500*(p.x-xmin)/Math.max(Number.EPSILON,xmax-xmin)} cy={235-205*(p.y-ymin)/Math.max(Number.EPSILON,ymax-ymin)} r={p.t.id===selected?7:4} className={`candidate ${front.has(p.t.id)?"front":""}`} tabIndex={0} role="button" aria-label={`Inspect trial ${p.t.index}`} onClick={()=>onSelect(p.t.id)} onKeyDown={e=>{if(e.key==="Enter")onSelect(p.t.id);}}><title>Trial {p.t.index}: {fmt(p.x)}, {fmt(p.y)}</title></circle>)}</svg>}<small>All feasible exploration points shown. Outlined points are non-dominated among recorded candidates, not globally optimal or scientifically novel.</small></section>;
}
