import {allMetrics} from "@/lib/research";
import {useMemo,useState} from "react";
import {Plus,Trash2,ShieldCheck} from "lucide-react";
import {api} from "@/lib/api";
import {initialRecipe,targets,validateRecipe,suggestedParameter} from "@/lib/discovery";

export default function StudyBuilder({manifest,onCreated,onCancel}) {
  const [r,setR]=useState(()=>initialRecipe(manifest));const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [approved,setApproved]=useState(false);
  const options=useMemo(()=>targets(manifest),[manifest]);const metrics=useMemo(()=>[...allMetrics(manifest).map(o=>({name:o.name,unit:o.unit})),...(manifest.model?.variables||[]).map(v=>({name:`final_${v.name}`,unit:v.unit}))],[manifest]);
  const patch=(key,value)=>{setApproved(false);setR(old=>({...old,[key]:value}));};
  const edit=(key,index,field,value)=>patch(key,r[key].map((row,i)=>i===index?{...row,[field]:value}:row));
  const create=async()=>{const problem=validateRecipe(r);if(problem){setError(problem);return;}setBusy(true);try{const result=await api.createStudy(r);onCreated(result.study);}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <section className="discoveryBuilder discoveryCard">
    <header><div><span className="eyebrow">PROTOCOL · FROZEN BEFORE COMPUTE</span><h2>Define what is worth exploring</h2><p>Use this to test a space of possibilities, not to generate a story around a single good-looking result.</p></div><button className="button button--secondary" onClick={onCancel}>Close</button></header>
    <div className="discFields"><label>Study name<input value={r.title} onChange={e=>patch("title",e.target.value)}/></label><label>Search strategy<select value={r.strategy} onChange={e=>patch("strategy",e.target.value)}><option value="latin_hypercube">Latin hypercube · broad stratified coverage</option><option value="map_elites">MAP-Elites · adaptive behavioral diversity</option><option value="novelty_search">Novelty search · pursue sparse measured behaviors</option></select></label></div>
    <label>Hypothesis and discriminatory purpose<textarea rows={3} value={r.hypothesis} onChange={e=>patch("hypothesis",e.target.value)}/></label>
    <h3>1. What may change?</h3><p className="discCaption">Bounds from the source manifest are retained when available. Added bounds are suggestions, not scientifically justified defaults. Review physical units and feasibility.</p>
    {r.parameters.map((p,i)=><div className="discParameter" key={i}><label>Target<select value={p.target} onChange={e=>edit("parameters",i,"target",e.target.value)}>{!options.some(o=>o.target===p.target)&&<option value={p.target}>{p.target}</option>}{options.map(o=><option value={o.target} key={o.target}>{o.label}</option>)}</select></label><label>Minimum<input type="number" step="any" value={p.minimum} onChange={e=>edit("parameters",i,"minimum",e.target.valueAsNumber)}/></label><label>Maximum<input type="number" step="any" value={p.maximum} onChange={e=>edit("parameters",i,"maximum",e.target.valueAsNumber)}/></label><button aria-label="Remove parameter" className="discIcon" onClick={()=>patch("parameters",r.parameters.filter((_,j)=>i!==j))}><Trash2 size={16}/></button></div>)}
    <button type="button" className="button button--secondary" disabled={!options.length||r.parameters.length>=12} onClick={()=>{const option=options.find(o=>!r.parameters.some(p=>p.target===o.target));if(option)patch("parameters",[...r.parameters,suggestedParameter(option,r.parameters.length)]);}}><Plus size={14}/>Add parameter</button>
    <h3>2. What is valuable, and what is different?</h3><p className="discCaption">Novelty search keeps a quality control and behaviorally separated finalists; 30% of post-warmup proposals retain broad exploration. Its score is local descriptor sparsity, not novelty to science. In the other strategies, the first metric ranks elites. Additional metrics expose Pareto trade-offs; they are not silently collapsed into one score. Behavioral bins distinguish outcomes within this study, not novelty to science.</p>
    <datalist id="study-metrics">{metrics.map(m=><option key={m.name} value={m.name}>{m.unit||"model units"}</option>)}</datalist>
    {r.objectives.map((g,i)=><div className="discParameter" key={i}><label>{i===0?"Primary ranking metric":"Additional Pareto metric"}<input list="study-metrics" value={g.metric} onChange={e=>edit("objectives",i,"metric",e.target.value)}/></label><label>Direction<select value={g.goal} onChange={e=>edit("objectives",i,"goal",e.target.value)}><option value="minimize">Minimize</option><option value="maximize">Maximize</option></select></label><button className="discIcon" aria-label="Remove objective" onClick={()=>patch("objectives",r.objectives.filter((_,j)=>i!==j))}><Trash2 size={16}/></button></div>)}
    <button className="button button--secondary" disabled={r.objectives.length>=3} onClick={()=>patch("objectives",[...r.objectives,{metric:metrics[r.objectives.length]?.name||"",goal:"minimize"}])}><Plus size={14}/>Add metric</button>
    {r.descriptors.map((d,i)=><div className="discDescriptor" key={i}><label>Behavioral descriptor<input list="study-metrics" value={d.metric} onChange={e=>edit("descriptors",i,"metric",e.target.value)}/></label>{["minimum","maximum","bins"].map(k=><label key={k}>{k}<input type="number" step={k==="bins"?1:"any"} value={d[k]} onChange={e=>edit("descriptors",i,k,e.target.valueAsNumber)}/></label>)}<button className="discIcon" aria-label="Remove descriptor" onClick={()=>patch("descriptors",r.descriptors.filter((_,j)=>i!==j))}><Trash2 size={16}/></button></div>)}
    <button className="button button--secondary" disabled={r.descriptors.length>=2} onClick={()=>patch("descriptors",[...r.descriptors,{metric:metrics[r.descriptors.length]?.name||"",minimum:0,maximum:1,bins:12}])}><Plus size={14}/>Add diversity axis</button>
    <h3>3. Bound the campaign and define agreement</h3><div className="discFields discFields--four">{[["exploration_trials","Exploration trials"],["validation_finalists","Finalists to challenge"],["wall_seconds","Campaign wall seconds"],["per_trial_seconds","Per-trial wall seconds"],["seed","Random seed"],["absolute_tolerance","Absolute agreement tolerance"],["relative_tolerance","Relative agreement tolerance"]].map(([key,label])=><label key={key}>{label}<input type="number" step={key.includes("tolerance")?"any":1} value={r[key]} onChange={e=>patch(key,e.target.valueAsNumber)}/></label>)}</div>
    <div className="discNotice"><ShieldCheck size={18}/><div>Up to <strong>{r.exploration_trials+2*r.validation_finalists} local numerical trials</strong>. Finalists are compared at h, h/2 and h/4. Tolerances are frozen now, not fitted afterward. Same-engine agreement is not independent replication. Runs use bounded CPU f64 on this machine; the separate batch-search runtime can still use supported GPUs.</div></div>
    <label className="discCheck"><input type="checkbox" checked={r.auto_review} onChange={e=>patch("auto_review",e.target.checked)}/>After completion, request one metered AI review. Existing token, cost and repair limits apply; no AI-generated follow-up is run automatically.</label>
    <label className="discCheck"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>I have reviewed the metrics, parameter bounds, units, tolerances and compute budget.</label>
    {error&&<p role="alert" className="discError">{error}</p>}
    <footer><span>Creating the draft does not run anything. Launch it explicitly after reviewing the frozen protocol.</span><button className="button button--primary" disabled={busy||!approved} onClick={create}>{busy?"Saving protocol…":"Freeze study protocol"}</button></footer>
  </section>;
}
