import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {CheckCircle2,FlaskConical,Play,Plus,RefreshCw,Search,ShieldAlert,Square,GitBranch} from 'lucide-react';
import {api} from '@/lib/api';
import {useModelSelection} from '@/lib/modelSelection';
import {fmt} from '@/lib/discovery';
import {initialVerification,validateVerification,terminalVerification,displayStatus,externalMeasurements,taskProgress} from '@/lib/verification';
import ChatMarkdown from '@/components/workspace/ChatMarkdown';

export default function VerificationLab({study}) {
  const {getSelection,getSelectionError}=useModelSelection();
  const modelError=getSelectionError(study.project_id);
  const requestAdvisory=async id=>{const problem=getSelectionError(study.project_id);if(problem)throw Error(problem);const selection={...getSelection(study.project_id)};return api.verificationAgentReview(id,selection);};
  const candidates=useMemo(()=>study.trials.filter(t=>t.phase==='explore'&&t.eligible),[study.trials]);
  const [candidateId,setCandidateId]=useState(study.finalist_ids[0]||candidates[0]?.id||'');
  const selected=candidates.find(t=>t.id===candidateId)||candidates[0];
  const [protocol,setProtocol]=useState(()=>selected?initialVerification(study,selected):null);
  const [dossiers,setDossiers]=useState([]),[dossierId,setDossierId]=useState(''),[detail,setDetail]=useState(null),[catalog,setCatalog]=useState([]),[runs,setRuns]=useState([]);
  const [mode,setMode]=useState('prepare'),[approved,setApproved]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0),[probe,setProbe]=useState(null),[advisory,setAdvisory]=useState(null);
  const bump=()=>setRefresh(v=>v+1);const d=detail?.dossier,a=detail?.assessment;
  useEffect(()=>{if(selected){setProtocol(initialVerification(study,selected));setApproved(false);}},[candidateId,study.id]);
  useEffect(()=>{let gone=false;
    Promise.all([api.verificationList(study.id),api.verificationCatalog(study.project_id),api.runs(1000,study.project_id)]).then(([v,c,r])=>{
      if(gone)return;setDossiers(v.dossiers||[]);setCatalog(c.references||[]);setRuns((r.runs||[]).filter(run=>run.status==='completed'));
      setDossierId(current=>current||(v.dossiers||[])[0]?.id||'');
    }).catch(e=>{if(!gone)setError(e.message);});return()=>{gone=true;};
  },[study.id,refresh]);
  useEffect(()=>{if(!dossierId){setDetail(null);return;}let gone=false,timer,controller;
    const poll=async()=>{controller=new AbortController();try{const v=await api.verification(dossierId,controller.signal);if(gone)return;setDetail(v);timer=setTimeout(poll,terminalVerification(v.dossier.state)?12000:1600);}catch(e){if(!gone&&e.name!=='AbortError'){setError(e.message);timer=setTimeout(poll,6000);}}};poll();
    return()=>{gone=true;clearTimeout(timer);controller?.abort();};
  },[dossierId,refresh]);
  const act=async(label,fn)=>{setBusy(label);setError('');setNotice('');try{await fn();bump();}catch(e){setError(e.message);}finally{setBusy('');}};
  const patch=(key,val)=>{setApproved(false);setProtocol(p=>({...p,[key]:val}));};
  const updateRule=(i,key,value)=>patch('metrics',protocol.metrics.map((r,j)=>j===i?{...r,[key]:value}:r));
  const freeze=()=>act('freeze',async()=>{const problem=validateVerification(protocol,study);if(problem)throw Error(problem);const v=await api.createVerification(protocol);setDossierId(v.dossier.id);setMode('evidence');setNotice('Exact candidate, protocol, controls, corpus and tool hashes frozen. Approve the separate compute budget to execute verification.');});
  const live=d&&!terminalVerification(d.state);
  return <section className="verificationLab">
    <header className="verificationHero"><div><span className="eyebrow">CANDIDATE → EVIDENCE → PRIOR WORK → HUMAN REVIEW</span><h2>Interesting is not the same as new.</h2><p>Separate numerical agreement, behavior under new perturbations, and comparison with existing work. Keep every uncertainty visible.</p></div><button className="button button--secondary" disabled={!!busy} onClick={()=>act('probe',async()=>setProbe(await api.probeVerification()))}><RefreshCw size={15}/>Check independent worker</button></header>
    {probe&&<p className={probe.available?'discSuccess':'discNotice'}>{probe.available?`Python worker ready: ${probe.interpreter}. No API key required.`:probe.error}</p>}
    {error&&<div role="alert" className="discError"><ShieldAlert size={16}/><span>{error}</span><button onClick={()=>setError('')}>×</button></div>}
    {notice&&<div role="status" className="discSuccess">{notice}</div>}
    {!candidates.length?<section className="discoveryCard discEmpty"><FlaskConical size={28}/><h3>Run a bounded discovery study first</h3><p>Only completed, feasible candidates can enter a verification dossier. Failed trials remain in the study ledger.</p></section>:<>
      <nav className="verificationTabs" aria-label="Verification sections">{[['prepare','1 · Freeze protocol'],['evidence','2 · Independent evidence'],['prior','3 · Compare prior work'],['review','4 · Review & handoff']].map(([id,label])=><button key={id} className={mode===id?'active':''} onClick={()=>setMode(id)}>{label}</button>)}</nav>
      {mode==='prepare'&&protocol&&<section className="discoveryCard verificationProtocol">
        <h3>Choose exactly what needs to survive</h3><p className="discNotice">This protocol is frozen <strong>after exploratory selection but before independent checks</strong>. It is not external preregistration. Defaults are suggestions, not scientific justification; review physical scales, units and acceptable changes.</p>
        <div className="discFields"><label>Candidate<select value={candidateId} onChange={e=>setCandidateId(e.target.value)}>{candidates.map(t=><option key={t.id} value={t.id}>Trial {t.index}{study.finalist_ids.includes(t.id)?' · frozen finalist':''} · {study.recipe.objectives[0].metric}={fmt(t.metrics[study.recipe.objectives[0].metric])}</option>)}</select></label><label>Verification question<textarea value={protocol.question} onChange={e=>patch('question',e.target.value)} rows={2}/></label></div>
        {study.base_manifest.model.kind!=='state_vector_ode'&&<p className="discError">The independent engine in this release supports ODE manifests only. Particle and biomolecular verification require another scientific engine; they will not be substituted with fake ODE results.</p>}
        <div className="verificationTable" tabIndex={0} role="region" aria-label="Metric comparison rules"><table><thead><tr><th>Measured metric</th><th>Feature scale</th><th>Solver agreement absolute</th><th>Solver agreement relative</th><th>Allowed perturbation change (absolute)</th></tr></thead><tbody>{protocol.metrics.map((r,i)=><tr key={i}><td><input aria-label={`Metric ${i+1}`} list="verify-metric-names" value={r.metric} onChange={e=>updateRule(i,'metric',e.target.value)}/></td>{['scale','absolute_tolerance','relative_tolerance','robustness_absolute'].map(k=><td key={k}><input aria-label={`${r.metric} ${k}`} type="number" step="any" value={r[k]} onChange={e=>updateRule(i,k,e.target.valueAsNumber)}/></td>)}</tr>)}</tbody></table></div>
        <datalist id="verify-metric-names">{Object.keys(selected?.metrics||{}).map(name=><option key={name}>{name}</option>)}</datalist>
        <div className="discActions"><button className="button button--secondary" disabled={protocol.metrics.length>=8} onClick={()=>patch('metrics',[...protocol.metrics,{metric:'',scale:1,absolute_tolerance:1e-6,relative_tolerance:.001,robustness_absolute:.01}])}><Plus size={14}/>Add metric</button>{protocol.metrics.length>1&&<button className="button button--secondary" onClick={()=>patch('metrics',protocol.metrics.slice(0,-1))}>Remove last metric</button>}</div>
        <h3>Fresh perturbations, not another fit to the winner</h3><div className="discFields discFields--four">{[['holdout_replicates','New perturbations (2–16)'],['perturb_fraction','Fraction of full parameter range'],['holdout_seed','New holdout seed'],['wall_seconds','Worker wall seconds'],['max_rhs_evaluations','Total RHS evaluation cap'],['solver_absolute_tolerance','Adaptive solver absolute tolerance'],['solver_relative_tolerance','Adaptive solver relative tolerance'],['duplicate_distance','Near-match feature distance']].map(([key,label])=><label key={key}>{label}<input type="number" step="any" value={protocol[key]} onChange={e=>patch(key,e.target.valueAsNumber)}/></label>)}</div>
        <p className="discCaption">The separate worker repeats the candidate with independently written Euler/RK4 and adaptive Dormand–Prince 5(4), then checks the new parameter perturbations. Observation summaries use the original sampling grid. Perturbation fractions refer to each parameter’s full declared range, not its current value. This is not a statistical significance test.</p>
        <h3>Declared controls</h3><p className="discCaption">Choose an already completed calibration or null/control run, a measured quantity, and its expected interval. Explain why that interval is known. No controls means an explicit review gap—not an automatic pass.</p>
        {protocol.controls.map((c,i)=><div className="verificationControl" key={i}><label>Completed control run<select value={c.run_id} onChange={e=>patch('controls',protocol.controls.map((v,j)=>j===i?{...v,run_id:e.target.value}:v))}><option value="">Select a control</option>{runs.filter(r=>r.id!==selected?.run_id).map(r=><option key={r.id} value={r.id}>{r.name} · {r.id.slice(0,8)}</option>)}</select></label>{[['metric','Expected metric','text'],['minimum','Minimum','number'],['maximum','Maximum','number'],['rationale','Why this interval is known','text']].map(([key,label,type])=><label key={key}>{label}<input type={type} step="any" value={c[key]} onChange={e=>patch('controls',protocol.controls.map((v,j)=>j===i?{...v,[key]:type==='number'?e.target.valueAsNumber:e.target.value}:v))}/></label>)}<button className="discTextButton" onClick={()=>patch('controls',protocol.controls.filter((_,j)=>j!==i))}>Remove control</button></div>)}
        <button className="button button--secondary" disabled={protocol.controls.length>=4} onClick={()=>patch('controls',[...protocol.controls,{run_id:'',metric:protocol.metrics[0]?.metric||'',minimum:0,maximum:1,rationale:''}])}><Plus size={14}/>Add known control</button>
        <ReferenceLibrary study={study} protocol={protocol} catalog={catalog} runs={runs} onChange={patch} onAdded={bump} onError={setError}/>
        <label className="discCheck"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>I reviewed measurement meanings, feature scales, tolerances, controls, reference scope and compute allocation.</label>
        <button className="button button--primary" disabled={!approved||!!busy||study.base_manifest.model.kind!=='state_vector_ode'} onClick={freeze}>Freeze verification dossier · do not run yet</button>
      </section>}
      {mode!=='prepare'&&<><label className="verificationDossierPicker">Frozen dossier<select value={dossierId} onChange={e=>setDossierId(e.target.value)}><option value="">Select a dossier</option>{dossiers.map(v=><option key={v.id} value={v.id}>{displayStatus(v.state)} · {v.question.slice(0,75)} · {v.id.slice(0,8)}</option>)}</select></label>{!d?<section className="discoveryCard discEmpty"><h3>Freeze a candidate and protocol first</h3><p>That creates a durable record without spending compute or making an AI call.</p><button className="button button--primary" onClick={()=>setMode('prepare')}>Define verification</button></section>:<>
        <section className="verificationVerdict discoveryCard"><span className="eyebrow">{displayStatus(a?.status)} · NOT A NOVELTY CERTIFICATE</span><h3>{a?.next_step||d.stage}</h3><p>Frozen protocol <code>{d.protocol_hash.slice(0,18)}…</code> · Source run <Link href={`/?run=${d.source_run.id}`}>{d.source_run.id.slice(0,12)}</Link></p><div className="verificationGates"><Gate title="Independent replay" value={a?.independent_agreement===true?'Agreement':d.result?'Disagrees / incomplete':'Not executed'} good={a?.independent_agreement===true}/><Gate title="New perturbations" value={displayStatus(a?.robustness)} good={a?.robustness==='within_declared_limits'}/><Gate title="Selected prior results" value={displayStatus(a?.catalog?.status)} good={false}/></div>
        {d.state==='draft'&&<button className="button button--primary" disabled={!!busy} onClick={()=>act('start',async()=>{await api.startVerification(d.id);setMode('evidence');})}><Play size={15}/>Approve independent checks · up to {d.protocol.wall_seconds}s</button>}
        {live&&<div className="verificationProgress"><div><progress max={taskProgress(d).total||1} value={taskProgress(d).completed}/><span>{d.completed_tasks}/{d.total_tasks} checks finished · {d.stage}</span></div><button className="button button--danger" onClick={()=>act('cancel',()=>api.cancelVerification(d.id))} disabled={!!busy}><Square size={14}/>Stop worker</button></div>}
        {d.error&&<p className="discError">{d.error}</p>}
        {terminalVerification(d.state)&&d.state!=='draft'&&<button className="button button--secondary" onClick={()=>{setMode('prepare');setApproved(false);}}><GitBranch size={15}/>Prepare a new protocol; preserve this attempt</button>}
        </section>
        {mode==='evidence'&&<VerificationEvidence dossier={d}/>}
        {mode==='prior'&&<PriorWork dossier={d} assessment={a} onChanged={bump} onError={setError}/>}
        {mode==='review'&&<HumanReview dossier={d} assessment={a} onChanged={bump} onError={setError}/>}
        {mode==='review'&&<section className="discoveryCard"><h3>Ask the Falsifier to review the gaps</h3><p>Optional metered advisory, grounded in this dossier. It cannot certify novelty or approve another experiment. Your existing Usage & cost controls and Stop all agents apply.</p><div className="discActions"><button className="button button--secondary" disabled={!!busy||live||!!modelError} onClick={()=>act('agent',async()=>setAdvisory((await requestAdvisory(d.id)).response))}>Request metered AI review</button>{modelError&&<span>{modelError} <Link href={`/?project=${study.project_id}`}>Choose in chat</Link></span>}<Link href="/usage/">Usage & stopping controls</Link></div>{advisory&&<ChatMarkdown>{advisory.assistant_message?.content||advisory.notice}</ChatMarkdown>}<p className="discCaption">The research ZIP in the Publish tab now includes these frozen inputs, worker outputs, controls, comparison records, searches and human reviews.</p></section>}
      </>}</>}
    </>}
  </section>;
}
function Gate({title,value,good}){return <article className={good?'good':''}>{good?<CheckCircle2 size={19}/>:<ShieldAlert size={19}/>}<div><small>{title}</small><strong>{value||'Not recorded'}</strong></div></article>;}

function ReferenceLibrary({study,protocol,catalog,runs,onChange,onAdded,onError}) {
  const [open,setOpen]=useState(false),[kind,setKind]=useState('local'),[runId,setRunId]=useState(''),[title,setTitle]=useState(''),[source,setSource]=useState(''),[license,setLicense]=useState(''),[text,setText]=useState('{}'),[busy,setBusy]=useState(false);
  const add=async()=>{setBusy(true);try{const values=kind==='external'?externalMeasurements(text,protocol.metrics):{};const result=await api.addVerificationReference({study_id:study.id,metric_rules:protocol.metrics,title,source,license,run_id:kind==='local'?runId:null,measurements:values});onChange('reference_ids',[...protocol.reference_ids,result.reference.id]);onAdded();setOpen(false);}catch(e){onError(e.message);}finally{setBusy(false);}};
  return <section className="verificationReferences"><h3>Freeze the numerical comparison corpus</h3><p>Matching uses your selected metric scales and the exact declared model/measurement context. It does not recognize rotated trajectories, time translations, rescaled equations, or prove equivalence. Imported external values require author verification.</p>
    <div className="verificationReferenceList">{catalog.map(r=><label className="discCheck" key={r.id}><input type="checkbox" checked={protocol.reference_ids.includes(r.id)} onChange={e=>onChange('reference_ids',e.target.checked?[...protocol.reference_ids,r.id]:protocol.reference_ids.filter(id=>id!==r.id))}/><span><strong>{r.title}</strong><small>{r.provenance_kind} · {r.source}</small></span></label>)}</div>
    {!catalog.length&&<p className="discNotice">There are no comparison records. An empty catalog can never establish that a finding is new.</p>}
    <button className="button button--secondary" onClick={()=>setOpen(v=>!v)}><Plus size={14}/>Add documented comparison</button>
    {open&&<div className="verificationReferenceForm"><div className="discFields"><label>Reference type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="local">Completed local run</option><option value="external">Author-supplied published measurements</option></select></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label></div>
      {kind==='local'?<label>Source run<select value={runId} onChange={e=>setRunId(e.target.value)}><option value="">Select completed run</option>{runs.map(r=><option key={r.id} value={r.id}>{r.name} · {r.id.slice(0,8)}</option>)}</select></label>:<label>Exact measurements as JSON<textarea rows={4} placeholder={JSON.stringify(Object.fromEntries(protocol.metrics.map(r=>[r.metric,0])),null,2)} value={text} onChange={e=>setText(e.target.value)}/></label>}
      <label>Source, DOI and location of measurement<input value={source} onChange={e=>setSource(e.target.value)} placeholder="DOI / source record and page/table; describe provenance"/></label><label>License / data permission note<input value={license} onChange={e=>setLicense(e.target.value)}/></label>
      <button className="button button--primary" disabled={busy||!title.trim()||!source.trim()||!license.trim()||(kind==='local'&&!runId)} onClick={add}>Save immutable reference</button>
    </div>}
  </section>;
}

function VerificationEvidence({dossier:d}) {
  const r=d.result;return <section className="discoveryCard"><h3>What actually survived?</h3>{!r?<p>No independent numerical evidence has been returned. A frozen plan alone is not validation.</p>:<>
    {(r.partial||r.state!=='completed')&&<p className="discError">Partial verification only. {r.checkpoint_notice||r.error||'Unfinished checks are not passing checks; inspect the retained completed steps.'}</p>}
    <p>{fmt(r.rhs_evaluations)} right-hand-side evaluations · {fmt(r.wall_seconds)} seconds · {displayStatus(r.state)}</p>
    {[['Independent implementation',r.same_method],['Independent adaptive solver',r.different_method]].map(([name,v])=><div className="verificationCheckGroup" key={name}><h4>{name} · {displayStatus(v?.status)}</h4><div className="verificationTable" tabIndex={0}><table><thead><tr><th>Metric</th><th>Recorded</th><th>Independent</th><th>Absolute difference</th><th>Allowed</th><th>Result</th></tr></thead><tbody>{(v?.comparisons||[]).map(c=><tr key={c.metric}><td>{c.metric}</td><td>{fmt(c.recorded)}</td><td>{fmt(c.independent)}</td><td>{fmt(c.absolute_difference)}</td><td>{fmt(c.threshold)}</td><td>{displayStatus(c.status)}</td></tr>)}</tbody></table></div></div>)}
    <h4>Calibration controls</h4>{!r.controls?.length?<p>No executed controls. This remains a review gap.</p>:r.controls.map((c,i)=><p key={i}>{displayStatus(c.status)} · {c.spec.metric} = {fmt(c.observed)}; expected [{fmt(c.spec.minimum)}, {fmt(c.spec.maximum)}]. {c.spec.rationale}</p>)}
    <h4>New perturbations</h4><p>{r.warning}</p><div className="verificationTable" tabIndex={0}><table><thead><tr><th>Trial</th><th>Actual parameter values</th><th>Outcome</th><th>Largest declared-metric difference</th></tr></thead><tbody>{(r.holdouts||[]).map(h=><tr key={h.index}><td>{h.index}</td><td>{h.values.map(fmt).join(' · ')}</td><td>{displayStatus(h.status)}</td><td>{fmt(Math.max(...h.comparisons.map(c=>c.absolute_difference??NaN)))}</td></tr>)}</tbody></table></div>
    <p className="discNotice">Agreement checks implementation. Perturbations test the declared tolerance neighborhood. Neither establishes stability for all initial conditions or scientific novelty. A sensitive result may still be useful, but requires a different, explicitly justified claim.</p>
  </>}<EvidenceInspector runId={d.source_run.id}/></section>;
}
function EvidenceInspector({runId}) {
  const [series,setSeries]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[result,setResult]=useState(null),[error,setError]=useState('');
  const inspect=async()=>{try{setError('');setResult(await api.evidenceWindow(runId,{series:series||undefined,start:start===''?undefined:Number(start),end:end===''?undefined:Number(end),max_points:256}));}catch(e){setError(e.message);}};
  return <details className="verificationInspector"><summary>Inspect a recorded signal window</summary><div className="discFields"><label>Series name (blank = first 32)<input value={series} onChange={e=>setSeries(e.target.value)}/></label><label>Start time<input type="number" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End time<input type="number" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><button className="button button--secondary" onClick={inspect}>Read recorded samples</button>{error&&<p className="discError">{error}</p>}{result&&<><p>{result.boundary}</p>{result.series.map((s,i)=><Signal key={s.name+i} value={s}/>)}</>}</details>;
}
function Signal({value:s}) {
  const points=(s.points||[]).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1]));
  if(points.length<2)return <p>{s.name}: fewer than two finite samples in this window.</p>;
  const xmin=points[0][0],xmax=points.at(-1)[0],ymin=Math.min(...points.map(p=>p[1])),ymax=Math.max(...points.map(p=>p[1]));
  if(![xmax-xmin,ymax-ymin].every(Number.isFinite))return <p>Plot range is nonfinite. Inspect the raw evidence.</p>;
  return <div className="verificationSignal"><strong>{s.name} · {s.returned_points}/{s.matching_recorded_points} recorded samples</strong><svg viewBox="0 0 700 180" role="img" aria-label={`${s.name} recorded points`}><path d="M50 15V150H680" className="axes"/>{points.map(([x,y],i)=><circle key={i} cx={50+620*(x-xmin)/Math.max(Number.EPSILON,xmax-xmin)} cy={150-125*(y-ymin)/Math.max(Number.EPSILON,ymax-ymin)} r={1.8}/>)}</svg><small>{fmt(xmin)} → {fmt(xmax)} model time; values {fmt(ymin)} → {fmt(ymax)} {s.unit||'model units'}. {s.sampled?'Subsampled for display; extrema can be missed.':'Every recorded point in the requested window.'}</small></div>;
}
function PriorWork({dossier:d,assessment:a,onChanged,onError}) {
  const [query,setQuery]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false);
  const search=async()=>{setBusy(true);try{await api.verificationSearch(d.id,query,consent);onChanged();}catch(e){onError(e.message);}finally{setBusy(false);}};
  return <section className="discoveryCard"><h3>Nearest documented numerical results</h3><p>{a.catalog.boundary}</p><p><strong>{a.catalog.compared}</strong> compatible records compared; {a.catalog.excluded} excluded. Frozen threshold: {fmt(a.catalog.threshold)}.</p>
    {!a.catalog.nearest?.length&&<p className="discNotice">No comparable reference. Add documented measurements and freeze a new dossier; do not interpret this as novelty.</p>}
    {a.catalog.nearest.map(m=><article className="verificationPriorResult" key={m.reference_id}><strong>{m.title}</strong><p>{m.source}</p><span>{m.near_match?'Near match in chosen features':'Outside chosen feature threshold'} · normalized distance {fmt(m.distance)}</span><small>Provenance: {m.provenance_kind} · frozen hash {m.content_hash.slice(0,16)}</small></article>)}
    <h3>Record the literature search—not just its best hit</h3><p>Only the query you approve leaves this machine. Crossref returns bibliographic metadata, not full-paper understanding. Search failures and empty results remain in this record.</p>
    <label>Public bibliographic query<input value={query} maxLength={300} onChange={e=>setQuery(e.target.value)}/></label><label className="discCheck"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Send this query to public Crossref. I have removed confidential details.</label>
    <button className="button button--secondary" disabled={busy||!consent||query.trim().length<3||!terminalVerification(d.state)} onClick={search}><Search size={14}/>{busy?'Searching…':'Search and retain record'}</button>
    {a.searches.map(s=><article key={s.id} className="verificationSearchRecord"><h4>{s.query}</h4><small>{s.provider} · {displayStatus(s.status)} · {new Date(s.retrieved_at).toLocaleString()}</small><p>{s.scope}</p>{s.error&&<p className="discError">{s.error}</p>}{s.references.map(r=><div key={r.doi}><strong>{r.title}</strong><span>{r.year||'Year not supplied'} · {r.authors.slice(0,3).join(', ')}</span><a href={r.url} target="_blank" rel="noreferrer">{r.doi}</a></div>)}</article>)}
  </section>;
}
function HumanReview({dossier:d,assessment:a,onChanged,onError}) {
  const [r,setR]=useState({reviewer:'',disposition:'inconclusive',comparison_notes:'',limitations:'',examined_sources:[],full_text_reviewed:false});const [sources,setSources]=useState(''),[busy,setBusy]=useState(false);
  const patch=(key,value)=>setR(old=>({...old,[key]:value}));
  const save=async()=>{setBusy(true);try{await api.saveVerificationReview(d.id,{...r,examined_sources:sources.split('\n').map(s=>s.trim()).filter(Boolean)});onChanged();}catch(e){onError(e.message);}finally{setBusy(false);}};
  return <section className="discoveryCard"><h3>Make the comparison accountable</h3><div className="discGaps">{a.gaps.map((gap,i)=><p key={i}><ShieldAlert size={14}/>{gap}</p>)}</div><p className="discNotice">A review records a scientist’s judgment; it cannot bypass missing numerical evidence. Adding a new search changes the evidence hash and requires a new review. No automatic publication, priority claim, proof or novelty certificate is issued.</p>
    <div className="discFields"><label>Responsible reviewer<input value={r.reviewer} onChange={e=>patch('reviewer',e.target.value)}/></label><label>Provisional interpretation<select value={r.disposition} onChange={e=>patch('disposition',e.target.value)}><option value="inconclusive">Inconclusive</option><option value="artifact_or_failed">Artifact or failed validation</option><option value="rediscovery">Rediscovery / existing result</option><option value="potentially_distinct">Potentially distinct; needs external review</option></select></label></div>
    <label>What was compared, and what is substantively different?<textarea rows={4} value={r.comparison_notes} onChange={e=>patch('comparison_notes',e.target.value)}/></label><label>Remaining limitations and attempts to disprove the interpretation<textarea rows={3} value={r.limitations} onChange={e=>patch('limitations',e.target.value)}/></label><label>Examined sources (DOI/identifier and pages; one per line)<textarea rows={3} value={sources} onChange={e=>setSources(e.target.value)}/></label><label className="discCheck"><input type="checkbox" checked={r.full_text_reviewed} onChange={e=>patch('full_text_reviewed',e.target.checked)}/>I have read the relevant source texts, not only metadata or AI summaries.</label>
    <button className="button button--primary" disabled={busy||!terminalVerification(d.state)||!r.reviewer.trim()||r.comparison_notes.trim().length<20||r.limitations.trim().length<10} onClick={save}>Record signed-by-name review</button>
    {a.reviews.map(v=><article className="verificationPriorResult" key={v.id}><strong>{v.review.reviewer} · {displayStatus(v.review.disposition)}</strong><p>{v.review.comparison_notes}</p><small>{new Date(v.recorded_at).toLocaleString()} · {v.evidence_hash===a.evidence_hash?'Review matches current evidence snapshot':'Earlier evidence snapshot; re-review required'} · local attribution, not cryptographic identity verification</small></article>)}
  </section>;
}
