import {fieldColor,fieldCell} from './laboratory-field.mjs';
import {installCameraNavigation} from './viewer-camera.mjs';
import {releaseRenderer,disposeObjectTree} from './viewer-resources.mjs';
import {advanceRenderClock} from './viewer-cadence.mjs';

/** An unlit quantitative plane: pixel colors encode saved cell values, never generated motion. */
export async function createFieldViewer(host,{index,options,onCameraChange,onSelect,signal}){
  const THREE=await import('three'),{OrbitControls}=await import('three/examples/jsm/controls/OrbitControls.js');if(signal.aborted)return null;
  const scene=new THREE.Scene(),renderer=new THREE.WebGLRenderer({antialias:true}),span=Math.max(index.lx,index.ly),scale=4/span,center=new THREE.Vector3(index.lx/2,index.ly/2,0);
  renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;host.replaceChildren(renderer.domElement);
  const texture=new THREE.DataTexture(new Uint8Array(index.nx*index.ny*4),index.nx,index.ny);texture.colorSpace=THREE.SRGBColorSpace;texture.magFilter=THREE.NearestFilter;texture.minFilter=THREE.NearestFilter;texture.flipY=false;
  const plane=new THREE.Mesh(new THREE.PlaneGeometry(index.lx*scale,index.ly*scale),new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide,toneMapped:false}));scene.add(plane);
  const outline=new THREE.LineSegments(new THREE.EdgesGeometry(plane.geometry),new THREE.LineBasicMaterial({color:'#a8c5df'}));scene.add(outline);
  const selection=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-.5,-.5,0),new THREE.Vector3(.5,-.5,0),new THREE.Vector3(.5,.5,0),new THREE.Vector3(-.5,.5,0)]),new THREE.LineBasicMaterial({color:'#ffffff',depthTest:false}));selection.renderOrder=10;selection.visible=false;scene.add(selection);
  const camera=new THREE.PerspectiveCamera(35,1,.01,500),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.screenSpacePanning=true;controls.minDistance=.01;controls.maxDistance=300;
  let disposed=false,raf=0,frame=null,stamp='',dirty=true,selectedCell=null,down=null,lastDraw=0,suppress=false;
  const state=()=>({position:camera.position.clone().divideScalar(scale).add(center).toArray(),target:controls.target.clone().divideScalar(scale).add(center).toArray(),up:camera.up.toArray(),fov:camera.fov,units:index.length_unit});
  const report=()=>{dirty=true;if(!suppress)onCameraChange?.(state());};
  controls.addEventListener('change',()=>{dirty=true;});controls.addEventListener('end',report);
  function fit(view='front',selected=false){const target=selected&&selectedCell?new THREE.Vector3(...selectedCell.position,0).sub(center).multiplyScalar(scale):new THREE.Vector3();controls.target.copy(target);camera.up.set(0,1,0);const radius=selected?Math.max(index.lx/index.nx,index.ly/index.ny)*scale*3:Math.hypot(index.lx,index.ly)*scale/2,angle=Math.min(THREE.MathUtils.degToRad(camera.fov)/2,Math.atan(Math.tan(THREE.MathUtils.degToRad(camera.fov)/2)*camera.aspect)),distance=radius/Math.sin(angle)*1.12,direction=view==='perspective'?new THREE.Vector3(.3,-.55,1).normalize():new THREE.Vector3(0,0,1);camera.position.copy(target).addScaledVector(direction,distance);controls.update();report();}
  function setCamera(value,{silent=false}={}){if(!value)return;for(const key of ['position','target','up'])if(value[key]&&(!Array.isArray(value[key])||value[key].length!==3||!value[key].every(Number.isFinite)))return;suppress=silent;try{if(value.position)camera.position.set(...value.position).sub(center).multiplyScalar(scale);if(value.target)controls.target.set(...value.target).sub(center).multiplyScalar(scale);if(value.up)camera.up.set(...value.up).normalize();if(Number.isFinite(value.fov)){camera.fov=Math.max(10,Math.min(90,value.fov));camera.updateProjectionMatrix();}controls.update();report();}finally{suppress=false;}}
  const resize=()=>{renderer.setSize(Math.max(1,host.clientWidth),Math.max(1,host.clientHeight),false);camera.aspect=Math.max(1,host.clientWidth)/Math.max(1,host.clientHeight);camera.updateProjectionMatrix();dirty=true;};const observer=new ResizeObserver(resize);observer.observe(host);resize();
  const navigation=installCameraNavigation(THREE,{camera,controls,element:renderer.domElement,span:4,onChange:report,fit});suppress=true;fit();setCamera(options().camera,{silent:true});suppress=false;
  function apply(){const opts=options(),next=JSON.stringify([opts.colorLow,opts.colorHigh,opts.contrast,opts.background,opts.selectedCell]);if(next===stamp)return;stamp=next;scene.background=new THREE.Color(opts.background||'#080f20');dirty=true;
    if(frame){let p=0;for(const row of frame.values)for(const value of row){const color=fieldColor(value,index.color_scale,opts);texture.image.data[p++]=color[0];texture.image.data[p++]=color[1];texture.image.data[p++]=color[2];texture.image.data[p++]=255;}texture.needsUpdate=true;}
    const cell=opts.selectedCell;if(cell&&Number.isInteger(cell.x)&&Number.isInteger(cell.y)&&cell.x>=0&&cell.x<index.nx&&cell.y>=0&&cell.y<index.ny){selectedCell=fieldCell(index,(cell.x+.5)/index.nx,(cell.y+.5)/index.ny);selection.position.set(selectedCell.position[0]-center.x,selectedCell.position[1]-center.y,0).multiplyScalar(scale);selection.scale.set(index.lx/index.nx*scale,index.ly/index.ny*scale,1);selection.visible=true;}else{selectedCell=null;selection.visible=false;}}
  const render=()=>{apply();controls.update();renderer.render(scene,camera);dirty=false;};
  function draw(now){if(disposed)return;raf=requestAnimationFrame(draw);if(document.hidden)return;const clock=advanceRenderClock(now,lastDraw,1000/60);if(clock===null)return;lastDraw=clock;apply();controls.update();if(dirty)render();}raf=requestAnimationFrame(draw);
  const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();const pointerdown=e=>{down=[e.clientX,e.clientY];},pointerup=e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;down=null;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2);ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(plane)[0];if(hit?.uv){const cell=fieldCell(index,hit.uv.x,hit.uv.y);onSelect?.({...cell,value:frame?.values[cell.y][cell.x],time:frame?.time});}};
  renderer.domElement.addEventListener('pointerdown',pointerdown);renderer.domElement.addEventListener('pointerup',pointerup);
  const dispose=()=>{if(disposed)return;disposed=true;cancelAnimationFrame(raf);observer.disconnect();navigation.dispose();controls.dispose();renderer.domElement.removeEventListener('pointerdown',pointerdown);renderer.domElement.removeEventListener('pointerup',pointerup);texture.dispose();disposeObjectTree(scene);releaseRenderer(renderer);signal.removeEventListener('abort',dispose);};signal.addEventListener('abort',dispose,{once:true});
  return {dispose,fit,setCamera,cameraState:state,navigate:navigation.command,focusSelection:()=>fit('front',true),setFrame:value=>{frame=value;stamp='';dirty=true;},capture:()=>{
    if(!frame)return null;render();const canvas=document.createElement('canvas');canvas.width=renderer.domElement.width;canvas.height=renderer.domElement.height+110;const ctx=canvas.getContext('2d');ctx.drawImage(renderer.domElement,0,0);const pad=18,barWidth=Math.min(280,canvas.width-2*pad),y=canvas.height-62;ctx.fillStyle='#07101f';ctx.fillRect(0,renderer.domElement.height,canvas.width,110);for(let i=0;i<barWidth;i++){ctx.fillStyle=`rgb(${fieldColor(index.color_scale.min+(index.color_scale.max-index.color_scale.min)*i/(barWidth-1),index.color_scale,options()).join(',')})`;ctx.fillRect(pad+i,y,1,12);}ctx.fillStyle='#e2ecfc';ctx.font='13px sans-serif';ctx.fillText(`${index.field_name} [${index.field_unit}] · t = ${frame.time.toPrecision(6)} ${index.time_unit}`,pad,y-14);ctx.fillText(`${index.color_scale.min.toPrecision(5)} → ${index.color_scale.max.toPrecision(5)} · fixed range`,pad,y+32);ctx.fillText(`${index.nx} × ${index.ny} · ${index.lx} × ${index.ly} ${index.length_unit} · row 0 = low y`,pad,y+50);
    return {dataUrl:canvas.toDataURL('image/png'),viewport:{width:renderer.domElement.width,height:renderer.domElement.height},annotations:{placement:'below',height:110},time:frame.time,recordedTime:frame.time,timeUnit:index.time_unit,frame:frame.step,camera:state(),presentation:options(),field_sha256:frame.source_sha256,view_sha256:frame.view_sha256,source_path:frame.source_path,representation:'scalar_field',selectedCell:selectedCell?{...selectedCell,value:frame.values[selectedCell.y][selectedCell.x]}:null};
  }};
}
